const fs = require('fs'), vm = require('vm'), assert = require('assert');
const core = fs.readFileSync('web/master-editor/core.js','utf8');
const tools = fs.readFileSync('web/master-editor/tools.js','utf8');
const text = fs.readFileSync('web/master-editor/text.js','utf8');
const section = {cover:true,spineColor:'#123456',spreads:[{pages:[{layers:[{id:'a',type:'rect'},{id:'spine',type:'text',pin:'spine',spineContent:true}]},{layers:[{id:'b',type:'photo'}]}]}]};
let commits = 0;
const c = vm.createContext({section:()=>section,preview:false,view:{spread:0},selected:[],focusCell:null,commit:fn=>{commits++;fn();}});
vm.runInContext(core.slice(core.indexOf('function spreadStack('),core.indexOf('function commit(')),c);
vm.runInContext(tools.slice(tools.indexOf('function layerPanelAction('),tools.indexOf('function action(')),c);
vm.runInContext(tools.slice(tools.indexOf('function restackOrder('),tools.indexOf('function copyLayers(')),c);
const sp=section.spreads[0];
c.layerPanelAction('a','forward');
assert.deepEqual(Array.from(c.stackGroups(sp)[0],l=>l.id),['b','a']);
c.layerPanelAction('a','forward'); assert.equal(commits,1,'cannot cross the spine band');
c.layerPanelAction('b','visibility');assert.equal(sp.pages[1].layers[0].hidden,true);
c.layerPanelAction('b','visibility');assert.equal(sp.pages[1].layers[0].hidden,false);
c.layerPanelAction('b','lock');assert.equal(sp.pages[1].layers[0].locked,true);
c.layerPanelAction('b','delete');assert.equal(sp.pages[1].layers.length,0);
c.layerPanelAction('missing','delete');assert.equal(commits,5);
c.preview=true;c.layerPanelAction('a','delete');assert.equal(commits,5);
// Corner warnings concern rendered text; empty resolved chips have no printed content.
const fragment=text.slice(text.indexOf('    overflowDetails()'),text.indexOf('    _render(ctx)',text.indexOf('    overflowDetails()')));
const Frame = vm.runInNewContext('(class { '+fragment+' })');
const frame=new Frame(); Object.assign(frame,{text:'Школа № 5',width:40,height:6,contentHeight:5.6,_textLines:[['Школа № 5']],getLineWidth:()=>23});
assert.equal(frame.overflows(),false);
frame.height=5;assert.equal(frame.overflowDetails().height,true);
frame.height=6;frame.getLineWidth=()=>50;assert.equal(frame.overflowDetails().width,true);
frame.text='';assert.equal(frame.overflows(),false);
frame.text='Школа № 5';frame.fit=true;assert.equal(frame.overflows(),false);
console.log('Layer actions and text overflow regressions passed');
