const fs=require('fs'),vm=require('vm'),assert=require('assert');
const source=fs.readFileSync('web/v2.js','utf8');
const state={selected:new Set(),order:{persons:[{id:'a',name:'Анна'}],photos:[{id:'1',filename:'1.jpg',person_id:'a',status:'ready',uncertain:1},{id:'2',filename:'2.jpg',person_id:'a',status:'ready',uncertain:0},{id:'3',filename:'3.jpg',person_id:null,status:'no_face'}]}};
const c=vm.createContext({state,esc:s=>String(s),personName:p=>p.name,statuses:{no_face:'Лицо не найдено'}});
for(const n of ['matchReference','canConfirmMatch','matchCaption','photoTile'])vm.runInContext(source.split('\n').find(l=>l.startsWith('function '+n+'(')),c);
assert(vm.runInContext('canConfirmMatch(state.order.photos[0])',c));
assert(!vm.runInContext('canConfirmMatch(state.order.photos[2])',c));
const ordinary=vm.runInContext('photoTile(state.order.photos[0])',c);
assert(!ordinary.includes('match-target')&&!ordinary.includes('Проверьте совпадение'));
const ready=vm.runInContext('photoTile(state.order.photos[1])',c);
assert(!ready.includes('Готово')&&!ready.includes('Назначено'));
const tile=vm.runInContext('photoTile(state.order.photos[0],true)',c);
assert(tile.includes('Анна')&&tile.includes('/media/2/thumb'));
state.order.photos=state.order.photos.filter(p=>p.id!=='2');
assert(!vm.runInContext('canConfirmMatch(state.order.photos[0])',c));
assert(vm.runInContext('matchCaption(state.order.photos[0])',c).includes('Нет другого снимка'));
console.log('Match targets, reference images and eligibility: OK');
const elements={};
c.$=selector=>elements[selector]||(elements[selector]={innerHTML:''});
c.icon=()=>'';
c.renderProgress=()=>{};
c.renderPhotos=()=>{};
state.view='photos';
vm.runInContext(source.split('\n').find(l=>l.startsWith('function shootBody(')),c);
for(const filter of ['all','pending','error','review']){
  state.photoFilter=filter;
  const html=vm.runInContext("shootBody({id:'shoot',kind:'portrait'})",c);
  assert.strictEqual(html.includes('data-v2="confirm-photos"'),filter==='review');
  assert.strictEqual(html.includes('data-v2="select-matches"'),filter==='review');
  assert.strictEqual(html.includes('confirmation-help'),filter==='review');
}
console.log('Confirmation controls appear only in review mode: OK');
for(const n of ['needsReview','visiblePhotos','shootStatus','renderWorkspace'])vm.runInContext(source.split('\n').find(l=>l.startsWith('function '+n+'(')),c);
c.photoLabel=n=>`${n} фото`;
state.order.shoots=[{id:'portrait',kind:'portrait',title:'Портреты'},{id:'general',kind:'general',title:'Прогулка'}];
state.order.photos=[{id:'p',shoot_id:'portrait',status:'ready',uncertain:1},{id:'g',shoot_id:'general',shoot_type:'general',status:'ready'}];
state.shootId=undefined;state.photoFilter='all';
vm.runInContext('renderWorkspace()',c);
assert.equal(state.shootId,'portrait');
assert.equal(vm.runInContext('visiblePhotos().length',c),1);
assert.equal((elements['#workspace'].innerHTML.match(/aria-expanded="true"/g)||[]).length,1);
state.shootId='general';
vm.runInContext('renderWorkspace()',c);
assert.equal(vm.runInContext('visiblePhotos()[0].id',c),'g');
assert(!elements['#workspace'].innerHTML.includes('data-action="move"'));
assert(!elements['#workspace'].innerHTML.includes('data-photo-filter="review"'));
assert(!vm.runInContext('needsReview(state.order.photos[1])',c));
state.shootId=null;
vm.runInContext('renderWorkspace()',c);
assert(!elements['#workspace'].innerHTML.includes('aria-expanded="true"'));
console.log('Shoot galleries, collapse state and general-shoot controls: OK');
