const fs=require('fs'),vm=require('vm'),assert=require('assert');
const source=fs.readFileSync('web/v2.js','utf8');
const names=['needsReview','stats','cardStatus','clientProgress'];
const context=vm.createContext({esc:s=>String(s),stageLabel:k=>k});
for(const n of names)vm.runInContext(source.split('\n').find(l=>l.startsWith('function '+n+'(')),context);
const o={id:'x',stage:'forms',photo_count:100,pending:0,review_count:3,client_progress:{enabled:true,status:'in_progress',label:'Клиенты заполняют',completed:7,total:16,remaining:9}};
context.o=o;
assert.equal(vm.runInContext('cardStatus(o).text',context),'Заполнили 7 из 16');
assert.equal(vm.runInContext('cardStatus(o).kind',context),'waiting');
assert.equal(vm.runInContext('cardStatus(o).action',context),undefined);
assert(vm.runInContext('clientProgress(o)',context).includes('Заполнено 7 из 16'));
o.client_progress.status='complete';
assert.equal(vm.runInContext('cardStatus(o).text',context),'Все заполнили');
assert.equal(vm.runInContext('cardStatus(o).kind',context),'done');
assert.equal(vm.runInContext('cardStatus(o).action[0]',context),'make-layout');
assert.equal(vm.runInContext('cardStatus(o).tab',context),'client');
o.stage='photos';o.pending=40;
assert.equal(vm.runInContext('cardStatus(o).text',context),'Обработка 60%');
o.pending=0;
assert.equal(vm.runInContext('cardStatus(o).text',context),'Проверить 3 фото');
assert.equal(vm.runInContext('cardStatus(o).tab',context),'review');
o.review_count=0;
assert.equal(vm.runInContext('cardStatus(o).action[0]',context),'send-forms');
o.stage='approval';o.approved=true;
assert.equal(vm.runInContext('cardStatus(o).text',context),'Согласовано');
o.stage='delivery';
assert.equal(vm.runInContext('cardStatus(o).text',context),'В доставке');
console.log('Order card status by stage: OK');
