const fs=require('fs'),vm=require('vm'),assert=require('assert');
const source=fs.readFileSync('web/v2.js','utf8');
const state={selected:new Set(),order:{persons:[{id:'a',name:'Анна'}],photos:[{id:'1',filename:'1.jpg',person_id:'a',status:'ready',uncertain:1},{id:'2',filename:'2.jpg',person_id:'a',status:'ready',uncertain:0},{id:'3',filename:'3.jpg',person_id:null,status:'no_face'}]}};
const c=vm.createContext({state,esc:s=>String(s),personName:p=>p.name,statuses:{no_face:'Лицо не найдено'},svgIcon:()=>'',PhotoTools:{changed(){},onlyImages:f=>f}});
for(const n of ['matchReference','canConfirmMatch','matchCaption','photoTile'])vm.runInContext(source.split('\n').find(l=>l.startsWith('function '+n+'(')),c);
assert(vm.runInContext('canConfirmMatch(state.order.photos[0])',c));
assert(!vm.runInContext('canConfirmMatch(state.order.photos[2])',c));
const ordinary=vm.runInContext('photoTile(state.order.photos[0])',c);
assert(!ordinary.includes('match-target')&&!ordinary.includes('Проверьте совпадение'));
const ready=vm.runInContext('photoTile(state.order.photos[1])',c);
assert(!ready.includes('Готово')&&!ready.includes('Назначено'));
const tile=vm.runInContext('photoTile(state.order.photos[0],true)',c);
assert(tile.includes('Анна')&&tile.includes('/media/2/thumb'));
state.order.photos=state.order.photos.filter(p=>p.id!=='2');
assert(!vm.runInContext('canConfirmMatch(state.order.photos[0])',c));
assert(vm.runInContext('matchCaption(state.order.photos[0])',c).includes('Нет другого снимка'));
console.log('Match targets, reference images and eligibility: OK');
const elements={};
c.$=selector=>elements[selector]||(elements[selector]={innerHTML:''});
c.icon=()=>'';
c.renderProgress=()=>{};
c.renderPhotos=()=>{};
state.view='photos';
for(const n of ['shootBody','gridTools'])vm.runInContext(source.split('\n').find(l=>l.startsWith('function '+n+'(')),c);
c.needsReview=p=>p.status!=='ready'||p.uncertain||!p.person_id;
for(const filter of ['all','pending','error','review']){
  state.photoFilter=filter;
  const html=vm.runInContext("shootBody({id:'shoot',kind:'portrait'})",c);
  assert(!html.includes('selection-bar'),'actions live in the floating bar');
  assert(html.includes('data-photo-tools="select-all"')&&html.includes('id="choose-folder"'));
}
state.order.photos.forEach(p=>{p.shoot_id='shoot';});
const counted=vm.runInContext("shootBody({id:'shoot',kind:'portrait'})",c);
assert(counted.includes('Проверить<small>2</small>'),'review filter shows how many photos wait');
assert(counted.includes('upload-strip'),'a shoot with photos gets the compact upload row');
assert(vm.runInContext("shootBody({id:'empty',kind:'portrait'})",c).includes('class="dropzone"'));
delete c.needsReview;
console.log('Shoot body: filters with counts, compact upload, no inline action bar: OK');
for(const n of ['needsReview','visiblePhotos','shootStatus','renderWorkspace','folderCard','teacherFolderCard','fmtDate'])vm.runInContext(source.split('\n').find(l=>l.startsWith('function '+n+'(')||l.startsWith('const '+n+'=')),c);
c.photoLabel=n=>`${n} фото`;
state.order.shoots=[{id:'portrait',kind:'portrait',title:'Портреты',shot_on:'2026-09-20'},{id:'general',kind:'general',title:'Прогулка'}];
state.order.photos=[{id:'p',shoot_id:'portrait',status:'ready',uncertain:1},{id:'g',shoot_id:'general',shoot_type:'general',status:'ready'}];
state.shootId=undefined;state.photoFilter='all';
vm.runInContext('renderWorkspace()',c);
assert.equal(state.shootId,null);
assert.equal((elements['#workspace'].innerHTML.match(/data-v2="open-shoot"/g)||[]).length,2);
assert.equal((elements['#workspace'].innerHTML.match(/data-v2="shoot-menu"/g)||[]).length,2);
assert(elements['#workspace'].innerHTML.includes('20.09.2026'));
state.shootId=undefined;state.photoFilter='review';
vm.runInContext('renderWorkspace()',c);
assert.equal(state.shootId,'portrait');
state.photoFilter='all';
vm.runInContext('renderWorkspace()',c);
assert.equal(vm.runInContext('visiblePhotos().length',c),1);
assert(elements['#workspace'].innerHTML.includes('data-v2="close-shoot"'));
state.shootId='general';
vm.runInContext('renderWorkspace()',c);
assert.equal(vm.runInContext('visiblePhotos()[0].id',c),'g');
assert(!elements['#workspace'].innerHTML.includes('data-action="move"'));
assert(!elements['#workspace'].innerHTML.includes('data-photo-filter="review"'));
assert(!vm.runInContext('needsReview(state.order.photos[1])',c));
state.shootId=null;
vm.runInContext('renderWorkspace()',c);
assert(!elements['#workspace'].innerHTML.includes('aria-expanded="true"'));
console.log('Shoot galleries, collapse state and general-shoot controls: OK');
