const state={orders:[],order:null,tab:'persons',selected:new Set(),person:null,uploading:false,progress:null,query:'',period:'all'};
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icon=name=>`<img src="/static/assets/${name}.svg" alt="">`;
const money=n=>new Intl.NumberFormat('ru-RU',{maximumFractionDigits:0}).format(n)+' ₽';
const count=(n,one,few,many)=>`${n} ${n%10===1&&n%100!==11?one:n%10>=2&&n%10<=4&&(n%100<12||n%100>14)?few:many}`;
const photoLabel=n=>count(n,'фотография','фотографии','фотографий');
const statuses={pending:'В очереди',processing:'Обработка',no_face:'Лицо не найдено',multiple_faces:'Несколько лиц',small_face:'Лицо слишком маленькое',error:'Ошибка обработки',ready:'Готово'};
const stages=[['planned','Назначить съёмку','#7712b3'],['scheduled','Съёмка назначена','#5073f2'],['upload','Загрузить фотографии','#50b7f1'],['layout','Сверстать макет','#28cec5']];
let toastTimer,pollTimer,routeVersion=0,groupsSig='';
async function api(path,options={}){const r=await fetch('/api'+path,options);let value=await r.json();if(!r.ok)throw Error(typeof value.detail==='string'?value.detail:'Проверьте заполнение полей');return value;}
function json(method,body){return {method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)};}
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),4500);}
function orderName(o){return `${o.school} / ${o.class_name}`;}
function personName(p,index){return p.name||`Персона ${String(index+1).padStart(2,'0')}`;}
function openNew(){ $('#order-form').reset();$('#form-error').textContent='';$('#order-dialog').showModal(); }
function taskButton(label,action){return `<button data-action="${action}">${icon('upload')}<span>${label}</span></button>`;}
function home(){
  const orders=state.orders.filter(o=>state.period==='all'||new Date(o.created_at).getFullYear()===new Date().getFullYear());
  const copies=orders.reduce((sum,o)=>sum+o.copies,0),total=orders.reduce((sum,o)=>sum+o.copies*o.price,0),pending=state.orders.filter(o=>!o.photo_count).length;
  $('#main').innerHTML=`<h1 style="margin-left:16px">Главная</h1><section class="home-top"><div class="tasks"><h3>Список задач</h3><div class="task-body">${state.orders.length?taskButton(pending?`Загрузить портреты · ${pending} заказов`:'Открыть персоны заказов',pending?'choose-upload':'choose-persons')+`<p>Проверьте группы персон после обработки фотографий.</p>`:taskButton('Создать первый заказ','new-order')+'<p>Добавьте класс, затем загрузите портреты участников.</p>'}</div></div><div class="report"><div class="report-head"><h2>Отчёт</h2><select id="period" aria-label="Период отчёта"><option value="all" ${state.period==='all'?'selected':''}>всё время</option><option value="year" ${state.period==='year'?'selected':''}>этот год</option></select></div><div class="metrics"><div class="metric"><span>Заказов</span><strong>${orders.length}</strong></div><div class="metric"><span>Альбомов</span><strong>${copies}</strong></div><div class="metric"><span>Сумма заказов</span><strong>${money(total)}</strong></div></div><p class="report-note">По указанной стоимости · оплаты пока не учитываются</p></div></section><div class="process-head"><h1>Процесс</h1><input id="search" class="search" type="search" placeholder="Поиск заказа" aria-label="Поиск заказа" value="${esc(state.query)}"></div><section class="board" aria-label="Этапы заказов" id="board"></section>`;
  board();$('#search').addEventListener('input',e=>{state.query=e.target.value;board();});$('#period').addEventListener('change',e=>{state.period=e.target.value;home();});
}
function board(){const filtered=state.orders.filter(o=>orderName(o).toLowerCase().includes(state.query.toLowerCase()));$('#board').innerHTML=stages.map(([stage,title,color])=>{const orders=filtered.filter(o=>o.stage===stage);return `<section class="column" style="--stage:${color}"><h3>${title}<small>${orders.length}</small></h3><div class="column-body">${orders.map(o=>`<button class="order-card" data-order="${o.id}"><div class="order-card-top"><span>${esc(orderName(o))}</span>${icon('edit')}</div><small>${o.photo_count?photoLabel(o.photo_count)+' · '+count(o.person_count,'персона','персоны','персон'):count(o.copies,'альбом','альбома','альбомов')}${o.pending?' · Обработка':''}${o.client_progress?.enabled?` · ${esc(o.client_progress.label)}: ${o.client_progress.completed} из ${o.client_progress.total}`:''}</small></button>`).join('')||`<div class="column-empty">${state.query?'Ничего не найдено':stage==='planned'?'Здесь появятся новые заказы':stage==='scheduled'?'Заказы с назначенной датой съёмки':stage==='upload'?'Заказы с загруженными фотографиями':'Подготовка макетов — следующий этап'}${stage==='planned'&&!state.query?'<button data-action="new-order">＋ Создать заказ</button>':''}</div>`}</div></section>`;}).join('');}
function chooseOrders(mode){$('#main').innerHTML=`<div class="page"><div class="page-heading"><h1>${mode==='upload'?'Загрузить фотографии':'Персоны'}</h1><button class="primary" data-action="new-order">Создать заказ</button></div><p class="muted">Выберите заказ, с которым хотите работать.</p><div class="order-list">${state.orders.map(o=>`<button class="order-row" data-order="${o.id}"><div><strong>${esc(orderName(o))}</strong><p>${photoLabel(o.photo_count)} · ${count(o.person_count,'персона','персоны','персон')}</p></div><span>Открыть →</span></button>`).join('')||'<div class="empty-state"><h3>Пока нет заказов</h3><p>Создайте заказ для первого класса.</p></div>'}</div></div>`;}
function orderPage(){const o=state.order;const pending=o.photos.filter(p=>['pending','processing'].includes(p.status)).length;$('#main').innerHTML=`<div class="page"><div class="eyebrow"><a href="#home">Главная</a> / Заказ</div><div class="page-heading"><h1>${esc(orderName(o))}</h1><button class="secondary" data-action="new-order">Новый заказ</button></div><div class="order-summary"><span class="pill">${count(o.copies,'альбом','альбома','альбомов')}</span><span class="pill">${photoLabel(o.photos.length)}</span><span class="pill">${count(o.persons.length,'персона','персоны','персон')}</span>${o.shoot_date?`<span class="pill">Съёмка ${esc(o.shoot_date.split('-').reverse().join('.'))}</span>`:''}${o.client_progress?.enabled?`<span class="pill">${esc(o.client_progress.label)} · ${o.client_progress.completed} из ${o.client_progress.total}</span>`:''}${pending?`<span class="pill processing">В обработке: ${pending}</span>`:''}</div><section class="panel"><h2>Портретные фотографии</h2><a class="secondary" href="/v2#order/${o.id}/client">Кабинет клиента →</a><div class="dropzone" id="dropzone">${icon('upload')}<h3>Перетащите фотографии сюда</h3><p>JPG, JPEG или PNG, до 30 МБ на файл. Персоны определятся автоматически.</p><button class="primary" id="choose-files">Выбрать фотографии</button><input id="files" class="file-input" type="file" accept=".jpg,.jpeg,.png,.JPG,.JPEG,.PNG,image/jpeg,image/png,image/jpg" multiple aria-label="Выбрать портретные фотографии"></div><div class="upload-status" id="upload-status" aria-live="polite"></div></section><div id="groups"></div><p class="model-note">Фотографии хранятся на этом компьютере. Группировка по лицам может ошибаться — проверьте результат.</p></div>`;
  $('#choose-files').onclick=()=>$('#files').click();$('#files').onchange=e=>uploadFiles([...e.target.files]);const drop=$('#dropzone');drop.ondragover=e=>{e.preventDefault();drop.classList.add('drag');};drop.ondragleave=()=>drop.classList.remove('drag');drop.ondrop=e=>{e.preventDefault();drop.classList.remove('drag');uploadFiles([...e.dataTransfer.files]);};renderProgress();renderGroups();
}
function renderGroups(){if(!$('#groups'))return;const o=state.order,unassigned=o.photos.filter(p=>(!p.person_id||p.uncertain)&&!['pending','processing'].includes(p.status)),pending=o.photos.filter(p=>['pending','processing'].includes(p.status)).length;$('#groups').innerHTML=`<div class="section-head"><h2>Персоны <span class="muted">${o.persons.length}</span></h2><div class="tabs"><button data-tab="persons" class="${state.tab==='persons'?'active':''}">По персонам</button><button data-tab="review" class="${state.tab==='review'?'active':''}">Проверить · ${unassigned.length}</button></div></div>${state.tab==='persons'?`<div class="person-grid">${o.persons.map((p,i)=>{const photos=o.photos.filter(f=>f.person_id===p.id);if(!photos.length)return '';return `<button class="person-card" data-person="${p.id}"><img src="/media/${photos[0].id}/thumb" alt="${esc(personName(p,i))}" loading="lazy" decoding="async">${photos.some(f=>f.uncertain)?'<span class="badge">Проверьте совпадение</span>':''}<div class="person-caption"><h3>${esc(personName(p,i))}</h3><p>${photoLabel(photos.length)}</p></div></button>`;}).join('')}</div>${!o.persons.length?`<div class="empty-state"><h3>${pending?'Ищем лица на фотографиях':'Персоны появятся здесь'}</h3><p>${pending?'Обработка идёт на компьютере. Можно продолжить загрузку.':unassigned.length?'Откройте «Проверить»: некоторым фотографиям нужна ваша помощь.':'Загрузите портреты — система соберёт снимки одного человека в группу.'}</p></div>`:''}`:`${unassigned.some(p=>p.status==='error')?'<div class="warning">Некоторые снимки не удалось обработать. <button class="link-button" data-action="retry">Повторить обработку</button></div>':''}${unassigned.length?`<p class="muted small">Выберите фотографии одного человека и назначьте им персону вручную.</p><div class="selection-bar"><span id="review-selected">Выбрано: ${state.selected.size}</span><button class="secondary" data-action="move">Назначить персону</button></div><div class="photo-grid">${unassigned.map(photoTile).join('')}</div>`:'<div class="empty-state"><h3>Нет фотографий для проверки</h3><p>Кадры без лица и с несколькими лицами появятся здесь.</p></div>'}`}`;groupsSig=orderSignature(o);}
function photoTile(p){return `<label class="photo-tile"><img src="/media/${p.id}/thumb" alt="${esc(p.filename)}" loading="lazy" decoding="async"><input type="checkbox" data-photo="${p.id}" ${state.selected.has(p.id)?'checked':''}><p title="${esc(p.filename)}">${esc(p.filename)}</p>${p.assignment_source==='sequence'?`<small>${p.uncertain?'По серии · проверить':'По серии'}</small>`:''}${p.status!=='ready'?`<small>${statuses[p.status]||'Проверить'}</small>`:''}</label>`;}
function orderSignature(o){return state.tab+'|'+o.persons.map(p=>p.id+':'+p.name).join(',')+'|'+o.photos.map(p=>[p.id,p.status,p.person_id||'',p.uncertain?1:0,p.error||'',p.filename].join(':')).join(';');}
function syncSummary(o){const summary=$('.order-summary');if(!summary)return;const pending=o.photos.filter(p=>['pending','processing'].includes(p.status)).length;summary.innerHTML=`<span class="pill">${count(o.copies,'альбом','альбома','альбомов')}</span><span class="pill">${photoLabel(o.photos.length)}</span><span class="pill">${count(o.persons.length,'персона','персоны','персон')}</span>${o.shoot_date?`<span class="pill">Съёмка ${esc(o.shoot_date.split('-').reverse().join('.'))}</span>`:''}${o.client_progress?.enabled?`<span class="pill">${esc(o.client_progress.label)} · ${o.client_progress.completed} из ${o.client_progress.total}</span>`:''}${pending?`<span class="pill processing">В обработке: ${pending}</span>`:''}`;}
function startOrderPolling(){clearInterval(pollTimer);pollTimer=setInterval(()=>refreshOrder().catch(()=>{}),1800);}
function stopOrderPollingIfIdle(){const busy=state.order?.photos.some(p=>['pending','processing'].includes(p.status));if(!busy&&!state.order?.client_progress?.enabled){clearInterval(pollTimer);pollTimer=null;}}
function renderProgress(){const el=$('#upload-status');if(!el)return;const p=state.progress;el.innerHTML=p?`<progress max="${p.total}" value="${p.done}"></progress><span>${state.uploading?'Загружаем':'Загрузка завершена'}: ${p.done} из ${p.total}${p.duplicates?` · Уже были загружены: ${p.duplicates}`:''}</span>${p.errors.length?`<div class="upload-error">${p.errors.map(esc).join('<br>')}</div>`:''}`:'';}
async function uploadFiles(files){if(state.uploading){toast('Дождитесь завершения текущей загрузки');return;}if(!files.length)return;const orderId=state.order.id;const allowed=f=>{const type=(f.type||'').toLowerCase();const name=f.name.toLowerCase();return ['image/jpeg','image/jpg','image/pjpeg','image/png','image/x-png'].includes(type)||/\.(jpe?g|png)$/.test(name);};state.uploading=true;state.progress={total:files.length,done:0,duplicates:0,errors:[]};renderProgress();const queue=[...files];const concurrency=Math.min(6,queue.length);const worker=async()=>{while(queue.length){const file=queue.shift();try{if(!allowed(file))throw Error('Нужен файл JPG, JPEG или PNG');if(file.size>30*1024*1024)throw Error('Файл больше 30 МБ');const r=await api(`/orders/${orderId}/photos?filename=${encodeURIComponent(file.name)}`,{method:'POST',headers:{'Content-Type':'application/octet-stream'},body:file});if(r.duplicate)state.progress.duplicates++;}catch(e){state.progress.errors.push(file.name+': '+e.message);}state.progress.done++;renderProgress();}};await Promise.all(Array.from({length:concurrency},()=>worker()));state.uploading=false;renderProgress();toast(state.progress.errors.length?'Загрузка завершена с ошибками — проверьте список':'Фотографии загружены. Группируем по персонам.');if(state.order?.id===orderId){await refreshOrder();startOrderPolling();}}
function showPerson(id){const o=state.order,index=o.persons.findIndex(p=>p.id===id),person=o.persons[index];if(!person)return;state.person=id;state.selected.clear();const photos=o.photos.filter(p=>p.person_id===id);$('#person-content').innerHTML=`<div class="dialog-heading"><h2 id="person-title">${esc(personName(person,index))}</h2><button class="close" data-close="person-dialog" aria-label="Закрыть">×</button></div><form id="name-form" class="name-form"><input name="name" placeholder="Имя и фамилия" aria-label="Имя персоны" maxlength="100" value="${esc(person.name)}"><button class="secondary" type="submit">Сохранить имя</button></form><p class="muted small">${photoLabel(photos.length)}. Выберите снимки, чтобы перенести их в другую группу или выделить в новую персону.</p><div class="selection-bar"><span id="person-selected">Выбрано: 0</span><button class="text-button" data-action="select-all">Выбрать все</button><button class="secondary" data-action="move">Перенести</button></div><div class="photo-grid">${photos.map(photoTile).join('')}</div>`;$('#name-form').onsubmit=async e=>{e.preventDefault();try{await api(`/orders/${o.id}/persons/${id}`,json('PATCH',{name:new FormData(e.target).get('name')}));await refreshOrder();const name=state.order.persons.find(p=>p.id===id)?.name;$('#person-title').textContent=name||personName(person,index);toast('Имя сохранено');}catch(e){toast(e.message);}};if(!$('#person-dialog').open)$('#person-dialog').showModal();}
function openMove(){if(!state.selected.size){toast('Сначала выберите фотографии');return;}showPersonPicker({order:state.order,selected:[...state.selected],api,esc,personName});$('#move-dialog').showModal();}
async function refreshOrder(){const id=state.order?.id;if(!id)return;const fresh=await api('/orders/'+id);if(state.order?.id!==id)return;const sig=orderSignature(fresh);state.order=fresh;if(sig!==groupsSig)renderGroups();syncSummary(fresh);stopOrderPollingIfIdle();}
async function route(){const version=++routeVersion;clearInterval(pollTimer);pollTimer=null;groupsSig='';state.selected.clear();state.person=null;const hash=location.hash.slice(1)||'home';document.querySelectorAll('nav a').forEach(a=>a.classList.toggle('active',a.dataset.nav===hash||(hash.startsWith('order/')&&a.dataset.nav==='upload')));try{if(hash.startsWith('order/')){const order=await api('/orders/'+encodeURIComponent(hash.split('/')[1]));if(version!==routeVersion)return;state.order=order;state.tab='persons';orderPage();if(order.client_progress?.enabled||order.photos.some(p=>['pending','processing'].includes(p.status)))startOrderPolling();}else{state.order=null;const orders=await api('/orders');if(version!==routeVersion)return;state.orders=orders;if(['upload','persons'].includes(hash))chooseOrders(hash);else home();}}catch(e){$('#main').innerHTML=`<div class="page"><h1>Не удалось открыть страницу</h1><p class="error">${esc(e.message)}</p><a href="#home" class="secondary">На главную</a></div>`;}}
document.addEventListener('click',async e=>{const target=e.target.closest('[data-action],[data-order],[data-close],[data-tab],[data-person]');if(!target)return;if(target.dataset.order){location.hash='order/'+target.dataset.order;return;}if(target.dataset.close){$('#'+target.dataset.close).close();return;}if(target.dataset.tab){state.tab=target.dataset.tab;state.selected.clear();renderGroups();return;}if(target.dataset.person){showPerson(target.dataset.person);return;}switch(target.dataset.action){case'new-order':openNew();break;case'choose-upload':location.hash='upload';break;case'choose-persons':location.hash='persons';break;case'move':openMove();break;case'select-all':document.querySelectorAll('#person-dialog [data-photo]').forEach(input=>{input.checked=true;state.selected.add(input.dataset.photo);});$('#person-selected').textContent='Выбрано: '+state.selected.size;break;case'retry':try{await api(`/orders/${state.order.id}/retry`,json('POST',{}));toast('Обработка запущена повторно');startOrderPolling();await refreshOrder();}catch(e){toast(e.message);}break;}});
document.addEventListener('change',e=>{if(e.target.dataset.photo){if(e.target.checked)state.selected.add(e.target.dataset.photo);else state.selected.delete(e.target.dataset.photo);for(const id of ['#person-selected','#review-selected'])if($(id))$(id).textContent='Выбрано: '+state.selected.size;}});
$('#order-form').onsubmit=async e=>{e.preventDefault();const button=e.target.querySelector('[type=submit]');button.disabled=true;$('#form-error').textContent='';const values=Object.fromEntries(new FormData(e.target));values.copies=Number(values.copies);values.price=Number(values.price);try{const result=await api('/orders',json('POST',values));$('#order-dialog').close();location.hash='order/'+result.id;toast('Заказ создан. Можно загрузить портреты.');}catch(error){$('#form-error').textContent=error.message;}finally{button.disabled=false;}};
$('#move-form').onsubmit=async e=>{e.preventDefault();const button=e.target.querySelector('[type=submit]');button.disabled=true;try{await api(`/orders/${state.order.id}/move`,json('POST',{photo_ids:[...state.selected],person_id:new FormData(e.target).get('target')||null}));$('#move-dialog').close();$('#person-dialog').close();state.selected.clear();await refreshOrder();toast('Фотографии перенесены');}catch(error){toast(error.message);}finally{button.disabled=false;}};
window.addEventListener('hashchange',route);window.addEventListener('beforeunload',e=>{if(state.uploading){e.preventDefault();e.returnValue='';}});route();
