const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const token=encodeURIComponent(location.pathname.split('/')[2]);
const base='/client-api/'+token;
let order,filter='all',query='',searchOpen=false,chosen=null,version=0,layoutView=null,layoutOwner=null,zoomIndex=0,screen='';
const sections={cover:'Обложка',intro:'Наш выпуск',personal:'Портрет',teachers:'Наши учителя',students:'Наш класс',moments:'Вместе',story:'В деталях',final:'Финал',custom:'Разворот'};
const ICONS={user:'<circle cx="12" cy="8" r="4"/><path d="M4 21c0-4 3.6-6 8-6s8 2 8 6"/>',arrow:'<path d="M7 17 17 7M8 7h9v9"/>',back:'<path d="m15 18-6-6 6-6"/>',search:'<circle cx="11" cy="11" r="7"/><path d="m20 20-3.5-3.5"/>',doc:'<path d="M14 3H6v18h12V7z"/><path d="M14 3v4h4M9 12h6M9 16h3"/><path d="m14.5 17.5 1.5 1.5 3-3"/>',truck:'<path d="M3 6h11v10H3zM14 10h4l3 3v3h-7"/><circle cx="7" cy="18" r="2"/><circle cx="17" cy="18" r="2"/>',download:'<path d="M12 4v11m-5-5 5 5 5-5M4 20h16"/>',zoom:'<circle cx="11" cy="11" r="7"/><path d="m20 20-3.5-3.5M11 8v6M8 11h6"/>',pencil:'<path d="M4 20h4L20 8l-4-4L4 16z"/><path d="m14 6 4 4"/>',check:'<path d="m5 12 5 5 9-10"/>',camera:'<path d="M4 8h3l2-3h6l2 3h3v11H4z"/><circle cx="12" cy="13" r="3.5"/>',text:'<path d="M5 6h14M12 6v13M9 19h6"/>',spread:'<rect x="3" y="5" width="18" height="14" rx="1.5"/><path d="M12 5v14"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',key:'<circle cx="8" cy="15" r="4"/><path d="m11 12 9-9M17 6l3 3"/>',logout:'<path d="M10 4H5v16h5M14 8l4 4-4 4M18 12H9"/>',plus:'<path d="M12 5v14M5 12h14"/>',trash:'<path d="M4 7h16M9 7V4h6v3M6 7l1 13h10l1-13"/>'};
const icon=(n,size=20)=>`<svg width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${ICONS[n]}</svg>`;
const LOGO='<svg width="30" height="24" viewBox="0 0 48.14 38.55" aria-hidden="true"><path d="M0 12.77 1.95 0l40.11 3.19.97 5.4z"/><path d="M48.14 12.77 5.1 16.69l.98 7.62 42.06.73z"/><path d="m1.95 28.48 40.11 1.72-4.62 5.89-31.36 2.46z"/></svg>';

async function api(path='',options={}){const r=await fetch(base+path,options);const text=await r.text();let data=null;if(text){try{data=JSON.parse(text);}catch{data={detail:text};}}if(!r.ok){const err=Error(typeof data?.detail==='string'?data.detail:(text||'Проверьте заполнение полей'));err.status=r.status;throw err;}return data??{};}
function json(body,method='POST'){return {method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)};}
const src=(id,variant='thumb')=>`${base}/photos/${encodeURIComponent(id)}/${variant}`;
const name=(p,i)=>p.first_name?`${p.first_name} ${p.last_name}`:p.name||`Участник ${String(i+1).padStart(2,'0')}`;
const personName=p=>name(p,order.persons.indexOf(p));
function notice(message){const el=$('#notice');el.textContent=message;el.classList.add('show');clearTimeout(notice.timer);notice.timer=setTimeout(()=>el.classList.remove('show'),3500);}
function quoteMax(){return typeof order?.quote_limit==='number'?order.quote_limit:300;}
function applyQuoteLimit(){const el=$('#selection-form').elements.quote;const max=quoteMax();el.maxLength=max;if(el.value.length>max)el.value=el.value.slice(0,max);$('#characters').textContent=`${el.value.length} / ${max}`;}
function show(html){$('#main').innerHTML=html;}
// A 401 means either the class session expired (entry) or the customer code is needed (manage).
function failed(err,box){if(err.status===401&&/управлени/i.test(err.message)){askManager();return;}if(err.status===401){showEntry();return;}if(box)box.textContent=err.message;else notice(err.message);}

const brandBar=(account=true)=>`<header class="bar"><a class="brand" href="#" aria-label="На главную">${LOGO}<span>ФАБРИКА<br>АЛЬБОМОВ</span></a>${account?`<a class="icon-btn dark" href="#account" aria-label="Аккаунт: ${order?.manager?'заказчик':'родители'}">${icon('user')}${order?.manager?'<i class="dot"></i>':''}</a>`:''}</header>`;
const backBar=(href,right='')=>`<header class="bar"><a class="icon-btn" href="${href}" aria-label="Назад">${icon('back')}</a>${right}</header>`;

function pinBoxes(id){return `<div class="pin" id="${id}" role="group" aria-label="Четырёхзначный код">${[0,1,2,3].map(i=>`<input inputmode="numeric" pattern="[0-9]*" autocomplete="${i?'off':'one-time-code'}" aria-label="Цифра ${i+1}" data-pin="${i}">`).join('')}</div>`;}
function wirePin(box,onFull){const inputs=[...box.querySelectorAll('input')];const value=()=>inputs.map(i=>i.value).join('');inputs.forEach((input,i)=>{input.oninput=()=>{const digits=input.value.replace(/\D/g,'');if(digits.length>1){digits.slice(0,4-i).split('').forEach((d,k)=>inputs[i+k].value=d);}else input.value=digits;if(!digits)return;const next=inputs.find(x=>!x.value);(next||inputs[3]).focus();if(value().length===4)onFull?.(value());};input.onkeydown=e=>{if(e.key==='Backspace'&&!input.value&&i)inputs[i-1].focus();if(e.key==='ArrowLeft'&&i)inputs[i-1].focus();if(e.key==='ArrowRight'&&i<3)inputs[i+1].focus();};input.onfocus=()=>input.select();});inputs[0].focus();return {value,clear(){inputs.forEach(i=>i.value='');inputs[0].focus();}};}

function showEntry(){screen='entry';show(`<div class="screen narrow">${brandBar(false)}<form id="entry-form" class="code-screen"><h1>Вход<br>в кабинет</h1><p>Введите код, который выдал фотограф. Он один для всего класса.</p><div class="code-field"><strong>Введите код</strong>${pinBoxes('entry-pin')}<p id="pin-error" class="error" role="alert"></p></div><button class="primary" type="submit">Войти</button></form></div>`);const pin=wirePin($('#entry-pin'),()=>$('#entry-form').requestSubmit());$('#entry-form').onsubmit=async e=>{e.preventDefault();const button=e.target.querySelector('[type=submit]');if(pin.value().length<4){$('#pin-error').textContent='Введите четыре цифры';return;}button.disabled=true;$('#pin-error').textContent='';try{await api('/enter',json({pin:pin.value()}));await load();}catch(err){$('#pin-error').textContent=err.message||'Неверный код';pin.clear();button.disabled=false;}};}

// ---------- Home: the order status ----------
function stageCards(){const st=order.stage,total=order.persons.length,done=order.completed,all=total&&done===total,fixes=order.corrections.length;const cards=[];
  const selection={key:'selection',href:'#people'};
  if(st==='selection')Object.assign(selection,{state:'active',tone:'yellow',title:'Выбор портретов',text:all?'Все участники выбрали портреты. Фотограф скоро приступит к вёрстке.':'Вёрстка начнётся, когда все участники выберут портрет и внесут информацию.',foot:`${icon('user',18)} ${done}/${total}`});
  else Object.assign(selection,{state:'done',title:'Портреты выбраны',text:`${done} из ${total} участников`});
  cards.push(selection);
  const t=order.teachers;
  selection.title='Сбор данных';
  selection.text=`Анкеты детей: ${done} из ${total}.`;
  selection.foot='';
  selection.parts=`<div class="collection-parts"><a href="#people">${icon('user',18)}<span><strong>Анкеты детей</strong><small>${done} из ${total}</small></span>${icon('arrow',18)}</a>${t?.school?`<a href="#teachers">${icon('user',18)}<span><strong>Выбор учителей</strong><small>Выбрано ${t.chosen+t.proposed}${t.class_teacher?' · '+esc(t.class_teacher):''}${t.unsigned?' · Подписать фото: '+t.unsigned:''}</small></span>${icon('arrow',18)}</a>`:''}</div>`;
  delete selection.href;
  const layout={key:'layout',icon:'doc'};
  if(st==='selection')Object.assign(layout,{state:'next',title:'Согласование макета',text:'Будет доступно после выбора всех фотографий.'});
  else if(st==='layout')Object.assign(layout,{state:'active',tone:'soft',title:'Фотограф верстает макет',text:'Когда макет будет готов, он появится здесь для проверки.',icon:'clock'});
  else if(st==='updating')Object.assign(layout,{state:'active',tone:'soft',title:'Фотограф вносит правки',text:'Обновлённый макет появится здесь. Пока можно посмотреть предыдущую версию.',href:'#layout',icon:'clock'});
  else if(st==='approval')Object.assign(layout,{state:'active',tone:'blue',title:'Согласование макета',text:fixes?`Вы отправили правки: ${fixes}. Фотограф исправит макет и пришлёт новую версию.`:'Проверьте макет перед тем, как мы приступим к печати. Убедитесь, что имена написаны правильно, а фотографии — верные.',href:'#layout'});
  else Object.assign(layout,{state:'done',title:'Макет согласован',text:'Посмотреть согласованную версию',href:'#layout'});
  cards.push(layout);
  const d=order.delivery,where=d?(d.mode==='personal'?'Получение лично у фотографа.':`Отправка${d.carrier?' · '+d.carrier:''}${d.address?' · '+d.address:''}`):'';
  const delivery={key:'delivery',icon:'truck',title:'Доставка'};
  if(['selection','layout','updating','approval'].includes(st))Object.assign(delivery,{state:'next',text:'Будет доступно после согласования макета.'});
  else if(st==='approved')Object.assign(delivery,{state:'active',tone:'green',title:'Готовим к печати',text:`Макет согласован. Фотограф отправит альбомы в типографию. ${where}`});
  else if(st==='print')Object.assign(delivery,{state:'active',tone:'green',title:'Альбомы в печати',text:`Типография печатает ваши альбомы. ${where}`});
  else if(st==='delivery')Object.assign(delivery,{state:'active',tone:'green',title:'Альбомы в пути',text:where||'Фотограф передал альбомы в доставку.'});
  else Object.assign(delivery,{state:'done',title:'Альбомы доставлены',text:'Спасибо, что были с нами!'});
  cards.push(delivery);
  const rank={active:0,extra:1,next:2,done:3};return cards.sort((a,b)=>rank[a.state]-rank[b.state]);}
function cardHtml(c){const tag=c.href&&c.state!=='next'?'a':'div',attrs=tag==='a'?` href="${esc(c.href)}"${c.external?' target="_blank" rel="noopener"':''}`:'';const badge=c.state==='done'?`<span class="card-icon done">${icon('check')}</span>`:c.state==='active'&&c.tone!=='soft'?(c.href?`<span class="card-icon">${icon('arrow')}</span>`:''):c.icon?`<span class="card-icon ${c.state==='extra'?'dark':''}">${icon(c.icon)}</span>`:'';return `<${tag} class="card ${c.state} ${c.tone||''}"${attrs}><div class="card-body"><h2>${esc(c.title)}</h2><p>${esc(c.text)}</p>${c.parts||''}</div>${c.foot?`<div class="card-foot"><span>${c.foot}</span>${badge}</div>`:badge}</${tag}>`;}
function drawHome(){screen='home';const cards=stageCards();const done=cards.filter(c=>c.state==='done');show(`<div class="screen narrow">${brandBar()}<p class="eyebrow">${esc(order.school)} · ${esc(order.class_name)}</p><h1 class="status-title">Статус заказа:</h1><div class="cards">${cards.filter(c=>c.state!=='done').map(cardHtml).join('')}</div>${done.length?`<p class="section-label">Готово</p><div class="cards">${done.map(cardHtml).join('')}</div>`:''}</div>`);}

// ---------- Portraits ----------
function peopleCards(){const people=order.persons.filter(p=>(filter!=='todo'||!p.photo_id)&&personName(p).toLowerCase().includes(query.toLowerCase()));$('#people').innerHTML=people.map(p=>{const photos=order.photos.filter(f=>f.person_id===p.id),cover=p.photo_id||photos[0]?.id,who=personName(p);return `<a class="tile" href="#person/${encodeURIComponent(p.id)}" aria-label="${esc(who)}${p.submitted?', анкета отправлена':''}">${cover?`<img src="${src(cover)}" alt="" loading="lazy">`:`<span class="tile-empty">${icon('camera',28)}</span>`}${p.submitted?`<span class="tile-mark done">${icon('check',16)}</span>`:p.photo_id?`<span class="tile-mark">${icon('pencil',16)}</span>`:''}<span class="caption"><strong>${esc(who)}</strong>${photos.length?'':'<small>Фото готовятся</small>'}</span></a>`;}).join('')||`<div class="empty">${order.persons.length?'Никого не найдено. Измените поиск или фильтр.':'Фотограф готовит ваши фотографии. Участники появятся здесь после обработки.'}</div>`;}
function drawPeople(){screen='people';const searching=query||searchOpen;show(`<div class="screen">${backBar('#',`<button type="button" class="icon-btn" id="toggle-search" aria-label="Поиск" aria-expanded="${!!searching}">${icon('search')}</button>`)}<h1>Выберите<br>портрет</h1><p class="muted lead">Найдите себя, выберите фото и добавьте подпись. Готово: ${order.completed} из ${order.persons.length}.</p><input type="search" id="search" class="search" placeholder="Найти по имени" aria-label="Найти по имени" value="${esc(query)}" ${searching?'':'hidden'}><div class="segmented" role="group"><button data-filter="all" class="${filter==='all'?'active':''}" aria-pressed="${filter==='all'}">Все</button><button data-filter="todo" class="${filter==='todo'?'active':''}" aria-pressed="${filter==='todo'}">Без портрета</button></div><div class="grid" id="people"></div></div>`);peopleCards();$('#search').oninput=e=>{query=e.target.value;peopleCards();};$('#toggle-search').onclick=()=>{const el=$('#search');searchOpen=el.hidden;el.hidden=!searchOpen;$('#toggle-search').setAttribute('aria-expanded',searchOpen);if(searchOpen)el.focus();else if(query){query='';el.value='';peopleCards();}};}
function drawPerson(id){const p=order.persons.find(x=>x.id===id);if(!p){location.hash='people';return;}screen='person';const who=esc(personName(p));if(p.photo_locked){const cover=p.photo_id;show(`<div class="screen narrow">${backBar('#people')}<h1>${p.submitted?'Анкета отправлена':'Ваш портрет'}</h1>${cover?`<img class="locked-photo" src="${src(cover,'full')}" alt="Выбранный портрет">`:'<p class="muted">Портрет ещё не выбран.</p>'}<h2 class="person-name">${who}</h2>${p.submitted?(p.quote?`<blockquote>${esc(p.quote)}</blockquote>`:''):`<p class="muted">Портрет уже выбран. Можно уточнить имя и цитату, затем отправить анкету.</p><button type="button" class="primary" id="fill-form">Отправить анкету</button>`}${p.submitted?'<p class="muted small">Заметили ошибку в имени? Её можно исправить на этапе согласования макета.</p>':''}</div>`);const fill=$('#fill-form');if(fill)fill.onclick=()=>openForm(p,cover);return;}
  const photos=order.photos.filter(f=>f.person_id===p.id);show(`<div class="screen">${backBar('#people')}<h1>Выберите<br>портрет</h1><p class="muted lead">${who} · нажмите на фото, чтобы добавить подпись.</p><div class="grid gallery">${photos.map((f,i)=>`<button class="tile" data-photo="${esc(f.id)}" aria-label="Выбрать фотографию ${i+1}"><img src="${src(f.id)}" alt="" loading="lazy">${p.photo_id===f.id?`<span class="tile-mark done">${icon('check',16)}</span>`:''}</button>`).join('')||'<div class="empty">Фотографии ещё готовятся.</div>'}</div></div>`);}
function openForm(p,photoId){if(!photoId){notice('Сначала выберите портрет');return;}chosen={photo_id:photoId,person_id:p.id};const form=$('#selection-form');form.reset();form.elements.first_name.value=p.first_name||'';form.elements.last_name.value=p.last_name||'';form.elements.quote.value=p.quote||'';applyQuoteLimit();$('#error').textContent='';$('#preview').src=src(photoId,'full');form.querySelector('[type=submit]').disabled=false;$('#selection').showModal();}

// ---------- Teachers: sign the photographer's shots, then pick who goes into the album ----------
const teacherDraftKey='album-teachers-'+token;
let teacherDraft={};try{teacherDraft=JSON.parse(sessionStorage.getItem(teacherDraftKey)||'{}');}catch{}
function persistTeacherDraft(){try{sessionStorage.setItem(teacherDraftKey,JSON.stringify(teacherDraft));}catch{}}
function signSection(photos){if(!photos.groups.length)return '';const thumb=id=>`${base}/teacher-photos/${encodeURIComponent(id)}/thumb`;return `<section class="sign-section"><h2 class="teacher-section">Кто на фото?</h2><p class="muted">Фотограф снял учителей, но их имена ещё не подписаны. Кадр уже выбрал фотограф. Укажите, кто на фото. После подписи группа уйдёт из списка. Если ошиблись, фотограф сможет отменить подпись. Если вы учитель — подпишите себя.</p><div class="sign-list">${photos.groups.map((g,i)=>`<form class="sign-card" data-sign="${esc(g.id)}"><div class="sign-frames"><input type="hidden" name="photo" value="${esc(g.photos[0])}"><img class="teacher-sign-photo" src="${thumb(g.photos[0])}" alt="Портрет учителя ${i+1}" loading="lazy"></div><div class="sign-fields form"><label>Кто это?<select name="teacher_id"><option value="">Выберите учителя</option>${photos.teachers.map(t=>`<option value="${esc(t.id)}">${esc(t.name)}${t.subject?' · '+esc(t.subject):''}</option>`).join('')}<option value="new">Нет в списке — вписать</option></select></label><div class="sign-new" hidden><label>Фамилия<input name="last_name" maxlength="60" autocomplete="off"></label><label>Имя<input name="first_name" maxlength="60" autocomplete="off"></label><label>Отчество<input name="patronymic" maxlength="60" autocomplete="off"></label><label>Предмет <span class="muted">· необязательно</span><input name="subject" maxlength="100" autocomplete="off"></label></div><button type="button" class="secondary" data-sign-preview>Посмотреть фото крупно</button><p class="sign-error error" role="alert"></p><button class="primary" type="submit">Подписать</button></div></form>`).join('')}</div></section>`;}
function bindSigning(){document.querySelectorAll('[data-sign]').forEach(form=>{const select=form.elements.teacher_id,extra=form.querySelector('.sign-new');const d=teacherDraft.signs?.[form.dataset.sign];if(d){for(const [key,value] of Object.entries(d)){const el=form.elements[key];if(el)el.value=value;}}extra.hidden=select.value!=='new';const store=()=>{teacherDraft.signs||={};teacherDraft.signs[form.dataset.sign]=Object.fromEntries(new FormData(form));persistTeacherDraft();};form.oninput=store;form.onchange=store;form.querySelector('[data-sign-preview]').onclick=()=>{const id=form.elements.photo.value;$('#teacher-zoom-image').src=`${base}/teacher-photos/${encodeURIComponent(id)}/full`;$('#teacher-zoom').showModal();};select.onchange=()=>{extra.hidden=select.value!=='new';if(!extra.hidden)form.elements.last_name.focus();};form.onsubmit=async e=>{e.preventDefault();const error=form.querySelector('.sign-error'),button=form.querySelector('[type=submit]');error.textContent='';const v=Object.fromEntries(new FormData(form));if(!v.teacher_id){error.textContent='Выберите учителя из списка или впишите его.';return;}if(v.teacher_id==='new'&&(!v.last_name.trim()||!v.first_name.trim())){error.textContent='Укажите фамилию и имя учителя.';return;}const body=v.teacher_id==='new'?{teacher:{last_name:v.last_name,first_name:v.first_name,patronymic:v.patronymic,subject:v.subject}}:{teacher_id:v.teacher_id};button.disabled=true;try{const saved=await api(`/teacher-photos/${encodeURIComponent(v.photo)}/sign`,json(body));captureTeacherChoice();if(teacherDraft.signs)delete teacherDraft.signs[form.dataset.sign];persistTeacherDraft();await refresh();await drawTeachers();notice(`Спасибо! Фото подписано: ${saved.name}`);}catch(err){failed(err,error);button.disabled=false;}};});}
// The class's pick lives in the page until it is saved: ids in album order, the class teacher, subjects for this class.
let teacherData=null,pick=null,teacherQuery='',teacherFilter='all',teacherSearchOpen=false,sheetTarget=null;
const pickKey=p=>JSON.stringify([p.ids,p.lead,p.subjects]);
function savedPick(d){return {ids:d.teachers.filter(t=>t.selected).map(t=>t.id),lead:d.class_teacher_id||null,subjects:{}};}
function captureTeacherChoice(){if(!pick||!teacherData)return;if(pickKey(pick)===pickKey(savedPick(teacherData)))delete teacherDraft.choice;else teacherDraft.choice={...pick,known:teacherData.teachers.map(t=>t.id)};persistTeacherDraft();}
// A draft survives a reload; teachers added meanwhile (a confirmed proposal) join it, and a confirmed class teacher stays.
function restoreTeacherChoice(d){const fresh=savedPick(d),draft=teacherDraft.choice;if(!draft)return fresh;const ids=new Set(d.teachers.map(t=>t.id)),known=new Set(draft.known||[]);
  const kept=[...draft.ids.filter(id=>ids.has(id)),...fresh.ids.filter(id=>!known.has(id)&&!draft.ids.includes(id))];
  const lead=kept.includes(draft.lead)||d.proposals.some(p=>p.id===draft.lead)?draft.lead:draft.lead?fresh.lead:null;
  return {ids:kept,lead,subjects:Object.fromEntries(Object.entries(draft.subjects||{}).filter(([id])=>kept.includes(id)))};}
const teacherSubject=t=>pick.subjects[t.id]??t.subject;
const initialsOf=t=>[t.last_name,t.first_name].map(x=>(x||'').trim().charAt(0)).join('').toUpperCase()||'?';
const teacherPortrait=t=>t.has_portrait?`<img src="${base}/teachers/${encodeURIComponent(t.id)}/portrait?v=${encodeURIComponent(t.portrait_version)}" alt="" loading="lazy">`:`<span class="tile-initials" aria-hidden="true">${esc(initialsOf(t))}</span>`;
const shortName=t=>[t.last_name,...[t.first_name,t.patronymic].filter(Boolean).map(x=>x.charAt(0)+'.')].join(' ');
function teacherTile(t,proposal=false){const locked=teacherData.locked,on=proposal||pick.ids.includes(t.id),lead=pick.lead===t.id,subject=proposal?t.subject:teacherSubject(t);
  return `<div class="tile teacher-tile${on?' on':''}${proposal?' proposed':''}">${proposal||locked?`<span class="tile-hit">${teacherPortrait(t)}</span>`:`<button type="button" class="tile-hit" data-pick="${esc(t.id)}" aria-pressed="${on}" aria-label="${esc(t.name)}">${teacherPortrait(t)}</button>`}${on&&!proposal?`<span class="tile-mark done">${icon('check',16)}</span>`:''}${on&&!locked?`<button type="button" class="tile-edit" data-teacher-edit="${esc(t.id)}" aria-label="${proposal?'Предложенный учитель':'Предмет и классный руководитель'}">${icon('pencil',15)}</button>`:''}<span class="caption">${lead?'<em class="lead-badge">Классный руководитель</em>':''}<strong>${esc(t.last_name)}<br>${esc([t.first_name,t.patronymic].filter(Boolean).join(' '))}</strong><small>${proposal?'Ждёт фотографа':esc(subject)}</small></span></div>`;}
function paintTeachers(){const d=teacherData,q=teacherQuery.trim().toLowerCase(),fits=t=>t.name.toLowerCase().includes(q),locked=d.locked;
  const list=d.teachers.filter(t=>(teacherFilter==='all'&&!locked||pick.ids.includes(t.id))&&fits(t)),offered=d.proposals.filter(fits);
  $('#teacher-grid').innerHTML=list.map(t=>teacherTile(t)).join('')+offered.map(p=>teacherTile(p,true)).join('')+(locked||q?'':`<button type="button" class="tile add-tile" data-propose>${icon('plus',26)}<span>Нет в списке</span></button>`)||`<div class="empty">${q?'Никого не найдено.':'Учителя не выбраны.'}</div>`;
  const n=pick.ids.length+d.proposals.length,lead=[...d.teachers,...d.proposals].find(t=>t.id===pick.lead);
  const seg=$('#teacher-filter');if(seg)seg.querySelector('[data-tfilter=picked]').textContent=`Выбраны · ${n}`;
  const dock=$('#teacher-dock');if(dock){const changed=!d.chosen||pickKey(pick)!==pickKey(savedPick(d));dock.querySelector('.dock-count').innerHTML=`Выбрано: ${n}${lead?` · <span>кл. руководитель ${esc(shortName(lead))}</span>`:''}`;const b=dock.querySelector('.primary');b.disabled=!changed;b.textContent=changed?'Сохранить выбор':'Выбор сохранён';}}
async function drawTeachers(){screen='teachers';const v=version;show(`<div class="screen narrow">${backBar('#')}<h1>Учителя альбома</h1><p class="loading">Загружаем учителей…</p></div>`);let data,photos;try{[data,photos]=await Promise.all([api('/teachers'),api('/teacher-photos')]);}catch(err){if(v!==version)return;if(err.status===401){failed(err);return;}show(`<div class="screen narrow">${backBar('#')}<h1>Учителя недоступны</h1><p class="muted">${esc(err.message)}</p></div>`);return;}if(v!==version||screen!=='teachers')return;
  if(!data.school){show(`<div class="screen narrow">${backBar('#')}<h1>Учителя альбома</h1><p class="muted">Фотограф ещё не добавил учителей вашей школы.</p></div>`);return;}
  if(teacherDraft.school!==data.school.id){teacherDraft={school:data.school.id};persistTeacherDraft();}
  teacherData=data;pick=restoreTeacherChoice(data);const locked=data.locked,searching=teacherQuery||teacherSearchOpen;
  show(`<div class="screen${locked?'':' with-dock'}">${backBar('#',locked?'':`<button type="button" class="icon-btn" id="toggle-teacher-search" aria-label="Поиск" aria-expanded="${!!searching}">${icon('search')}</button>`)}<p class="eyebrow">${esc(order.school)} · ${esc(order.class_name)}</p><h1>Учителя<br>альбома</h1>${signSection(photos)}${locked?'<p class="banner">Альбом в печати — состав учителей не меняется.</p>':`<p class="muted lead">Нажмите на учителей, которые будут в альбоме.</p><input type="search" id="teacher-search" class="search" placeholder="Найти по имени" aria-label="Найти по имени" value="${esc(teacherQuery)}" ${searching?'':'hidden'}><div class="segmented" id="teacher-filter" role="group"><button data-tfilter="all" class="${teacherFilter==='all'?'active':''}" aria-pressed="${teacherFilter==='all'}">Все</button><button data-tfilter="picked" class="${teacherFilter==='picked'?'active':''}" aria-pressed="${teacherFilter==='picked'}">Выбраны</button></div>`}<div class="grid teacher-grid" id="teacher-grid"></div>${locked?'':`<div class="dock" id="teacher-dock"><p class="dock-count"></p><p id="teachers-error" class="error" role="alert"></p><button type="button" class="primary" data-teachers-save>Сохранить выбор</button></div>`}</div>`);
  paintTeachers();bindSigning();if(locked)return;
  const search=$('#teacher-search');search.oninput=()=>{teacherQuery=search.value;paintTeachers();};
  $('#toggle-teacher-search').onclick=()=>{teacherSearchOpen=search.hidden;search.hidden=!teacherSearchOpen;$('#toggle-teacher-search').setAttribute('aria-expanded',teacherSearchOpen);if(teacherSearchOpen)search.focus();else if(teacherQuery){teacherQuery='';search.value='';paintTeachers();}};
  $('#main .screen').onclick=e=>{const f=e.target.closest('[data-tfilter]');if(f){teacherFilter=f.dataset.tfilter;$('#teacher-filter').querySelectorAll('button').forEach(b=>{b.classList.toggle('active',b===f);b.setAttribute('aria-pressed',b===f);});paintTeachers();return;}
    const hit=e.target.closest('[data-pick]');if(hit){const id=hit.dataset.pick;if(pick.ids.includes(id)){pick.ids=pick.ids.filter(x=>x!==id);if(pick.lead===id)pick.lead=null;delete pick.subjects[id];}else pick.ids.push(id);captureTeacherChoice();paintTeachers();return;}
    const edit=e.target.closest('[data-teacher-edit]');if(edit){openTeacherSheet(edit.dataset.teacherEdit);return;}
    if(e.target.closest('[data-propose]')){openProposeSheet();return;}
    if(e.target.closest('[data-teachers-save]'))saveTeachers(e.target.closest('[data-teachers-save]'));};}
async function saveTeachers(button){$('#teachers-error').textContent='';const ids=pick.ids,payload={teacher_ids:ids,class_teacher_id:pick.lead,subjects:Object.fromEntries(Object.entries(pick.subjects).filter(([id])=>ids.includes(id)))};button.disabled=true;
  try{await api('/teachers',json(payload,'PUT'));delete teacherDraft.choice;persistTeacherDraft();await refresh();location.hash='';notice('Учителя сохранены');}catch(err){failed(err,$('#teachers-error'));button.disabled=false;}}
// One sheet for both: a chosen teacher (subject for this class, class teacher) and a teacher the class proposes.
function openTeacherSheet(id){const proposal=teacherData.proposals.find(p=>p.id===id),t=proposal||teacherData.teachers.find(x=>x.id===id);if(!t)return;sheetTarget=id;
  $('#teacher-sheet-body').innerHTML=`<div class="sheet-head"><span>${proposal?'Предложенный учитель':'Учитель в альбоме'}</span><button type="button" class="icon-btn" data-sheet-close aria-label="Закрыть">×</button></div><div class="sheet-who"><span class="sheet-face">${proposal?`<span class="tile-initials" aria-hidden="true">${esc(initialsOf(t))}</span>`:teacherPortrait(t)}</span><div><h2>${esc(t.name)}</h2><p class="muted">${proposal?'Ждёт фотографа'+(t.subject?' · '+esc(t.subject):''):esc(t.subject)}</p></div></div>${proposal?'':`<label>Предмет в вашем классе<input name="subject" maxlength="100" value="${esc(teacherSubject(t))}" placeholder="${esc(t.subject)}"></label>`}<label class="switch"><input type="checkbox" name="lead" role="switch" ${pick.lead===id?'checked':''}><span>Классный руководитель</span></label><p class="error" role="alert"></p><button class="primary" type="submit">Готово</button><button type="button" class="text-btn" data-sheet-remove>${proposal?'Убрать предложение':'Убрать из альбома'}</button>`;
  $('#teacher-sheet').showModal();}
function openProposeSheet(){sheetTarget='new';const d=teacherDraft.proposal||{};
  $('#teacher-sheet-body').innerHTML=`<div class="sheet-head"><span>Нет в списке</span><button type="button" class="icon-btn" data-sheet-close aria-label="Закрыть">×</button></div><h2>Предложить учителя</h2><p class="muted">Фотограф проверит и добавит в альбом.</p><label>Фамилия<input name="last_name" maxlength="60" autocomplete="off" required value="${esc(d.last_name)}"></label><label>Имя<input name="first_name" maxlength="60" autocomplete="off" required value="${esc(d.first_name)}"></label><label>Отчество <span class="muted">· необязательно</span><input name="patronymic" maxlength="60" autocomplete="off" value="${esc(d.patronymic)}"></label><label>Предмет<input name="subject" maxlength="100" autocomplete="off" value="${esc(d.subject)}"></label><p class="error" role="alert"></p><button class="primary" type="submit">Предложить</button>`;
  $('#teacher-sheet').showModal();$('#teacher-sheet-form').elements.last_name.focus();}
function bindTeacherSheet(){const dialog=$('#teacher-sheet'),form=$('#teacher-sheet-form');
  dialog.addEventListener('click',e=>{if(e.target===dialog||e.target.closest('[data-sheet-close]'))dialog.close();if(e.target.closest('[data-sheet-remove]'))removeFromSheet(e.target.closest('[data-sheet-remove]'));});
  form.oninput=()=>{if(sheetTarget==='new'){teacherDraft.proposal=Object.fromEntries(new FormData(form));persistTeacherDraft();}};
  form.onsubmit=async e=>{e.preventDefault();const error=form.querySelector('.error'),v=Object.fromEntries(new FormData(form));error.textContent='';
    if(sheetTarget!=='new'){if(v.subject!==undefined)pick.subjects[sheetTarget]=v.subject.trim();if(v.lead)pick.lead=sheetTarget;else if(pick.lead===sheetTarget)pick.lead=null;captureTeacherChoice();dialog.close();paintTeachers();return;}
    if(!v.last_name.trim()||!v.first_name.trim()){error.textContent='Укажите фамилию и имя учителя.';return;}
    const button=form.querySelector('[type=submit]');button.disabled=true;
    try{teacherData=await api('/teacher-proposals',json(v));delete teacherDraft.proposal;persistTeacherDraft();dialog.close();paintTeachers();notice('Фотограф проверит и добавит учителя');refresh().catch(()=>{});}catch(err){failed(err,error);button.disabled=false;}};}
async function removeFromSheet(button){const id=sheetTarget,dialog=$('#teacher-sheet');
  if(!teacherData.proposals.some(p=>p.id===id)){pick.ids=pick.ids.filter(x=>x!==id);if(pick.lead===id)pick.lead=null;delete pick.subjects[id];captureTeacherChoice();dialog.close();paintTeachers();return;}
  button.disabled=true;try{teacherData=await api('/teacher-proposals/'+encodeURIComponent(id),{method:'DELETE'});if(pick.lead===id)pick.lead=null;captureTeacherChoice();dialog.close();paintTeachers();}catch(err){failed(err,dialog.querySelector('.error'));button.disabled=false;}}

// ---------- Layout ----------
function spreadCanvas(spread,doc,variant='thumb'){const size=spread.section==='cover'?(spread.size_mm||doc.cover_size_mm):doc.spread_size_mm;const [width,height]=Array.isArray(size)&&size.length===2?size:[400,200];const layers=(spread.elements||[]).map(e=>{const raw=e.box||[0,0,0,0],stroke=e.type==='frame'?(e.strokeWidth||0):0,pad=e.type==='frame'?(e.strokeAlign==='outside'?stroke:e.strokeAlign==='center'?stroke/2:0):0,box=[raw[0]-pad,raw[1]-pad,raw[2]+2*pad,raw[3]+2*pad];const center=e.rotation_center||[raw[0]+raw[2]/2,raw[1]+raw[3]/2],shadow=e.shadow?`box-shadow:${(e.shadow.offsetX||0)/width*100}cqw ${(e.shadow.offsetY||0)/width*100}cqw ${(e.shadow.blur||0)/width*100}cqw ${esc(e.shadow.color||'#000000')}${Math.round((e.shadow.opacity??35)/100*255).toString(16).padStart(2,'0')};`:'';const style=`${shadow}opacity:${(e.opacity??100)/100};transform:rotate(${e.angle||0}deg)${e.flipX||e.flipY?` scale(${e.flipX?-1:1},${e.flipY?-1:1})`:''};transform-origin:${(center[0]-box[0])/box[2]*100}% ${(center[1]-box[1])/box[3]*100}%;border:${(e.strokeWidth||0)/width*100}cqw solid ${esc(e.stroke||'#333333')};border-radius:${(e.radius||0)/width*100}cqw;left:${box[0]/width*100}%;top:${box[1]/height*100}%;width:${box[2]/width*100}%;height:${box[3]/height*100}%`;if(e.type==='svg')return `<div class="spread-layer" style="${style};border:0"><img alt="" src="data:image/svg+xml;charset=utf-8,${encodeURIComponent(e.svg||'')}" style="width:100%;height:100%;object-fit:fill"></div>`;if(['rect','line','ellipse','frame'].includes(e.type))return `<div class="spread-layer" style="${style};background:${e.type==='frame'?'transparent':esc(e.fill||'#eee')};${e.type==='ellipse'?'border-radius:50%;':''}"></div>`;if(e.type==='photo'){const crop=e.crop,image=e.photo?`<img alt="" loading="lazy" src="${base}/layout/photos/${encodeURIComponent(e.photo)}/${variant}${e.asset_version?'?v='+encodeURIComponent(e.asset_version):''}" style="${crop&&e.width&&e.height?`width:${e.width/crop[2]*100}%;height:${e.height/crop[3]*100}%;left:${-crop[0]/crop[2]*100}%;top:${-crop[1]/crop[3]*100}%`:'width:100%;height:100%;object-fit:cover'}">`:'';return `<div class="spread-layer spread-photo" style="${style};${e.mask==='ellipse'?'border-radius:50%':''}">${image}</div>`;}return `<div class="spread-layer spread-text" style="${style};font-size:${(e.size||4)*(doc.master_template?.3528:1)/width*100}cqw;color:${esc(e.color||'#202020')};text-align:${esc(e.align||'left')};font-family:${e.font==='display'?'Georgia,serif':e.font==='times'?'Times New Roman,serif':'Arial,sans-serif'};${e.fit?'white-space:pre;':''}${e.valign==='middle'||e.valign==='bottom'?'display:flex;flex-direction:column;justify-content:'+(e.valign==='bottom'?'flex-end':'center')+';':''}"><span>${esc(e.text||'').replace(/\n/g,'<br>')}</span></div>`;}).join('');return `<div class="spread-canvas" style="aspect-ratio:${width}/${height};--ratio:${width/height}">${layers}</div>`;}
async function ensureLayout(){if(!layoutView)layoutView=await api('/layout');const variants=layoutView.variants||[];if(!variants.some(v=>v.owner===layoutOwner))layoutOwner=variants[0]?.owner??null;return layoutView;}
const currentVariant=()=>(layoutView?.variants||[]).find(v=>v.owner===layoutOwner);
const chips=()=>{const variants=layoutView.variants||[];return variants.length>1?`<div class="chips" role="tablist" aria-label="Варианты альбома">${variants.map(v=>`<button type="button" role="tab" data-owner="${esc(v.owner)}" aria-selected="${v.owner===layoutOwner}" class="${v.owner===layoutOwner?'active':''}">${esc(v.name||'Общий вариант')}</button>`).join('')}</div>`:'';};
const spreadLabel=(spread,i,n)=>`${i+1}/${n}${sections[spread.section]?' · '+sections[spread.section]:''}`;
function layoutActions(){const st=order.stage,fixes=order.corrections.length;if(st==='approval'&&!fixes)return `<div class="dock"><a class="primary" href="#approve">Всё в порядке</a><a class="text-btn" href="#fixes">Нужны правки</a></div>`;if(st==='approval')return `<div class="dock"><div class="dock-note">${icon('clock',18)}<span>Вы отправили правки: ${fixes}. Фотограф пришлёт обновлённый макет.</span></div><a class="secondary" href="#fixes">Мои правки</a></div>`;return '';}
function layoutBanner(){const st=order.stage;if(st==='updating')return '<p class="banner">Фотограф вносит правки. Ниже — предыдущая версия макета.</p>';if(['approved','print','delivery','archive'].includes(st))return `<p class="banner ok">${icon('check',16)} Макет согласован</p>`;return '';}
async function drawLayout(){screen='layout';const v=version;show(`<div class="screen">${brandBar()}<h1>Макет</h1><p class="loading">Загружаем развороты…</p></div>`);try{await ensureLayout();}catch(err){if(v!==version)return;if(err.status===401){failed(err);return;}show(`<div class="screen narrow">${backBar('#')}<h1>Макет ещё не готов</h1><p class="muted">${esc(err.message)}</p></div>`);return;}if(v!==version||screen!=='layout')return;const variant=currentVariant(),spreads=variant?.spreads||[];show(`<div class="screen with-dock">${brandBar()}<h1>Макет</h1>${layoutBanner()}${chips()}<div class="spreads">${spreads.map((s,i)=>`<button type="button" class="spread-card" data-zoom="${i}" aria-label="Разворот ${i+1} из ${spreads.length}, открыть крупно">${spreadCanvas(s,layoutView)}<span class="spread-count">${esc(spreadLabel(s,i,spreads.length))}</span><span class="spread-zoom">${icon('zoom',18)}</span></button>`).join('')||'<div class="empty">В этом варианте пока нет разворотов.</div>'}</div>${layoutActions()}</div>`);}
function drawZoom(){const spreads=currentVariant()?.spreads||[];zoomIndex=Math.max(0,Math.min(zoomIndex,spreads.length-1));const s=spreads[zoomIndex];if(!s)return;$('#zoom-stage').innerHTML=spreadCanvas(s,layoutView,'full');$('#zoom-count').textContent=`${spreadLabel(s,zoomIndex,spreads.length)}`;$('#zoom-prev').disabled=zoomIndex===0;$('#zoom-next').disabled=zoomIndex>=spreads.length-1;const fix=$('#zoom-fix');fix.hidden=order.stage!=='approval';fix.href=`#fixes/spread/${encodeURIComponent(layoutOwner??'')}/${zoomIndex}`;}
function openZoom(i){zoomIndex=i;drawZoom();$('#zoom').showModal();}

// ---------- Corrections (customer account) ----------
function fixItem(f){return `<li class="fix"><span class="fix-icon">${icon(f.kind==='name'?'text':'spread',18)}</span><div><strong>${f.kind==='name'?'Ошибка в имени':esc(f.spread_label)+(f.variant?' · '+esc(f.variant):'')}</strong><p>${f.kind==='name'?`${esc(f.old_name)} → ${esc(f.new_name)}`:''}${f.comment?`${f.kind==='name'?'<br>':''}${esc(f.comment)}`:''}</p></div><button type="button" class="icon-btn" data-withdraw="${esc(f.id)}" aria-label="Отозвать правку">${icon('trash',18)}</button></li>`;}
function drawFixes(){screen='fixes';const list=order.corrections,editable=order.stage==='approval';show(`<div class="screen narrow">${backBar('#layout')}<h1>Внесите правки</h1>${editable?`<div class="cards"><div class="card plain"><div class="card-body"><h2>Ошибка в имени</h2><p>Чтобы исправить ошибку, выберите нужного человека и введите новые данные.</p></div><a class="dark-btn" href="#fixes/name">Выбрать</a></div><div class="card plain"><div class="card-body"><h2>Другая ошибка</h2><p>Выберите разворот и опишите проблему.</p></div><a class="dark-btn" href="#fixes/spread">Выбрать</a></div></div>`:'<p class="banner">Сейчас макет не на согласовании, новые правки отправить нельзя.</p>'}${list.length?`<p class="section-label">Отправлено фотографу · ${list.length}</p><ul class="fixes">${list.map(fixItem).join('')}</ul><p class="muted small">Фотограф исправит макет и пришлёт новую версию. Пока правки не учтены, согласовать макет нельзя. Отозванная правка не попадёт к фотографу.</p>`:''}</div>`);}
function drawNameList(){screen='fix-name';show(`<div class="screen narrow">${backBar('#fixes')}<h1>Ошибка в имени</h1><p class="muted lead">Выберите человека, в имени которого ошибка.</p><input type="search" id="fix-search" class="search" placeholder="Найти по имени" aria-label="Найти по имени"><ul class="people-list" id="fix-people"></ul></div>`);const fill=()=>{const q=$('#fix-search').value.toLowerCase();$('#fix-people').innerHTML=order.persons.filter(p=>personName(p).toLowerCase().includes(q)).map(p=>`<li><a href="#fixes/name/${encodeURIComponent(p.id)}">${p.photo_id?`<img src="${src(p.photo_id)}" alt="" loading="lazy">`:`<span class="avatar">${icon('user',18)}</span>`}<span>${esc(personName(p))}</span>${icon('back',18).replace('m15 18-6-6 6-6','m9 18 6-6-6-6')}</a></li>`).join('')||'<li class="muted">Никого не найдено</li>';};$('#fix-search').oninput=fill;fill();}
function drawNameForm(id){const p=order.persons.find(x=>x.id===id);if(!p){location.hash='fixes/name';return;}screen='fix-name-form';const [first,...rest]=(p.first_name?[p.first_name,p.last_name]:(p.name||'').split(' '));show(`<div class="screen narrow">${backBar('#fixes/name')}<h1>Новые данные</h1><div class="person-row">${p.photo_id?`<img src="${src(p.photo_id)}" alt="">`:''}<div><small class="muted">Сейчас в макете</small><strong>${esc(personName(p))}</strong></div></div><form id="name-fix" class="form"><label>Имя<input name="first_name" maxlength="50" required value="${esc(first||'')}" autocomplete="off"></label><label>Фамилия<input name="last_name" maxlength="50" required value="${esc(rest.join(' '))}" autocomplete="off"></label><label>Комментарий <span class="muted">· необязательно</span><textarea name="comment" rows="3" maxlength="1000" placeholder="Например: ударение, отчество учителя"></textarea></label><p class="error" id="fix-error" role="alert"></p><button class="primary" type="submit">Отправить правку</button></form></div>`);$('#name-fix').onsubmit=async e=>{e.preventDefault();const button=e.target.querySelector('[type=submit]');button.disabled=true;$('#fix-error').textContent='';try{const f=new FormData(e.target);await api('/corrections/name',json({person_id:p.id,first_name:String(f.get('first_name')).trim(),last_name:String(f.get('last_name')).trim(),comment:String(f.get('comment')).trim()}));await refresh();location.hash='fixes';notice('Правка отправлена фотографу');}catch(err){failed(err,$('#fix-error'));button.disabled=false;}};}
async function drawSpreadPicker(){screen='fix-spread';const v=version;show(`<div class="screen">${backBar('#fixes')}<h1>Другая ошибка</h1><p class="loading">Загружаем развороты…</p></div>`);try{await ensureLayout();}catch(err){failed(err);return;}if(v!==version||screen!=='fix-spread')return;const spreads=currentVariant()?.spreads||[];show(`<div class="screen">${backBar('#fixes')}<h1>Другая ошибка</h1><p class="muted lead">Выберите разворот, на котором нужна правка.</p>${chips()}<div class="spreads picker">${spreads.map((s,i)=>`<a class="spread-card" href="#fixes/spread/${encodeURIComponent(layoutOwner??'')}/${i}" aria-label="Разворот ${i+1}">${spreadCanvas(s,layoutView)}<span class="spread-count">${esc(spreadLabel(s,i,spreads.length))}</span></a>`).join('')}</div></div>`);}
async function drawSpreadForm(owner,index){screen='fix-spread-form';const v=version;try{await ensureLayout();}catch(err){failed(err);return;}if(v!==version)return;if(layoutView.variants.some(x=>x.owner===owner))layoutOwner=owner;const spreads=currentVariant()?.spreads||[],i=Number(index),s=spreads[i];if(!s){location.hash='fixes/spread';return;}show(`<div class="screen narrow">${backBar('#fixes/spread')}<h1>Опишите проблему</h1><div class="spread-card static">${spreadCanvas(s,layoutView)}<span class="spread-count">${esc(spreadLabel(s,i,spreads.length))}</span></div><form id="spread-fix" class="form"><label>Что нужно исправить?<textarea name="comment" rows="5" maxlength="1000" required placeholder="Например: на фото слева у Маши закрыты глаза — замените на другой кадр"></textarea></label><p class="error" id="fix-error" role="alert"></p><button class="primary" type="submit">Отправить правку</button></form></div>`);$('#spread-fix').onsubmit=async e=>{e.preventDefault();const button=e.target.querySelector('[type=submit]');button.disabled=true;$('#fix-error').textContent='';try{await api('/corrections/spread',json({variant:layoutOwner,index:i,comment:String(new FormData(e.target).get('comment')).trim()}));await refresh();location.hash='fixes';notice('Правка отправлена фотографу');}catch(err){failed(err,$('#fix-error'));button.disabled=false;}};}

// ---------- Approval: copies and delivery, then the customer's sign-off ----------
function allowedModes(summary){const raw=summary.delivery_modes;if(raw==='personal'||raw==='shipping')return [raw];return ['personal','shipping'];}
function summaryPayload(form){const mode=form.elements.mode.value;const shipping=mode!=='personal';return {allocations:[...form.querySelectorAll('[data-alloc]')].map(el=>({key:el.dataset.alloc,paid:Number(el.value)||0,gift:Number(el.dataset.gift)||0})),paid_total:Number(form.elements.paid_total.value)||0,delivery:{mode,carrier:shipping?form.elements.carrier.value.trim():'',address:shipping?form.elements.address.value.trim():'',recipient:form.elements.recipient.value.trim(),phone:form.elements.phone.value.trim()}};}
function syncSummary(form){const paidTotal=Number(form.elements.paid_total.value)||0;const paid=[...form.querySelectorAll('[data-alloc]')].reduce((s,el)=>s+(Number(el.value)||0),0);const left=paidTotal-paid;const hint=$('#remainder');hint.textContent=left===0?'Все платные экземпляры распределены.':left>0?`Не распределено: ${left}. Распределите остаток или измените тираж.`:`Распределено больше тиража на ${-left}.`;hint.classList.toggle('warn',left!==0);const fit=$('#fit-total');fit.hidden=left===0;fit.textContent=`Сделать тираж ${paid} ${paid%10===1&&paid%100!==11?'альбом':paid%10>=2&&paid%10<=4&&(paid%100<10||paid%100>=20)?'альбома':'альбомов'}`;fit.onclick=()=>{form.elements.paid_total.value=paid;syncSummary(form);};$('#grand-total').textContent=String(paidTotal+(Number(form.dataset.gift)||0));$('#ship-extra').hidden=form.elements.mode.value==='personal';form.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===form.elements.mode.value));}
async function drawApprove(message=''){screen='approve';const v=version;if(order.stage!=='approval'||order.corrections.length){location.hash='layout';return;}show(`<div class="screen narrow">${backBar('#layout')}<h1>Согласование</h1><p class="loading">Загружаем заказ…</p></div>`);let summary;try{summary=await api('/summary');}catch(err){failed(err);return;}if(v!==version)return;const alloc=summary.allocations||[];const paidTotal=alloc.reduce((s,a)=>s+(Number(a.paid)||0),0)+(Number(summary.remainder)||0);const modes=allowedModes(summary);const d=summary.delivery||{};const mode=modes.includes(d.mode)?d.mode:modes[0];const gift=Number(summary.gift)||0;
  show(`<div class="screen narrow">${backBar('#layout')}<h1>Согласование</h1><p class="muted lead">Проверьте тираж и получение. После согласования макет уйдёт в печать — изменить его будет нельзя.</p><form id="summary-form" class="form" data-gift="${gift}"><section class="panel"><h2>Тираж</h2><label class="row">Платных альбомов<input name="paid_total" type="number" inputmode="numeric" min="0" value="${paidTotal}"></label>${alloc.length?`<details class="allocs"${summary.remainder?' open':''}><summary>По участникам</summary>${alloc.map(a=>`<label class="row"><span>${esc(a.label||a.key)}${a.gift?` <small class="muted">+${esc(a.gift)} в подарок</small>`:''}</span><input data-alloc="${esc(a.key)}" data-gift="${Number(a.gift)||0}" type="number" inputmode="numeric" min="0" value="${Number(a.paid)||0}" aria-label="Платных: ${esc(a.label||a.key)}"></label>`).join('')}</details>`:''}<p id="remainder" class="muted small"></p><button type="button" class="secondary fit" id="fit-total" hidden></button><p class="total">${gift?`В подарок: ${gift} · `:''}Всего: <strong id="grand-total"></strong></p></section><section class="panel"><h2>Получение</h2><input type="hidden" name="mode" value="${mode}">${modes.length>1?`<div class="segmented wide">${modes.map(m=>`<button type="button" data-mode="${m}">${m==='personal'?'Лично':'Доставка'}</button>`).join('')}</div>`:`<p class="muted">${mode==='personal'?'Альбомы передаст фотограф лично.':'Альбомы отправят доставкой.'}</p>`}<div id="ship-extra"><label>Служба доставки<input name="carrier" value="${esc(d.carrier||'')}" maxlength="120" placeholder="СДЭК, Почта России…"></label><label>Адрес или пункт выдачи<textarea name="address" rows="2" maxlength="300">${esc(d.address||'')}</textarea></label></div><label>Получатель<input name="recipient" value="${esc(d.recipient||'')}" maxlength="120" autocomplete="name"></label><label>Телефон<input name="phone" type="tel" value="${esc(d.phone||'')}" maxlength="40" autocomplete="tel"></label></section><p id="summary-error" class="error" role="alert">${esc(message)}</p><button class="primary" type="submit">Согласовать макет</button></form></div>`);
  const form=$('#summary-form');const refreshForm=()=>syncSummary(form);form.oninput=refreshForm;form.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{form.elements.mode.value=b.dataset.mode;refreshForm();});refreshForm();
  form.onsubmit=async e=>{e.preventDefault();const button=e.target.querySelector('[type=submit]');button.disabled=true;$('#summary-error').textContent='';try{await api('/summary',json(summaryPayload(form),'PUT'));const fresh=await api('/summary');await api('/approve',json({hash:fresh.hash}));await refresh();show(`<div class="screen narrow">${brandBar()}<div class="success"><span class="success-icon">${icon('check',34)}</span><h1>Макет согласован</h1><p class="muted">Спасибо! Фотограф отправит альбомы в печать. Статус заказа всегда можно посмотреть в кабинете.</p><a class="primary" href="#">К статусу заказа</a></div></div>`);screen='approved';}catch(err){failed(err,$('#summary-error'));button.disabled=false;}};}

// ---------- Account switch: parents (entry code) ↔ customer (manage code) ----------
function askManager(){try{sessionStorage.setItem('album-next',location.hash||'#');}catch{}location.hash='account';}
function drawAccount(){screen='account';if(order.manager){show(`<div class="screen narrow">${backBar('#')}<h1>Аккаунт<br>заказчика</h1><p>Вы вошли как заказчик. Можно вносить правки в макет и согласовать его для печати.</p><div class="account-badge">${icon('key',20)}<span>Код заказчика принят</span></div><button type="button" class="secondary wide" id="leave">${icon('logout',18)} Выйти из аккаунта заказчика</button></div>`);$('#leave').onclick=async()=>{try{await api('/manage/logout',json({}));await refresh();location.hash='';notice('Вы вернулись в аккаунт для родителей');}catch(err){failed(err);}};return;}
  show(`<div class="screen narrow">${backBar('#')}<form id="manage-form" class="code-screen"><h1>Смена<br>аккаунта</h1><p>Сейчас вы в аккаунте для родителей.</p><p>Чтобы изменить данные для вёрстки и отправить макет в печать, войдите в аккаунт заказчика.</p><p>Для этого нужно ввести код, который выдал фотограф.</p><div class="code-field"><strong>Введите код</strong>${pinBoxes('manage-pin')}<p id="manage-error" class="error" role="alert"></p></div><button class="primary" type="submit">Войти</button></form></div>`);const pin=wirePin($('#manage-pin'),()=>$('#manage-form').requestSubmit());$('#manage-form').onsubmit=async e=>{e.preventDefault();if(pin.value().length<4){$('#manage-error').textContent='Введите четыре цифры';return;}const button=e.target.querySelector('[type=submit]');button.disabled=true;$('#manage-error').textContent='';try{await api('/manage',json({pin:pin.value()}));await refresh();let next='#';try{next=sessionStorage.getItem('album-next')||'#';sessionStorage.removeItem('album-next');}catch{}location.hash=next==='#account'?'':next;notice('Вы вошли как заказчик');}catch(err){$('#manage-error').textContent=err.message;pin.clear();button.disabled=false;}};}

// ---------- Routing ----------
const needsManager=new Set(['fixes','approve']);
function route(){if(!order)return;if($('#selection').open)$('#selection').close();if($('#teacher-sheet').open)$('#teacher-sheet').close();if($('#zoom').open)$('#zoom').close();version++;const [page='',...rest]=location.hash.slice(1).split('/').map(decodeURIComponent);const previous=screen;
  if(needsManager.has(page)&&!order.manager){askManager();return;}
  if(page==='people')drawPeople();else if(page==='person')drawPerson(rest[0]);else if(page==='layout')drawLayout();
  else if(page==='fixes'&&rest[0]==='name')rest[1]?drawNameForm(rest[1]):drawNameList();
  else if(page==='fixes'&&rest[0]==='spread')rest.length>=3?drawSpreadForm(rest[1],rest[2]):drawSpreadPicker();
  else if(page==='fixes')drawFixes();else if(page==='approve')drawApprove();else if(page==='teachers')drawTeachers();else if(page==='account')drawAccount();else drawHome();
  if(previous!==screen)window.scrollTo(0,0);}
async function refresh(){order=await api();layoutView=null;return order;}
async function load(){const v=++version;try{const fresh=await api();if(v!==version)return;order=fresh;layoutView=null;applyQuoteLimit();route();}catch(e){if(e.status===401){showEntry();return;}show(`<div class="screen narrow"><h1>Не удалось открыть заказ</h1><p class="muted">${esc(e.message)}</p><button class="primary" id="retry">Повторить</button></div>`);$('#retry').onclick=load;}}

document.addEventListener('click',e=>{const f=e.target.closest('[data-filter]');if(f){filter=f.dataset.filter;drawPeople();return;}
  const chip=e.target.closest('[data-owner]');if(chip){layoutOwner=chip.dataset.owner;route();return;}
  const z=e.target.closest('[data-zoom]');if(z){openZoom(Number(z.dataset.zoom));return;}
  const w=e.target.closest('[data-withdraw]');if(w){if(!confirm('Отозвать эту правку?'))return;w.disabled=true;api('/corrections/'+encodeURIComponent(w.dataset.withdraw),{method:'DELETE'}).then(refresh).then(()=>{route();notice('Правка отозвана');}).catch(err=>{w.disabled=false;failed(err);});return;}
  const b=e.target.closest('[data-photo]');if(!b)return;const photo=order.photos.find(p=>p.id===b.dataset.photo),p=order.persons.find(x=>x.id===photo?.person_id);if(!p||p.photo_locked)return;openForm(p,photo.id);});
$('#close').onclick=()=>$('#selection').close();$('#selection-form').elements.quote.oninput=()=>applyQuoteLimit();
$('#selection-form').onsubmit=async e=>{e.preventDefault();const button=e.target.querySelector('[type=submit]');button.disabled=true;$('#error').textContent='';const id=encodeURIComponent(chosen.person_id);try{await api('/persons/'+id,json({...Object.fromEntries(new FormData(e.target)),photo_id:chosen.photo_id},'PUT'));await api('/persons/'+id+'/submit',json({}));$('#selection').close();await refresh();location.hash='people';route();notice('Анкета отправлена');}catch(err){$('#error').textContent=err.message;button.disabled=false;}};
$('#zoom-close').onclick=()=>$('#zoom').close();$('#zoom-prev').onclick=()=>{zoomIndex--;drawZoom();};$('#zoom-next').onclick=()=>{zoomIndex++;drawZoom();};
$('#zoom-fix').onclick=()=>$('#zoom').close();
$('#zoom').addEventListener('keydown',e=>{if(e.key==='ArrowLeft'&&zoomIndex>0){zoomIndex--;drawZoom();}if(e.key==='ArrowRight'){zoomIndex++;drawZoom();}});
{let startX=null;const stage=$('#zoom-stage');stage.addEventListener('touchstart',e=>{startX=e.touches.length===1?e.touches[0].clientX:null;},{passive:true});stage.addEventListener('touchend',e=>{if(startX===null)return;const dx=e.changedTouches[0].clientX-startX;startX=null;if(Math.abs(dx)<50)return;zoomIndex+=dx<0?1:-1;drawZoom();});}
window.addEventListener('hashchange',route);bindTeacherSheet();
document.addEventListener('visibilitychange',async()=>{if(document.hidden||!order||!['home','layout'].includes(screen))return;try{const before=JSON.stringify([order.stage,order.corrections.length,order.completed]);await refresh();if(before!==JSON.stringify([order.stage,order.corrections.length,order.completed]))route();}catch{}});
load();
