const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const token=encodeURIComponent(location.pathname.split('/')[2]);
const base='/client-api/'+token;
let order,filter='all',query='',chosen=null,version=0;
async function api(path='',options={}){const r=await fetch(base+path,options);const data=await r.json();if(!r.ok)throw Error(typeof data.detail==='string'?data.detail:'Проверьте заполнение полей');return data;}
const src=(id,variant='thumb')=>`${base}/photos/${encodeURIComponent(id)}/${variant}`;
const name=(p,i)=>p.first_name?`${p.first_name} ${p.last_name}`:p.name||`Персона ${String(i+1).padStart(2,'0')}`;
function cards(){const people=order.persons.filter((p,i)=>(filter!=='todo'||!p.photo_id)&&name(p,i).toLowerCase().includes(query.toLowerCase()));$('#people').innerHTML=people.map(p=>{const i=order.persons.indexOf(p),photos=order.photos.filter(f=>f.person_id===p.id),cover=p.photo_id||photos[0]?.id;return `<a class="tile" href="#person/${encodeURIComponent(p.id)}" aria-label="${esc(name(p,i))}">${cover?`<img src="${src(cover)}" alt="${esc(name(p,i))}" loading="lazy">`:''}${p.photo_id?'<span class="badge">✓ Выбрано</span>':''}<span class="caption"><strong>${esc(name(p,i))}</strong><small>${photos.length?`${photos.length} фото · ${p.photo_id?'Изменить выбор':'Выбрать портрет'}`:'Ожидаем фотографии'}</small></span></a>`;}).join('')||'<div class="empty">'+(order.persons.length?'Никого не найдено. Попробуйте изменить поиск или фильтр.':'Фотограф готовит ваши фотографии. Персоны появятся здесь после обработки.')+'</div>';}
function render(){const id=decodeURIComponent(location.hash.split('/')[1]||'');const p=order.persons.find(p=>p.id===id);if(id&&!p){location.hash='';return;}if(p){const photos=order.photos.filter(f=>f.person_id===p.id);$('#main').innerHTML=`<a class="back" href="#" aria-label="Назад к персонам">←</a><div class="eyebrow">${esc(order.school)} · ${esc(order.class_name)}</div><div class="intro"><div><h1>Выберите портрет</h1><p class="muted">${esc(name(p,order.persons.indexOf(p)))} · Нажмите на фото, чтобы добавить подпись.</p></div></div><div class="grid gallery">${photos.map((f,i)=>`<button class="tile" data-photo="${esc(f.id)}" aria-label="Открыть фотографию ${i+1}"><img src="${src(f.id)}" alt="Портрет ${i+1}" loading="lazy">${p.photo_id===f.id?'<span class="badge">✓ Выбрано</span>':''}</button>`).join('')||'<div class="empty">Фотографии ещё готовятся.</div>'}</div>`;return;}
$('#main').innerHTML=`<div class="eyebrow">Ваш выпускной альбом · ${esc(order.school)} · ${esc(order.class_name)}</div><div class="intro"><div><h1>Сохраните себя<br>в этой истории.</h1><p class="muted">Выберите портрет и добавьте несколько слов о себе.</p></div><div class="progress"><strong>${order.completed}</strong> / ${order.persons.length}<div class="muted">участников готовы</div><progress max="${order.persons.length||1}" value="${order.completed}" aria-label="Участников готовы"></progress></div></div><div class="layout"><aside class="steps" aria-label="Статус заказа"><a href="#people" class="step active"><small>01 / СТАТУС ЗАКАЗА</small><h2>Выбор<br>портретов</h2><p>${order.persons.length&&order.completed===order.persons.length?'Все портреты выбраны. Фотограф может приступить к макету.':'Когда все участники выберут фото, фотограф сможет приступить к макету.'}</p><div class="foot"><span>${order.completed} / ${order.persons.length}</span><span class="arrow">↗</span></div></a><div class="step"><small>02 / СЛЕДУЮЩИЙ ЭТАП</small><h2>Согласование макета</h2><p>Ожидаем макет от фотографа.</p></div><div class="step"><small>03 / ВПЕРЕДИ</small><h2>Доставка</h2><p>После согласования и печати альбомов.</p></div></aside><section><h2 style="margin-top:0">Выберите себя</h2><div class="toolbar"><div class="tabs"><button data-filter="all" class="${filter==='all'?'active':''}" aria-pressed="${filter==='all'}">Все персоны</button><button data-filter="todo" class="${filter==='todo'?'active':''}" aria-pressed="${filter==='todo'}">Без портрета</button></div><input type="search" id="search" placeholder="Найти по имени" aria-label="Найти по имени" value="${esc(query)}"></div><div class="grid" id="people"></div></section></div>`;cards();$('#search').oninput=e=>{query=e.target.value;cards();};}
async function load(){const v=++version;try{const fresh=await api();if(v!==version)return;order=fresh;render();}catch(e){$('#main').innerHTML=`<h1>Не удалось открыть заказ</h1><p class="muted">${esc(e.message)}</p><button class="primary" id="retry">Повторить</button>`;$('#retry').onclick=load;}}
document.addEventListener('click',e=>{const f=e.target.closest('[data-filter]');if(f){filter=f.dataset.filter;render();}const b=e.target.closest('[data-photo]');if(!b)return;const photo=order.photos.find(p=>p.id===b.dataset.photo),p=order.persons.find(p=>p.id===photo.person_id);chosen={photo_id:photo.id,person_id:p.id};const form=$('#selection-form');form.reset();form.elements.first_name.value=p.first_name||'';form.elements.last_name.value=p.last_name||'';form.elements.quote.value=p.quote||'';$('#characters').textContent=`${form.elements.quote.value.length} / 300`;$('#error').textContent='';$('#preview').src=src(photo.id,'full');$('#selection').showModal();});
$('#close').onclick=()=>$('#selection').close();$('#selection-form').elements.quote.oninput=e=>$('#characters').textContent=`${e.target.value.length} / 300`;
$('#selection-form').onsubmit=async e=>{e.preventDefault();const button=e.target.querySelector('[type=submit]');button.disabled=true;$('#error').textContent='';try{await api('/persons/'+encodeURIComponent(chosen.person_id),{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({...Object.fromEntries(new FormData(e.target)),photo_id:chosen.photo_id})});$('#selection').close();location.hash='';await load();$('#notice').textContent='Портрет и подпись сохранены';$('#notice').classList.add('show');setTimeout(()=>$('#notice').classList.remove('show'),3500);}catch(err){$('#error').textContent=err.message;}finally{button.disabled=false;}};
window.addEventListener('hashchange',()=>{if($('#selection').open)$('#selection').close();if(order)render();});load();
