/* Review of an analysed general shoot inside the V2 order page. Uses the V2 globals (state, api, json, esc, toast, count). */
window.GeneralReview=(()=>{
  const FILTERS=[['all','Все'],['best','Лучшие'],['series','Серии'],['defects','Брак'],['people','Люди']];
  let cache={key:'',data:null,loading:null},faceDialog=null;
  const shoot=()=>state.order?.shoots?.find(s=>s.id===state.shootId);
  const signature=()=>state.order.id+'|'+state.shootId+'|'+state.order.photos.filter(p=>p.shoot_id===state.shootId).map(p=>p.id+':'+p.status).join(',')+'|'+state.order.persons.map(p=>p.id+':'+p.name).join(',');
  async function load(force=false){const key=signature();if(!force&&cache.key===key&&cache.data)return cache.data;const orderId=state.order.id,shootId=state.shootId;const promise=api(`/orders/${orderId}/shoots/${shootId}/general`);cache.loading=promise;const data=await promise;if(cache.loading!==promise)return cache.data;cache={key,data,loading:null};return data;}
  function personLabel(id){const index=state.order.persons.findIndex(p=>p.id===id);return index<0?'Неизвестный':personName(state.order.persons[index],index);}
  function filters(){const photos=state.order.photos.filter(p=>p.shoot_id===state.shootId),pending=photos.filter(p=>['pending','processing'].includes(p.status)).length,errors=photos.filter(p=>p.status==='error').length;
    return [...FILTERS,...(pending?[['pending','В обработке']]:[]),...(errors?[['error','Ошибки']]:[])];}
  /* Section below the upload panel: title, filters, actions and results. */
  function section(s){const photos=state.order.photos.filter(p=>p.shoot_id===s.id),pending=photos.filter(p=>['pending','processing'].includes(p.status)).length;if(!filters().some(([k])=>k===state.photoFilter))state.photoFilter='all';
    return `<div class="section-head"><h2>${esc(s.title)} <span class="muted">${photos.length}</span></h2><div class="filter-tabs photo-filters">${filters().map(([key,label])=>`<button data-photo-filter="${key}" class="${state.photoFilter===key?'active':''}" aria-pressed="${state.photoFilter===key}">${label}</button>`).join('')}</div></div>
    <div class="general-status" id="general-status">${pending?`Анализируем снимки: осталось ${pending}. Лица, люди, крупность и брак появятся по мере обработки.`:'Снимки проанализированы на этом компьютере: люди, крупность плана, серии похожих кадров и брак.'} <button class="link-button" data-general="reanalyze">Проанализировать заново</button></div>
    ${state.photoFilter==='people'?'':gridTools()}
    <div id="photo-results"></div>`;}
  function visible(data){const byId=Object.fromEntries(data.photos.map(p=>[p.id,p]));return state.order.photos.filter(p=>p.shoot_id===state.shootId).map(p=>({...p,a:byId[p.id]})).filter(({status,a})=>{const f=state.photoFilter;if(f==='pending')return ['pending','processing'].includes(status);if(f==='error')return status==='error';if(f==='best')return a?.analyzed&&!a.alternate&&!a.flags.excluded&&a.defect!=='reject';if(f==='defects')return a?.defect==='reject'||a?.defects.length||a?.flags.excluded;if(f==='series')return a?.series;return true;});}
  function tags(a,labels){if(!a?.analyzed)return '';const items=[];if(a.flags.excluded)items.push(['Не используется','off']);if(a.defect==='reject')items.push([a.defects.map(d=>labels.defect[d]).filter(Boolean).join(', ')||'Брак','bad']);else if(a.defects.length)items.push([a.defects.map(d=>labels.defect[d]).join(', '),'warn']);if(a.flags.must_use)items.push(['Обязательно','key']);if(a.flags.hero)items.push(['Главное','key']);if(a.alternate)items.push(['Дубль','off']);
    items.push([labels.bucket[a.bucket]+(a.count>2?' · '+a.count:''),''],[labels.scale[a.scale],'']);if(a.subjects.length)items.push([count(a.subjects.length,'ученик','ученика','учеников'),'people']);return `<div class="tile-tags">${items.map(([t,k])=>`<span class="${k}">${esc(t)}</span>`).join('')}</div>`;}
  function tile(p,labels,extra=''){const a=p.a;return `<label class="photo-tile general-tile ${a?.flags.excluded||a?.alternate?'muted-tile':''}"><img src="/media/${p.id}/thumb" alt="${esc(p.filename)}" loading="lazy" decoding="async"><input type="checkbox" data-photo="${p.id}" aria-label="Выбрать ${esc(p.filename)}" ${state.selected.has(p.id)?'checked':''}><p title="${esc(p.filename)}">${esc(p.filename)}</p>${['pending','processing'].includes(p.status)?'<small>Анализ…</small>':p.status==='error'?`<small>${esc(p.error||'Ошибка анализа')}</small>`:tags(a,labels)}${a?.analyzed?`<button type="button" class="tile-open" data-general="open" data-id="${p.id}">Подробнее</button>`:''}${extra}</label>`;}
  async function render(){const el=$('#photo-results');if(!el)return;if(!cache.data)el.innerHTML='<p class="muted small">Загружаем анализ…</p>';let data;try{data=await load();}catch(e){el.innerHTML=`<div class="warning">${esc(e.message)}</div>`;return;}if(!$('#photo-results'))return;
    if(state.photoFilter==='people'){el.innerHTML=people(data);return;}
    const photos=visible(data);if(!photos.length){el.innerHTML=`<div class="empty-state"><h3>${state.photoFilter==='defects'?'Брака не найдено':state.photoFilter==='series'?'Похожих серий нет':'Здесь нет фотографий'}</h3><p>${state.photoFilter==='all'?'Добавьте фотографии с помощью кнопки или перетащите их в область загрузки.':'Выберите другой фильтр.'}</p></div>`;return;}
    if(state.photoFilter==='series'){const groups={};photos.forEach(p=>(groups[p.a.series]??=[]).push(p));el.innerHTML=Object.values(groups).map(items=>`<section class="series-group"><h3>Серия · ${count(items.length,'кадр','кадра','кадров')}</h3><div class="photo-grid">${items.map(p=>tile(p,data.labels,p.a.alternate?`<button type="button" class="tile-best" data-general="best" data-id="${p.id}">Сделать лучшим</button>`:'<span class="tile-best current">Лучший кадр</span>')).join('')}</div></section>`).join('');return;}
    el.innerHTML=`${photos.some(p=>p.status==='error')?'<div class="warning">Не удалось проанализировать часть снимков. <button class="link-button" data-action="retry">Повторить обработку</button></div>':''}<div class="photo-grid">${photos.map(p=>tile(p,data.labels)).join('')}</div>`;}
  /* Person picker: a button showing the chosen person, opening a popover grid of portraits. */
  const CHEVRON='<svg class="pick-chevron" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="m6 9 6 6 6-6"/></svg>';
  let pick={el:null,ids:[],selected:'',taken:[],trigger:null,query:'',closedAt:0};
  const portraitOf=id=>cache.data?.persons.find(p=>p.id===id)?.portrait;
  const avatar=(id,cls='')=>{const src=portraitOf(id);return src?`<img class="${cls}" src="/media/${src}/thumb" alt="" loading="lazy" decoding="async">`:`<span class="avatar-empty ${cls}"></span>`;};
  function picker(ids,selected='',label='Кто это?',taken=[]){const i=state.order.persons.findIndex(p=>p.id===selected);
    const inner=i>=0?`${avatar(selected)}<span>${esc(personName(state.order.persons[i],i))}</span>`:selected==='stranger'?'<span class="avatar-empty"></span><span>Не из класса</span>':'<span class="avatar-empty ask">?</span><span class="muted">Кто это?</span>';
    return `<button type="button" class="person-pick" data-general="pick" data-faces="${ids.join(',')}" data-selected="${esc(selected)}" data-taken="${taken.join(',')}" aria-haspopup="dialog" aria-label="${esc(label)}">${inner}${CHEVRON}</button>`;}
  function pickerGrid(){const q=pick.query.trim().toLowerCase(),list=state.order.persons.map((p,i)=>({p,name:personName(p,i)})).filter(x=>!q||x.name.toLowerCase().includes(q));
    return list.length?list.map(({p,name})=>{const current=p.id===pick.selected,taken=!current&&pick.taken.includes(p.id);return `<button type="button" class="pick-person ${current?'current':''} ${taken?'taken':''}" data-pick="person:${p.id}" title="${esc(name)}${taken?' · уже отмечен на этом фото':''}">${avatar(p.id)}<span>${esc(name)}</span>${taken?'<small>уже на фото</small>':''}</button>`;}).join(''):`<p class="muted small pick-empty">${state.order.persons.length?'Никого не нашли':'Персоны появятся после портретной съёмки'}</p>`;}
  function positionPicker(){const r=pick.trigger.getBoundingClientRect(),el=pick.el,below=innerHeight-r.bottom-18,above=r.top-18,down=below>=Math.min(460,above)||below>=above;
    el.style.maxHeight=Math.min(460,down?below:above)+'px';const w=el.offsetWidth,h=el.offsetHeight;
    el.style.left=Math.max(12,Math.min(r.right-w,innerWidth-w-12))+'px';el.style.top=(down?r.bottom+6:r.top-h-6)+'px';}
  function openPicker(trigger){if(pick.trigger===trigger&&Date.now()-pick.closedAt<300)return;
    if(!pick.el){const el=document.createElement('div');el.id='face-person-picker';el.className='person-picker';el.setAttribute('popover','');el.setAttribute('role','dialog');el.setAttribute('aria-label','Выбрать персону');document.body.append(el);pick.el=el;
      const follow=()=>{if(el.matches(':popover-open'))positionPicker();};addEventListener('resize',follow);document.addEventListener('scroll',e=>{if(!el.contains(e.target))follow();},true);
      el.addEventListener('toggle',e=>{if(e.newState==='closed'){pick.closedAt=Date.now();pick.trigger?.setAttribute('aria-expanded','false');if(pick.trigger?.isConnected)pick.trigger.focus();}});
      el.addEventListener('input',e=>{if(!e.target.matches('.pick-search'))return;pick.query=e.target.value;el.querySelector('.pick-grid').innerHTML=pickerGrid();positionPicker();});
      el.addEventListener('keydown',e=>{if(e.key==='Enter'&&e.target.matches('.pick-search')){e.preventDefault();el.querySelector('.pick-person')?.click();}});
      el.addEventListener('click',async e=>{const b=e.target.closest('[data-pick]');if(!b)return;const ids=pick.ids;el.hidePopover();try{await faces(ids,b.dataset.pick);}catch(error){toast(error.message);}});}
    const host=trigger.closest('dialog')||document.body;if(pick.el.parentElement!==host){if(pick.el.matches(':popover-open'))pick.el.hidePopover();host.append(pick.el);}
    Object.assign(pick,{ids:trigger.dataset.faces.split(','),selected:trigger.dataset.selected||'',taken:(trigger.dataset.taken||'').split(',').filter(Boolean),trigger,query:''});
    pick.el.innerHTML=`<input class="pick-search" type="search" placeholder="Найти ученика" aria-label="Найти ученика" autocomplete="off"><div class="pick-grid">${pickerGrid()}</div><div class="pick-extra"><button type="button" data-pick="stranger" class="${pick.selected==='stranger'?'current':''}">Не из класса</button><button type="button" data-pick="not_face">Это не лицо</button></div>`;
    pick.el.showPopover();trigger.setAttribute('aria-expanded','true');positionPicker();pick.el.querySelector('.pick-grid .current')?.scrollIntoView({block:'nearest'});pick.el.querySelector('.pick-search').focus({preventScroll:true});}
  function people(data){const persons=[...data.persons].sort((a,b)=>a.count-b.count),missing=persons.filter(p=>!p.count);
    const coverage=persons.length?`<section class="panel general-people"><h3>Ученики на общих фото</h3><p class="muted small">${missing.length?`${count(missing.length,'ученик не найден','ученика не найдены','учеников не найдены')} ни на одном годном снимке. Проверьте неопознанных людей ниже.`:'Каждый ученик есть хотя бы на одном годном снимке.'}</p><div class="coverage-list">${persons.map(p=>`<div class="coverage-item ${p.count?'':'missing'}">${p.portrait?`<img src="/media/${p.portrait}/thumb" alt="">`:'<span class="avatar-empty"></span>'}<span>${esc(personLabel(p.id))}</span><b>${p.count}</b></div>`).join('')}</div></section>`:'<div class="warning">Персоны появляются из портретной съёмки. Загрузите портреты, и лица на общих фото будут связаны с учениками.</div>';
    const uncertain=data.uncertain.length?`<section class="panel general-people"><h3>Проверить совпадения <span class="muted">${data.uncertain.length}</span></h3><div class="face-grid">${data.uncertain.map(f=>{const person=data.persons.find(p=>p.id===f.candidate);return `<div class="face-card"><div class="face-pair"><img src="/media/face/${f.id}/crop" alt="Лицо на общем фото">${person?.portrait?`<img src="/media/${person.portrait}/thumb" alt="Портрет">`:''}</div><p>Это ${esc(personLabel(f.candidate))}?</p><div class="face-actions"><button class="secondary" data-general="face" data-faces="${f.id}" data-value="person:${f.candidate}">Да</button>${picker([f.id],'','Выбрать человека')}</div></div>`;}).join('')}</div></section>`:'';
    const card=c=>`<div class="face-card"><div class="face-strip">${c.faces.slice(0,4).map(f=>`<img src="/media/face/${f.id}/crop" alt="">`).join('')}</div><p>${count(c.faces.length,'снимок','снимка','снимков')}</p>${picker(c.faces.map(f=>f.id))}</div>`,groups=data.clusters.filter(c=>c.faces.length>1),single=data.clusters.filter(c=>c.faces.length===1);
    const clusters=data.clusters.length?`<section class="panel general-people"><h3>Неопознанные люди <span class="muted">${data.clusters.length}</span></h3><p class="muted small">Похожие лица собраны вместе. Выберите ученика один раз — связь появится на всех снимках группы.</p>${groups.length?`<div class="face-grid">${groups.map(card).join('')}</div>`:''}${single.length?`<details class="single-faces" ${groups.length?'':'open'}><summary>${count(single.length,'лицо встречается','лица встречаются','лиц встречаются')} на одном снимке</summary><div class="face-grid">${single.map(card).join('')}</div></details>`:''}</section>`:'';
    return coverage+uncertain+clusters||'<div class="empty-state"><h3>Людей пока нет</h3><p>Лица появятся после анализа снимков.</p></div>';}
  async function openPhoto(id){const d=await api(`/orders/${state.order.id}/general/${id}`),data=await load(),a=data.photos.find(p=>p.id===id),labels=data.labels,taken=d.faces.filter(f=>f.subject&&(f.source==='manual'||f.level==='auto')).map(f=>f.subject);faceDialog=id;
    $('#person-content').innerHTML=`<div class="dialog-heading"><h2 id="person-title">${esc(d.filename)}</h2><button class="close" data-close="person-dialog" aria-label="Закрыть">×</button></div>
    <div class="general-detail"><div class="general-figure"><img src="/media/${id}/full" alt="${esc(d.filename)}">${d.faces.map((f,i)=>`<span class="face-box ${f.subject?'known':''}" style="left:${f.box[0]*100}%;top:${f.box[1]*100}%;width:${f.box[2]*100}%;height:${f.box[3]*100}%"><b>${i+1}</b></span>`).join('')}</div>
    <div class="general-facts">${tags(a,labels)}<dl><dt>Люди</dt><dd>${labels.bucket[a.bucket]} · ${a.count}</dd><dt>Крупность</dt><dd>${labels.scale[a.scale]}</dd><dt>Оценка</dt><dd>${Math.round((a.quality||0)*100)} из 100</dd>${a.tags.length?`<dt>Сцена</dt><dd>${a.tags.map(t=>labels.tags[t]).join(', ')}</dd>`:''}${a.style?`<dt>Стиль</dt><dd>${a.style==='posed'?'Постановка':'Репортаж'}</dd>`:''}${a.taken_at?`<dt>Снято</dt><dd>${esc(a.taken_at.replace('T',' ').slice(0,16))}</dd>`:''}</dl>
    <h3>Лица <span class="muted">${d.faces.length}</span></h3><div class="face-list">${d.faces.map((f,i)=>`<div class="face-row"><img src="/media/face/${f.id}/crop" alt=""><span>${i+1}</span>${picker([f.id],f.source==='stranger'?'stranger':f.source==='manual'||f.level==='auto'?f.subject||'':'',`Лицо ${i+1}`,taken)}</div>`).join('')||'<p class="muted small">Лиц не найдено.</p>'}</div>
    <p class="muted small">Лица сопоставляются с персонами из портретной съёмки. Ручной выбор сохраняется при повторном анализе.</p></div></div>`;
    if(!$('#person-dialog').open)$('#person-dialog').showModal();}
  async function mutate(path,body,message){await api(path,json('PUT',body));cache.key='';await refreshOrder();await render();if(faceDialog&&$('#person-dialog').open)await openPhoto(faceDialog);if(message)toast(message);}
  async function faces(ids,value){const [action,person]=value.startsWith('person:')?['person',value.slice(7)]:[value,null];await mutate(`/orders/${state.order.id}/general/faces`,{face_ids:ids,action,person_id:person},action==='person'?'Лицо связано с учеником':'Отметка сохранена');}
  document.addEventListener('click',async e=>{const t=e.target.closest('[data-general]');if(!t)return;e.preventDefault();const action=t.dataset.general;try{
    if(action==='pick')openPicker(t);
    if(action==='open')await openPhoto(t.dataset.id);
    if(action==='best')await mutate(`/orders/${state.order.id}/general/best`,{photo_id:t.dataset.id},'Лучший кадр серии выбран');
    if(action==='face')await faces(t.dataset.faces.split(','),t.dataset.value);
    if(action==='reanalyze'){const r=await api(`/orders/${state.order.id}/shoots/${state.shootId}/reanalyze`,json('POST',{}));cache.key='';await refreshOrder();toast(`Снимки поставлены в очередь: ${r.queued}`);}
    if(action==='flag'){const ids=[...state.selected];if(!ids.length){toast('Сначала выберите фотографии');return;}const data=await load(),flag=t.dataset.flag;let value=t.dataset.value==='1';if(t.dataset.value==='toggle')value=!ids.every(id=>data.photos.find(p=>p.id===id)?.flags[flag]);await mutate(`/orders/${state.order.id}/general/flags`,{photo_ids:ids,flag,value},flag==='excluded'?(value?'Снимки не попадут в макет':'Снимки снова доступны макету'):value?'Отметка добавлена':'Отметка снята');}
  }catch(error){toast(error.message);}});
  $('#person-dialog')?.addEventListener('close',()=>{faceDialog=null;if(pick.el?.matches(':popover-open'))pick.el.hidePopover();});
  /* Flag buttons for the floating selection bar. */
  function dockActions(button){return button('data-general="flag" data-flag="excluded" data-value="1"','x','Не использовать','Не брать в макет')+button('data-general="flag" data-flag="excluded" data-value="0"','retry','Вернуть','Снова использовать в макете')+button('data-general="flag" data-flag="must_use" data-value="toggle"','ok','Обязательно','Обязательно поставить в макет')+button('data-general="flag" data-flag="hero" data-value="toggle"','star','Главное фото','Крупно в макете');}
  return {section,render,dockActions,isGeneral:()=>shoot()?.kind==='general',visiblePhotos:()=>cache.data&&state.photoFilter!=='people'?visible(cache.data):[],reset:()=>{cache={key:'',data:null,loading:null};}};
})();
