(()=>{'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],clone=v=>JSON.parse(JSON.stringify(v)),uid=()=>crypto.randomUUID(),round=n=>Math.round(n*10)/10,clamp=(n,a,b)=>Math.max(a,Math.min(b,n)),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icons={text:'text',photo:'photo',rect:'rect',grid:'grid',ellipse:'ellipse',line:'line'},img=(key)=>`<img src="assets/editor/${key}.svg" alt="">`;
let doc=MasterDefaults.create(),serverId=new URLSearchParams(location.search).get('id'),revision=null,design=null,packageMeta=null,dirty=false,saving=false,ready=false,history=[],future=[],renderToken=0,changing=false,preview=false,inspectorTab='design',tool='select',selected=[],zoomMode='fit',clipboard=null,pan=null,space=false,packageMode='new';
const view={teachers:5,students:22,owner:'s0',long:false,missing:false,section:'students',spread:0,side:0};
const canvas=new fabric.Canvas('design-canvas',{preserveObjectStacking:true,selection:true,selectionColor:'#7712b30d',selectionBorderColor:'#a677c0',fireRightClick:false,stopContextMenu:true});
fabric.FabricObject.prototype.set({cornerColor:'#fff',cornerStrokeColor:'#9063b2',borderColor:'#9063b2',cornerSize:8,transparentCorners:false,padding:0});
let planner=MasterPlanner(doc,view),plans=[];const assetCache=new Map();
const section=()=>doc.sections.find(s=>s.id===view.section)||doc.sections[0];
const page=()=>section().spreads[Math.min(view.spread,section().spreads.length-1)]?.pages[view.side];
const allLayers=()=>doc.sections.flatMap(s=>s.spreads.flatMap(sp=>sp.pages.flatMap(p=>p.layers)));
const chosen=()=>allLayers().filter(l=>selected.includes(l.id));
const selectedLayer=()=>chosen()[0];
function notify(message,error=false){$('#feedback').textContent=message;$('#feedback').classList.toggle('error',error);}
async function api(path,method='GET',body){const r=await fetch('/api'+path,{method,headers:{'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});const d=await r.json();if(!r.ok)throw Error(typeof d.detail==='string'?d.detail:'Проверьте значения полей');return d;}
function markDirty(){dirty=true;$('#server-state').textContent='Не сохранено';try{localStorage.setItem('af-package-'+serverId,JSON.stringify({document:doc,revision}));}catch(e){notify('Локальная копия не поместилась. Сохраните на сервер.',true);}}
function commit(fn){history.push(clone(doc));if(history.length>60)history.shift();future=[];fn();markDirty();render();}
function undo(){if(!history.length)return;future.push(clone(doc));doc=history.pop();selected=[];markDirty();render();}
function redo(){if(!future.length)return;history.push(clone(doc));doc=future.pop();selected=[];markDirty();render();}
async function save(){if(!ready||saving)throw Error('Дождитесь загрузки или сохранения');saving=true;$('#server-save').disabled=true;const snapshot=clone(doc);try{const r=await api('/master-templates'+(serverId?'/'+serverId:''),serverId?'PUT':'POST',{document:snapshot,revision});serverId=r.id;revision=r.revision;dirty=JSON.stringify(snapshot)!==JSON.stringify(doc);historyURL();$('#server-state').textContent=dirty?'Не сохранено':'Сохранено';if(!dirty)localStorage.removeItem('af-package-'+serverId);return r;}finally{saving=false;$('#server-save').disabled=false;}}
function historyURL(){window.history.replaceState(null,'','?id='+encodeURIComponent(serverId));}
async function load(id){$('#canvas-loading').hidden=false;ready=false;try{const data=await api('/master-templates/'+id);doc=data.document;serverId=data.id;revision=data.revision;packageMeta=data.package;if(packageMeta)design=await api('/designs/'+packageMeta.design_id);dirty=false;history=[];future=[];selected=[];view.section=doc.sections[0].id;view.spread=0;view.side=0;ready=true;historyURL();$('#server-state').textContent='Сохранено';renderHeader();render();}catch(e){notify(e.message,true);}finally{$('#canvas-loading').hidden=true;}}
function renderHeader(){$('#design-title').textContent=design?.name||doc.name;$('#package-switch').innerHTML=(design?.packages||[{template_id:serverId,name:'Основная',price:0}]).map(p=>`<option value="${p.template_id}" ${p.template_id===serverId?'selected':''}>${esc(p.name)} · ${p.price.toLocaleString('ru-RU')} ₽</option>`).join('');}
function freshIds(value){const copy=clone(value);const walk=o=>{if(!o||typeof o!=='object')return;if(o.id)o.id=uid();Object.values(o).forEach(v=>{if(Array.isArray(v))v.forEach(walk);else if(v&&typeof v==='object')walk(v);});};walk(copy);return copy;}
function miniSpread(sp){return `<div class="mini-spread">${sp.pages.map(p=>`<div class="mini-page" style="background:${p.background}">${p.layers.filter(l=>!l.hidden).map(l=>{const b=l.box,style=`left:${b.x/210*100}%;top:${b.y/280*100}%;width:${b.w/210*100}%;height:${b.h/280*100}%;background:${l.fill||'transparent'};opacity:${(l.opacity??100)/100};border-radius:${l.type==='ellipse'?'50%':'0'}`;return `<div class="mini-layer" style="${style}">${l.type==='photo'?`<img src="${esc(l.dataUrl||planner.placeholderSvg({id:'s0'}))}" alt="">`:l.type==='grid'?'<div class="mini-grid">'+Array.from({length:9},()=>'<i></i>').join('')+'</div>':l.type==='text'?`<span style="font-size:4px">${esc(l.text)}</span>`:''}</div>`;}).join('')}</div>`).join('')}</div>`;}
function renderNavigation(){const sec=section();$('#sections').innerHTML=doc.sections.map(s=>{const p=plans.find(p=>p.sectionId===s.id);return `<div class="section-card ${s.id===sec.id?'active':''}" data-section="${s.id}" role="button" tabindex="0" aria-label="${esc(s.name)}">${miniSpread(s.spreads[0])}<div class="section-caption"><span>${esc(s.name)}</span><small>${p.spreads} разв.</small></div></div>`;}).join('');$('#section-title').textContent=sec.name;const count=preview?plans.find(p=>p.sectionId===sec.id).spreads:sec.spreads.length;view.spread=clamp(view.spread,0,Math.max(0,count-1));$('#spread-label').textContent=preview?`Альбом · ${view.spread+1} из ${count}`:`Шаблон ${view.spread+1} из ${count}`;$('#spread-select').innerHTML=Array.from({length:count},(_,i)=>`<option value="${i}" ${view.spread===i?'selected':''}>${i+1} / ${count}</option>`).join('');$('#prev-spread').disabled=view.spread===0;$('#next-spread').disabled=view.spread>=count-1;$('#delete-spread').disabled=sec.spreads.length<=1;renderLayers();}
function renderLayers(){const p=page();$('#page-side').textContent=view.side?'Правая':'Левая';$('#layers').innerHTML=(p?.layers||[]).slice().reverse().map(l=>`<div class="layer-row ${selected.includes(l.id)?'active':''}" data-layer="${l.id}" role="button" tabindex="0" aria-label="Слой ${esc(l.name)}">${img(icons[l.type])}<span>${esc(l.name)}</span><button data-layer-toggle="hidden" data-id="${l.id}" title="${l.hidden?'Показать':'Скрыть'} слой" aria-label="${l.hidden?'Показать':'Скрыть'} ${esc(l.name)}">${l.hidden?'◌':'◉'}</button><button data-layer-toggle="locked" data-id="${l.id}" title="Закрепить слой" aria-label="Закрепить ${esc(l.name)}">${l.locked?'▣':'▫'}</button></div>`).join('')||'<p class="section-note">Добавьте текст, фото или фигуру с панели внизу.</p>';}
function field(label,key,value,type='number',attrs=''){return `<label>${label}<input data-prop="${key}" type="${type}" value="${esc(type==='number'?round(value||0):value||'')}" ${attrs}></label>`;}
function number(label,key,value,min=0,max=280){return `<label class="compact-number" title="${label}"><span>${label}</span><input aria-label="${label}" data-prop="${key}" type="number" value="${round(value||0)}" min="${min}" max="${max}" step="0.1"></label>`;}
function select(label,key,value,options){return `<label>${label}<select data-prop="${key}">${options.map(([k,n])=>`<option value="${k}" ${value===k?'selected':''}>${n}</option>`).join('')}</select></label>`;}
function block(title,body){return `<section class="inspector-section"><h3>${title}</h3>${body}</section>`;}
function alignmentIcon(type){const paths={left:'M4 3v18M7 7h12M7 12h8M7 17h12',cx:'M12 3v18M5 7h14M8 12h8M5 17h14',right:'M20 3v18M5 7h12M9 12h8M5 17h12',top:'M3 4h18M7 7v12M12 7v8M17 7v12',cy:'M3 12h18M7 5v14M12 8v8M17 5v14',bottom:'M3 20h18M7 5v12M12 9v8M17 5v12'};return `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><path d="${paths[type]}"/></svg>`;}
function renderInspector(){const l=selectedLayer(),sec=section();let html='';if(inspectorTab==='rules'){
html=block('Раздел',field('Название','section.name',sec.name,'text','maxlength="100"')+select('Как добавлять страницы','section.kind',sec.kind,[['fixed','Фиксированный объём'],['flow','Все участники списка'],['repeat','Личные развороты']])+ (sec.kind==='flow'?field('Ориентир, разворотов','section.target',sec.target||1,'number','min="1" max="100"')+'<p class="section-note">Добавим страницы, если виньетки не помещаются. Общий объём альбома не ограничен этим числом.</p>':sec.kind==='repeat'?select('Повторение','personalMode',doc.personalMode,[['all','Для каждого ученика'],['owner','Только владельцу варианта'],['off','Выключено']]):'<p class="section-note">В альбом войдут все шаблоны этого раздела. Добавляйте развороты кнопкой ＋ над холстом.</p>'))+block('Порядок',`<div class="inspector-actions"><button data-action="section-up">↑ Раньше</button><button data-action="section-down">↓ Позже</button></div><button class="wide" data-action="section-delete" style="margin-top:8px">Удалить раздел</button>`);
const issues=plans.find(p=>p.sectionId===sec.id)?.issues||[];html+=block('Проверка примера',issues.length?issues.map(i=>`<div class="issue ${i.severity}">${esc(i.text)}</div>`).join(''):'<p class="section-note">Для текущего состава ошибок нет.</p>');
}else if(l){const multi=selected.length>1;html=block(multi?`${selected.length} объекта`:({photo:'Фоторамка',text:'Текст',grid:'Автовиньетка',rect:'Прямоугольник',ellipse:'Эллипс',line:'Линия'})[l.type],multi?'<p class="section-note">Shift + клик — добавить к выделению.</p>':`<input class="selection-name" aria-label="Название слоя" data-prop="name" value="${esc(l.name)}" maxlength="100">`);
html+=block('Положение',`<div class="align-tools">${[['left','По левому краю'],['cx','Центр по горизонтали'],['right','По правому краю'],['top','По верхнему краю'],['cy','Центр по вертикали'],['bottom','По нижнему краю']].map(([k,n])=>`<button data-align="${k}" title="${n}" aria-label="${n}">${alignmentIcon(k)}</button>`).join('')}</div><div class="field-grid">${number('X','box.x',l.box.x,0,210)}${number('Y','box.y',l.box.y)}</div><div class="field-grid" style="margin-top:8px">${number('Угол °','angle',l.angle||0,-180,180)}<button data-action="rotate">↻ 90°</button></div>`);
html+=block('Размер',`<div class="field-grid">${number('W','box.w',l.box.w,1,210)}${number('H','box.h',l.box.h,1,280)}</div>`);
if(!multi&&l.type==='text')html+=block('Текст',`<textarea data-prop="text" aria-label="Текст" maxlength="2000">${esc(l.text)}</textarea><div class="field-grid" style="margin-top:10px">${select('Шрифт','font',l.font,[['Arial','Arial'],['Georgia','Georgia'],['Times New Roman','Times New Roman']])}${field('Кегль, pt','fontSize',l.fontSize,'number','min="4" max="120"')}</div>${select('Выравнивание','align',l.align,[['left','Слева'],['center','По центру'],['right','Справа']])}${select('Содержимое','binding',l.binding,[['static','Свой текст'],['owner.name','Имя владельца альбома'],['item.name','Имя ученика разворота'],['lead.name','Имя руководителя'],['class','Название класса'],['year','Год выпуска']])}`);
if(!multi&&l.type==='photo')html+=block('Фотография',select('Источник','source',l.source,[['owner','Владелец альбома'],['item','Ученик разворота'],['lead','Классный руководитель'],['class','Общее фото'],['custom','Загруженный файл']])+`<label class="upload-button">Загрузить изображение<input id="photo-upload" type="file" accept="image/jpeg,image/png,image/webp"></label><div class="field-grid">${number('Кадр X','cropX',l.cropX??50,0,100)}${number('Кадр Y','cropY',l.cropY??50,0,100)}</div><p class="section-note">Двойной клик по фото открывает его параметры. Исходный снимок не изменяется.</p>`);
if(!multi&&l.type==='grid')html+=block('Виньетки',select('Кого разместить','source',l.source,[['students','Учеников'],['teachers','Учителей']])+`<div class="field-grid">${field('Минимум','min',l.min,'number','min="1" max="30"')}${field('Максимум','max',l.max,'number','min="1" max="30"')}${field('Отступ, мм','gap',l.gap,'number','min="0" max="30"')}${field('Фото от, мм','minPhotoWidth',l.minPhotoWidth,'number','min="5" max="180"')}${field('Кегль, pt','fontSize',l.fontSize,'number','min="4" max="40"')}${field('Минимальный','minFontSize',l.minFontSize,'number','min="4" max="40"')}</div>${select('Шрифт','font',l.font,[['Arial','Arial'],['Georgia','Georgia'],['Times New Roman','Times New Roman']])}<label class="check"><input data-prop="excludeLead" type="checkbox" ${l.excludeLead?'checked':''}>Не повторять руководителя</label><label class="check"><input data-prop="strictMin" type="checkbox" ${l.strictMin?'checked':''}>Строгий минимум</label><p class="section-note">Стиль общий для всех виньеток раздела.</p>`);
html+=block('Оформление',`<div class="field-grid">${field('Непрозрачность, %','opacity',l.opacity??100,'number','min="0" max="100"')}${field('Радиус, мм','radius',l.radius||0,'number','min="0" max="100"')}</div>${l.type!=='photo'?field('Цвет',['text','grid'].includes(l.type)?'color':'fill',l.color||l.fill||'#333333','color'):''}<div class="field-grid">${field('Обводка','stroke',l.stroke||'#333333','color')}${field('Толщина, мм','strokeWidth',l.strokeWidth||0,'number','min="0" max="10" step="0.1"')}</div><label class="check"><input data-prop="locked" type="checkbox" ${l.locked?'checked':''}>Закрепить положение</label>`);
html+=block('Действия',`<div class="inspector-actions"><button data-action="duplicate" title="Дублировать · ⌘D" aria-label="Дублировать">${img('copy')}</button><button data-action="forward" title="На слой выше" aria-label="На слой выше">↑</button><button data-action="backward" title="На слой ниже" aria-label="На слой ниже">↓</button><button data-action="delete" title="Удалить" aria-label="Удалить">${img('trash')}</button></div>`);
}else{html=block('Страница',`<div class="field-grid"><button data-side="0" class="${view.side===0?'active':''}">Левая</button><button data-side="1" class="${view.side===1?'active':''}">Правая</button></div>${field('Фон','page.background',page()?.background||'#ffffff','color')}<p class="section-note">Выберите объект на холсте, чтобы изменить его оформление.</p>`)+block('Начните с инструмента','<p class="section-note">Текст, фотографии и фигуры — на панели внизу. Нажмите инструмент, затем кликните на страницу.<br><br>Shift — несколько объектов.<br>Пробел — перемещение холста.<br>⌘/Ctrl + колесо — масштаб.</p>');}
$('#inspector').innerHTML=html;$('#inspector').inert=preview;$$('[data-inspector]').forEach(b=>b.classList.toggle('active',b.dataset.inspector===inspectorTab));}
function render(){planner=MasterPlanner(doc,view);plans=planner.plan();if(!doc.sections.some(s=>s.id===view.section)){view.section=doc.sections[0].id;view.spread=0;}selected=selected.filter(id=>allLayers().some(l=>l.id===id));renderNavigation();renderInspector();renderScene();$('#undo').disabled=!history.length;$('#redo').disabled=!future.length;const n=plans.reduce((n,p)=>n+p.spreads,0),errors=plans.flatMap(p=>p.issues).filter(i=>i.severity==='error').length;$('#summary').textContent=`${n} разв. · ${n*2} страниц${errors?' · '+errors+' ошибок':''}`;$('#owner').innerHTML=planner.people('students').map(p=>`<option value="${p.id}" ${view.owner===p.id?'selected':''}>${p.name}</option>`).join('');setTool(tool);}
async function imageElement(src){if(!assetCache.has(src))assetCache.set(src,new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>resolve(image);image.onerror=()=>reject(Error('Не удалось загрузить изображение'));image.src=src;}));return assetCache.get(src);}
async function renderScene(){const token=++renderToken;const sec=section(),plan=plans.find(p=>p.sectionId===sec.id);const pages=preview?plan.pages.slice(view.spread*2,view.spread*2+2):sec.spreads[view.spread]?.pages.map(p=>plan.pages.find(g=>g.templateId===p.id)||{templateId:p.id,personId:view.owner,records:planner.people(p.layers.find(l=>l.type==='grid')?.source||'students').slice(0,8)});const objects=[];
for(let side=0;side<2;side++){const g=pages?.[side],p=planner.getTemplatePage(g?.templateId);objects.push(new fabric.Rect({left:side*210,top:0,width:210,height:280,fill:p?.background||'#fff',stroke:'#e5e1e8',strokeWidth:.25,selectable:false,evented:false,shadow:new fabric.Shadow({color:'#2222220a',blur:9,offsetX:0,offsetY:3})}));if(!p)continue;for(const l of p.layers.filter(l=>!l.hidden)){let object;const b=l.box,base={left:side*210+b.x+b.w/2,top:b.y+b.h/2,originX:'center',originY:'center',angle:l.angle||0,opacity:(l.opacity??100)/100,stroke:l.stroke||'#333333',strokeWidth:l.strokeWidth||0,selectable:!preview&&!l.locked,evented:!preview,lockMovementX:!!l.locked,lockMovementY:!!l.locked,lockRotation:!!l.locked,lockScalingX:!!l.locked,lockScalingY:!!l.locked,lockScalingFlip:true,cornerColor:'#ffffff',cornerStrokeColor:'#9664b5',borderColor:'#9664b5',transparentCorners:false,cornerSize:7};
if(l.type==='text'){object=new fabric.Textbox(planner.resolvedText(l,g),{...base,width:b.w,fontSize:l.fontSize*.3528,fontFamily:l.font,fill:l.color,textAlign:l.align,lineHeight:1.25,editable:l.binding==='static'&&!preview&&!l.locked,splitByGrapheme:false});}
else if(l.type==='photo'){const src=planner.resolvedPhoto(l,g);if(src){try{const el=await imageElement(src);const ratio=b.w/b.h,w=el.naturalWidth,h=el.naturalHeight,cw=w/h>ratio?h*ratio:w,ch=w/h>ratio?h:w/ratio;object=new fabric.FabricImage(el,{...base,width:cw,height:ch,cropX:(w-cw)*(l.cropX??50)/100,cropY:(h-ch)*(l.cropY??50)/100,scaleX:b.w/cw,scaleY:b.h/ch});if(l.radius)object.clipPath=new fabric.Rect({width:cw,height:ch,rx:l.radius*cw/b.w,ry:l.radius*ch/b.h,originX:'center',originY:'center'});}catch(e){notify(e.message,true);}}if(!object)object=new fabric.Rect({...base,width:b.w,height:b.h,fill:'#f1edf4',stroke:'#bca9ca',strokeWidth:.5,strokeDashArray:[2,2]});}
else if(l.type==='grid'){const records=g.records||[],geo=planner.gridGeometry(g.layoutCount||Math.max(1,records.length),l),children=[new fabric.Rect({left:0,top:0,width:b.w,height:b.h,fill:'transparent',strokeWidth:0})];if(geo){for(let i=0;i<records.length;i++){const x=(i%geo.cols)*(geo.cellW+l.gap)+(geo.cellW-geo.photoW)/2,y=Math.floor(i/geo.cols)*(geo.cellH+l.gap);const el=await imageElement(planner.placeholderSvg(records[i]));children.push(new fabric.FabricImage(el,{left:x,top:y,scaleX:geo.photoW/el.naturalWidth,scaleY:(geo.photoW/.75)/el.naturalHeight,opacity:records[i].missing?.2:1}));children.push(new fabric.Textbox(records[i].name,{left:x-(geo.cellW-geo.photoW)/2,top:y+geo.photoW/.75+3,width:geo.cellW,fontFamily:l.font,fontSize:(g.actualFont||l.fontSize)*.3528,lineHeight:1.25,textAlign:'center',fill:l.color,strokeWidth:0}));}}object=new fabric.Group(children,{...base,width:b.w,height:b.h,subTargetCheck:false});}
else if(l.type==='ellipse')object=new fabric.Ellipse({...base,rx:b.w/2,ry:b.h/2,fill:l.fill});else object=new fabric.Rect({...base,width:b.w,height:b.h,rx:l.radius||0,ry:l.radius||0,fill:l.fill});object.masterId=l.id;object.pageId=p.id;object.side=side;object.baseWidth=b.w;object.baseHeight=b.h;objects.push(object);}}
if(token!==renderToken)return;changing=true;canvas.discardActiveObject();canvas.clear();canvas.backgroundColor='#f0f0f2';canvas.add(...objects);const targets=objects.filter(o=>selected.includes(o.masterId)&&o.selectable);if(targets.length===1)canvas.setActiveObject(targets[0]);else if(targets.length>1)canvas.setActiveObject(new fabric.ActiveSelection(targets,{canvas}));canvas.requestRenderAll();changing=false;}
function fit(){const host=$('#canvas-host'),w=host.clientWidth,h=host.clientHeight;canvas.setDimensions({width:w,height:h});const scale=zoomMode==='fit'?Math.max(.2,Math.min((w-70)/420,(h-180)/280)):Number(zoomMode)*2;canvas.setViewportTransform([scale,0,0,scale,(w-420*scale)/2,(h-280*scale)/2-5]);}
new ResizeObserver(()=>fit()).observe($('#canvas-host'));
function syncSelection(){if(changing)return;const objects=canvas.getActiveObjects();selected=objects.map(o=>o.masterId).filter(Boolean);if(objects[0])view.side=objects[0].side;renderLayers();renderInspector();if(selected.length&&window.innerWidth<850)$('.right-panel').classList.add('mobile-open');}
canvas.on('selection:created',syncSelection);canvas.on('selection:updated',syncSelection);canvas.on('selection:cleared',()=>{if(!changing){selected=[];renderLayers();renderInspector();$('.right-panel').classList.remove('mobile-open');}});
canvas.on('object:modified',event=>{if(changing||preview)return;const objects=event.target instanceof fabric.ActiveSelection?event.target.getObjects():[event.target];const changes=objects.filter(o=>o.masterId).map(o=>{const c=o.getCenterPoint(),scale=o.getObjectScaling(),l=allLayers().find(l=>l.id===o.masterId),w=round(o.width*scale.x),h=round(o.height*scale.y);return {l,w,h,x:round(c.x-w/2-o.side*210),y:round(c.y-h/2),angle:round(o.getTotalAngle())};});commit(()=>changes.forEach(({l,w,h,x,y,angle})=>{l.box={x:clamp(x,0,210-Math.min(w,210)),y:clamp(y,0,280-Math.min(h,280)),w:clamp(w,1,210),h:clamp(h,1,280)};l.angle=((angle+180)%360+360)%360-180;}));});
canvas.on('text:editing:exited',({target})=>{const l=allLayers().find(l=>l.id===target.masterId);if(l&&l.text!==target.text)commit(()=>{l.text=target.text.slice(0,2000);l.box.h=round(Math.min(280-l.box.y,target.height));});});
canvas.on('object:moving',({target,e})=>{if(e?.altKey)return;const c=target.getCenterPoint(),side=target.side||0;for(const x of [side*210+105])if(Math.abs(c.x-x)<1.5)target.set('left',target.left+x-c.x);if(Math.abs(c.y-140)<1.5)target.set('top',target.top+140-c.y);});
canvas.on('mouse:down',opt=>{const e=opt.e;if(space||tool==='hand'){pan={x:e.clientX,y:e.clientY};canvas.selection=false;return;}if(preview)return;const point=canvas.getScenePoint(e);if(point.x<0||point.x>420||point.y<0||point.y>280)return;view.side=point.x>=210?1:0;if(tool!=='select'){addLayer(tool,point.x-view.side*210,point.y);return;}if(!opt.target?.masterId){selected=[];renderLayers();renderInspector();}});
canvas.on('mouse:move',opt=>{if(pan){const v=canvas.viewportTransform;v[4]+=opt.e.clientX-pan.x;v[5]+=opt.e.clientY-pan.y;pan={x:opt.e.clientX,y:opt.e.clientY};canvas.requestRenderAll();}});canvas.on('mouse:up',()=>{if(pan){pan=null;canvas.setViewportTransform(canvas.viewportTransform);canvas.selection=!preview&&tool==='select';}});
canvas.on('mouse:wheel',opt=>{const e=opt.e;e.preventDefault();e.stopPropagation();if(e.ctrlKey||e.metaKey){const zoom=clamp(canvas.getZoom()*Math.pow(.999,e.deltaY),.2,8);canvas.zoomToPoint(new fabric.Point(e.offsetX,e.offsetY),zoom);zoomMode=zoom/2;$('#zoom').value='';}else{const v=canvas.viewportTransform;v[4]-=e.deltaX;v[5]-=e.deltaY;canvas.requestRenderAll();}});
function setTool(next){tool=next;canvas.selection=tool==='select'&&!preview;canvas.skipTargetFind=tool!=='select'||preview;canvas.defaultCursor=tool==='hand'?'grab':tool==='select'?'default':'crosshair';$$('[data-tool]').forEach(b=>b.classList.toggle('active',b.dataset.tool===tool));$('#tool-hint').textContent=preview?'Предпросмотр альбома · реальные данные появятся в заказе':tool==='select'?'Shift — несколько объектов · пробел — перемещение':tool==='hand'?'Перетащите холст':`Нажмите на страницу, чтобы добавить объект`;}
function addLayer(type,x=24,y=36){if(preview)return;const p=page();if(!p)return;if(type==='grid'&&p.layers.some(l=>l.type==='grid'))return notify('На этой странице уже есть виньетка',true);const l={id:uid(),type,name:({text:'Текст',photo:'Фотография',rect:'Прямоугольник',ellipse:'Эллипс',line:'Линия',grid:'Автовиньетка'})[type],opacity:100,angle:0,box:{x:round(x),y:round(y),w:80,h:50}};if(type==='text')Object.assign(l,{text:'Новый текст',binding:'static',font:'Arial',fontSize:24,color:'#333333',align:'left',box:{x:round(x),y:round(y),w:80,h:20}});if(type==='photo')Object.assign(l,{source:'owner',cropX:50,cropY:50,box:{x:round(x),y:round(y),w:80,h:106}});if(['rect','ellipse','line'].includes(type)){l.fill='#d9d2e1';if(type==='line')l.box.h=1;}if(type==='grid')Object.assign(l,{source:'students',min:4,max:12,gap:5,minPhotoWidth:32,font:'Arial',fontSize:12,minFontSize:10,color:'#333333',styleGroup:section().id,box:{x:16,y:33,w:178,h:224}});l.box.x=clamp(l.box.x,0,210-l.box.w);l.box.y=clamp(l.box.y,0,280-l.box.h);commit(()=>{p.layers.push(l);if(type==='grid')section().kind='flow';selected=[l.id];});setTool('select');}
function property(key,value){if(preview)return;const l=selectedLayer();if(key==='section.kind'&&value!=='flow'&&section().spreads.some(sp=>sp.pages.some(p=>p.layers.some(l=>l.type==='grid'))))return notify('Удалите виньетки перед сменой правила раздела',true);commit(()=>{if(key.startsWith('section.')){section()[key.split('.')[1]]=value;return;}if(key==='personalMode'){doc.personalMode=value;return;}if(key==='page.background'){page().background=value;return;}if(!l)return;let layers=chosen();if(l.type==='grid'&&['source','min','max','gap','minPhotoWidth','font','fontSize','minFontSize','color','strictMin','excludeLead'].includes(key))layers=section().spreads.flatMap(sp=>sp.pages.flatMap(p=>p.layers)).filter(i=>i.type==='grid');for(const item of layers){if(key.startsWith('box.')){item.box[key.split('.')[1]]=value;item.box.w=clamp(item.box.w,1,210);item.box.h=clamp(item.box.h,1,280);item.box.x=clamp(item.box.x,0,210-item.box.w);item.box.y=clamp(item.box.y,0,280-item.box.h);}else item[key]=value;}});}
function align(which){commit(()=>{const list=chosen();if(!list.length)return;let minX=0,minY=0,maxX=210,maxY=280;if(list.length>1){minX=Math.min(...list.map(l=>l.box.x));minY=Math.min(...list.map(l=>l.box.y));maxX=Math.max(...list.map(l=>l.box.x+l.box.w));maxY=Math.max(...list.map(l=>l.box.y+l.box.h));}for(const l of list){if(which==='left')l.box.x=minX;if(which==='cx')l.box.x=(minX+maxX-l.box.w)/2;if(which==='right')l.box.x=maxX-l.box.w;if(which==='top')l.box.y=minY;if(which==='cy')l.box.y=(minY+maxY-l.box.h)/2;if(which==='bottom')l.box.y=maxY-l.box.h;}});}
function action(type){if(preview)return;const sec=section();if(type.startsWith('section-')){commit(()=>{const i=doc.sections.indexOf(sec);if(type==='section-delete'){if(doc.sections.length>1){doc.sections.splice(i,1);view.section=doc.sections[0].id;view.spread=0;selected=[];}}else{const next=clamp(i+(type==='section-up'?-1:1),0,doc.sections.length-1);doc.sections.splice(i,1);doc.sections.splice(next,0,sec);}});return;}if(!selected.length)return;commit(()=>{for(const sp of sec.spreads)for(const p of sp.pages){const targets=p.layers.filter(l=>selected.includes(l.id));if(type==='delete')p.layers=p.layers.filter(l=>!selected.includes(l.id));if(type==='duplicate')for(const l of targets.filter(l=>l.type!=='grid')){const copy=clone(l);copy.id=uid();copy.name+=' · копия';copy.box.x=clamp(copy.box.x+5,0,210-copy.box.w);copy.box.y=clamp(copy.box.y+5,0,280-copy.box.h);p.layers.push(copy);}if(type==='rotate')targets.forEach(l=>l.angle=((l.angle||0)+90+180)%360-180);if(type==='forward'||type==='backward')for(const l of targets){const i=p.layers.indexOf(l),to=clamp(i+(type==='forward'?1:-1),0,p.layers.length-1);p.layers.splice(i,1);p.layers.splice(to,0,l);}}if(type==='delete')selected=[];});}
$('#sections').onclick=e=>{const node=e.target.closest('[data-section]');if(!node)return;view.section=node.dataset.section;view.spread=0;view.side=0;selected=[];render();};$('#sections').onkeydown=e=>{if(e.key==='Enter')e.target.click();};
$('#layers').onclick=e=>{const toggle=e.target.closest('[data-layer-toggle]');if(toggle){const l=allLayers().find(l=>l.id===toggle.dataset.id);commit(()=>l[toggle.dataset.layerToggle]=!l[toggle.dataset.layerToggle]);return;}const row=e.target.closest('[data-layer]');if(!row)return;selected=e.shiftKey?[...new Set([...selected,row.dataset.layer])]:[row.dataset.layer];renderScene();renderLayers();renderInspector();$('.right-panel').classList.add('mobile-open');};
$$('[data-tool]').forEach(b=>b.onclick=()=>{selected=[];canvas.discardActiveObject();setTool(b.dataset.tool);});
$('#inspector').onchange=async e=>{const el=e.target;if(el.id==='photo-upload'){const file=el.files?.[0];if(!file)return;if(file.size>1_000_000||!['image/jpeg','image/png','image/webp'].includes(file.type))return notify('Выберите PNG, JPEG или WebP до 1 МБ',true);const target=selectedLayer();if(!target)return;const reader=new FileReader();reader.onload=()=>commit(()=>{target.dataUrl=reader.result;target.source='custom';});reader.readAsDataURL(file);return;}if(!el.dataset.prop)return;if(el.type==='number'&&!el.reportValidity())return;const value=el.type==='checkbox'?el.checked:el.type==='number'?Number(el.value):el.value;property(el.dataset.prop,value);};
$('#inspector').onclick=e=>{const alignment=e.target.closest('[data-align]');if(alignment)return align(alignment.dataset.align);const a=e.target.closest('[data-action]');if(a)return action(a.dataset.action);if(e.target.dataset.side){view.side=Number(e.target.dataset.side);selected=[];renderLayers();renderInspector();}};
$$('[data-inspector]').forEach(b=>b.onclick=()=>{inspectorTab=b.dataset.inspector;renderInspector();});
$('#prev-spread').onclick=()=>{view.spread--;selected=[];render();};$('#next-spread').onclick=()=>{view.spread++;selected=[];render();};$('#spread-select').onchange=e=>{view.spread=Number(e.target.value);selected=[];render();};
$('#add-section').onclick=()=>commit(()=>{const s={id:uid(),name:'Новый раздел',kind:'fixed',spreads:[{id:uid(),pages:[{id:uid(),background:'#ffffff',layers:[]},{id:uid(),background:'#ffffff',layers:[]}]}]};doc.sections.push(s);view.section=s.id;view.spread=0;view.side=0;selected=[];inspectorTab='rules';$('.right-panel').classList.add('mobile-open');});
$('#add-spread').onclick=()=>commit(()=>{section().spreads.splice(view.spread+1,0,{id:uid(),pages:[{id:uid(),background:'#ffffff',layers:[]},{id:uid(),background:'#ffffff',layers:[]}]});view.spread++;selected=[];});
$('#duplicate-spread').onclick=()=>commit(()=>{section().spreads.splice(view.spread+1,0,freshIds(section().spreads[view.spread]));view.spread++;selected=[];});
$('#delete-spread').onclick=()=>{if(section().spreads.length<=1)return;commit(()=>{section().spreads.splice(view.spread,1);view.spread=Math.max(0,view.spread-1);selected=[];});};
$('#show-properties').onclick=()=>$('.right-panel').classList.toggle('mobile-open');$('#close-properties').onclick=()=>$('.right-panel').classList.remove('mobile-open');
$('#zoom').onchange=e=>{zoomMode=e.target.value;fit();};$('#undo').onclick=undo;$('#redo').onclick=redo;
$('#preview-toggle').onclick=()=>{preview=!preview;selected=[];view.spread=0;$('#app').classList.toggle('preview',preview);$('#preview-toggle').textContent=preview?'К редактированию':'Предпросмотр';render();};
$('#test-data').onclick=()=>$('#test-dialog').showModal();for(const [selector,key] of [['#student-count','students'],['#teacher-count','teachers']])$(selector).onchange=e=>{if(!e.target.reportValidity())return;view[key]=Number(e.target.value);view.spread=0;if(Number(view.owner.slice(1))>=view.students)view.owner='s0';render();};$('#owner').onchange=e=>{view.owner=e.target.value;render();};$('#long-name').onchange=e=>{view.long=e.target.checked;render();};$('#missing-photo').onchange=e=>{view.missing=e.target.checked;render();};
$('#server-save').onclick=()=>save().catch(e=>notify(e.message,true));
$('#package-switch').onchange=async e=>{try{if(dirty)await save();await load(e.target.value);}catch(error){notify(error.message,true);renderHeader();}};
function packageDialog(mode){packageMode=mode;$('#package-dialog-title').textContent=mode==='new'?'Новая комплектация':'Настройки комплектации';$('#package-help').textContent=mode==='new'?'Скопируем текущие развороты. Правки новой комплектации не изменят исходную.':'Название и цена относятся к этой комплектации. Для новых заказов опубликуйте новую версию.';$('#package-form [name=name]').value=mode==='edit'?packageMeta?.name||'Основная':'';$('#package-form [name=price]').value=mode==='edit'?packageMeta?.price||0:1500;$('#package-form .form-error').textContent='';$('#package-dialog').showModal();}
$('#new-package').onclick=()=>packageDialog('new');$('#package-settings').onclick=()=>packageDialog('edit');$$('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());
$('#package-form').onsubmit=async e=>{e.preventDefault();const f=e.target,b=f.querySelector('[type=submit]'),values=Object.fromEntries(new FormData(f));b.disabled=true;try{if(dirty)await save();values.price=Number(values.price);if(packageMode==='new'){const result=await api('/designs/'+design.id+'/packages','POST',{...values,source_id:serverId});$('#package-dialog').close();await load(result.template_id);}else{await api('/master-templates/'+serverId+'/package','PUT',{...values,revision});$('#package-dialog').close();await load(serverId);}}catch(error){f.querySelector('.form-error').textContent=error.message;}finally{b.disabled=false;}};
$('#publish-master').onclick=()=>{$('#publish-summary').textContent=`${design?.name||doc.name} / ${packageMeta?.name||'Основная'} · ${(packageMeta?.price||0).toLocaleString('ru-RU')} ₽ за альбом`;$('#publish-error').textContent='';$('#publish-dialog').showModal();};
$('#confirm-publish').onclick=async()=>{const b=$('#confirm-publish');b.disabled=true;try{if(dirty)await save();const r=await api('/master-templates/'+serverId+'/publish','POST',{revision});$('#publish-dialog').close();notify(`Опубликована версия ${r.version}. Комплектация доступна в новых заказах.`);$('#server-state').textContent='Опубликовано · v'+r.version;}catch(e){$('#publish-error').textContent=e.message;}finally{b.disabled=false;}};
$$('[data-tab]').forEach(b=>b.onclick=()=>{$$('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));$('#pages-panel').hidden=b.dataset.tab!=='pages';$('#library-panel').hidden=b.dataset.tab!=='library';if(b.dataset.tab==='library')renderLibrary();});
function renderLibrary(){$('#library-list').innerHTML=(design?.blocks||[]).map(b=>`<div class="library-card">${miniSpread(b.section.spreads[0])}<strong>${esc(b.name)}</strong><button data-block="${b.id}">Добавить в комплектацию</button></div>`).join('')||'<p class="section-note">Сохраните раздел как заготовку — он останется здесь даже после удаления из комплектации.</p>';}
$('#save-block').onclick=async()=>{try{if(!design)throw Error('Сначала создайте дизайн');await api('/designs/'+design.id+'/blocks','POST',{name:section().name,section:section()});design=await api('/designs/'+design.id);renderLibrary();notify('Заготовка добавлена в библиотеку дизайна');}catch(e){notify(e.message,true);}};
$('#library-list').onclick=e=>{const b=e.target.closest('[data-block]');if(!b)return;commit(()=>{const s=freshIds(design.blocks.find(x=>x.id===b.dataset.block).section);doc.sections.push(s);view.section=s.id;view.spread=0;selected=[];});};
function download(data,name){const a=document.createElement('a');a.href=data;a.download=name;a.click();}
$('#export').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(doc,null,2)],{type:'application/json'}));download(url,(packageMeta?.name||'master')+'.json');setTimeout(()=>URL.revokeObjectURL(url),1000);};
$('#import').onchange=async e=>{const f=e.target.files?.[0];if(!f)return;if(f.size>8_000_000)return notify('Файл больше 8 МБ',true);try{const parsed=JSON.parse(await f.text());await api('/master-templates/validate','POST',{document:parsed});commit(()=>{doc=parsed;view.section=doc.sections[0].id;view.spread=0;selected=[];});notify('Макет импортирован в текущую комплектацию');}catch(error){notify(error.message,true);}e.target.value='';};
$('#recover').onclick=async()=>{try{const stored=localStorage.getItem('af-package-'+serverId);if(!stored)return notify('Локальной копии нет');const parsed=JSON.parse(stored);await api('/master-templates/validate','POST',{document:parsed.document});commit(()=>{doc=parsed.document;view.section=doc.sections[0].id;view.spread=0;selected=[];});notify('Локальные изменения восстановлены. Проверьте и сохраните.');}catch(e){notify(e.message,true);}};
$('#export-png').onclick=()=>{const active=canvas.getActiveObject();changing=true;canvas.discardActiveObject();const transform=canvas.viewportTransform.slice();canvas.setViewportTransform([2,0,0,2,0,0]);download(canvas.toDataURL({format:'png',left:0,top:0,width:840,height:560,multiplier:2}),'spread.png');canvas.setViewportTransform(transform);if(active)canvas.setActiveObject(active);changing=false;canvas.requestRenderAll();};
document.addEventListener('keydown',e=>{const editing=e.target.closest('input,textarea,select')||canvas.getActiveObject()?.isEditing;if(editing)return;const mod=e.metaKey||e.ctrlKey;if(mod&&e.key.toLowerCase()==='s'){e.preventDefault();save().catch(e=>notify(e.message,true));return;}if(mod&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo();return;}if(mod&&e.key.toLowerCase()==='d'){e.preventDefault();action('duplicate');return;}if(mod&&e.key.toLowerCase()==='c'){clipboard=clone(chosen());return;}if(mod&&e.key.toLowerCase()==='v'&&clipboard){e.preventDefault();commit(()=>{const p=page(),copies=clipboard.filter(l=>l.type!=='grid'||!p.layers.some(i=>i.type==='grid')).map(l=>({...clone(l),id:uid()}));p.layers.push(...copies);selected=copies.map(l=>l.id);if(copies.some(l=>l.type==='grid'))section().kind='flow';});return;}if(e.key===' '){e.preventDefault();space=true;canvas.skipTargetFind=true;return;}if(e.key==='Escape'){selected=[];canvas.discardActiveObject();$('.right-panel').classList.remove('mobile-open');setTool('select');renderInspector();return;}if(preview)return;if(['Delete','Backspace'].includes(e.key)){e.preventDefault();action('delete');return;}if(e.key.startsWith('Arrow')&&selected.length){e.preventDefault();const step=e.shiftKey?10:1;commit(()=>chosen().filter(l=>!l.locked).forEach(l=>{if(e.key==='ArrowLeft')l.box.x=clamp(l.box.x-step,0,210-l.box.w);if(e.key==='ArrowRight')l.box.x=clamp(l.box.x+step,0,210-l.box.w);if(e.key==='ArrowUp')l.box.y=clamp(l.box.y-step,0,280-l.box.h);if(e.key==='ArrowDown')l.box.y=clamp(l.box.y+step,0,280-l.box.h);}));return;}const tools={v:'select',h:'hand',t:'text',f:'photo',r:'rect',o:'ellipse',l:'line',g:'grid'};if(tools[e.key.toLowerCase()])setTool(tools[e.key.toLowerCase()]);});
document.addEventListener('keyup',e=>{if(e.key===' '){space=false;setTool(tool);}});window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
if(serverId)load(serverId);else location.replace('/static/master-catalog.html');
})();
