/* Chosen portraits, camera-original export and durable return from retouching. */
globalThis.Retouch=(()=>{
  let todoOnly=false,personFilter='all',report=null,busy=false,reportOrder=null;
  const chosen=(o=state.order)=>{const ids=new Set((o?.persons||[]).map(p=>p.selected_photo_id).filter(Boolean));return (o?.photos||[]).filter(p=>ids.has(p.id)&&p.status==='ready'&&p.shoot_type!=='general');};
  const scope=()=>state.view==='photos'?state.shootId:null;
  const list=()=>chosen().filter(p=>!scope()||p.shoot_id===scope()).filter(p=>!todoOnly||!p.retouch_version);
  const url=(p,variant='thumb')=>`/media/${p.id}/${variant}${p.retouch_version?'?v='+encodeURIComponent(p.retouch_version):''}`;
  const badge=p=>`<span class="pw-tile-badge${p.retouch_version?' retouched':''}">${svgIcon(p.retouch_version?'check':'star',11)}${p.retouch_version?'обработано':'выбор'}</span>`;
  function tools(){const all=chosen().filter(p=>!scope()||p.shoot_id===scope()),done=all.filter(p=>p.retouch_version).length;
    const editable=!['print','delivery','archive'].includes(state.order.stage);
    return `<section class="retouch-tools"><div class="retouch-progress"><b>Обработано ${done} из ${all.length}</b><progress value="${done}" max="${all.length||1}"></progress><button class="text-button" data-retouch="todo">${todoOnly?'Показать всех':'Показать необработанные · '+(all.length-done)}</button></div><button class="secondary" data-retouch="list" ${list().length?'':'disabled'}>${svgIcon('copy',15)}Список файлов</button><button class="secondary" data-retouch="archive" ${list().length?'':'disabled'}>${svgIcon('download',15)}Скачать оригиналы · ${list().length}</button></section>${editable?`<div class="retouch-drop${busy?' busy':''}" data-retouch-drop>${svgIcon('upload',22)}<div><strong>${busy?'Загружаем обработанные…':'Загрузить обработанные'}</strong><span>Перетащите фото сюда или <button class="text-button" data-retouch="upload" ${busy?'disabled':''}>выберите файлы</button>. Имя кадра, имя-Edit и имя-2 сопоставляются автоматически.</span>${state.order.stage==='approval'?'<small>Замена вернёт макет на проверку. Отправьте его на согласование заново.</small>':''}</div><input type="file" data-retouch-files multiple accept="image/jpeg,image/png,.jpg,.jpeg,.png" hidden ${busy?'disabled':''}></div>`:''}${reportHtml()}`;
  }
  function reportHtml(){if(!report||reportOrder!==state.order.id)return '';return `<section class="retouch-report" role="status"><header><b>Результат загрузки</b><button class="text-button" data-retouch="hide">Скрыть</button></header>${[['replaced','Заменено'],['not_chosen','Не выбраны'],['unknown','Без пары'],['ambiguous','Неоднозначное имя'],['error','Ошибки']].map(([key,label])=>{const items=report.filter(x=>x.status===key);return items.length?`<p><b>${label} · ${items.length}</b> ${items.map(x=>esc(x.filename)+(x.message?' — '+esc(x.message):'')).join(' · ')}</p>`:'';}).join('')}<p>Осталось обработать: ${chosen().filter(p=>!p.retouch_version).length}</p></section>`;}
  function personTools(){const people=state.order.persons,selected=people.filter(p=>p.selected_photo_id).length;return `<div class="filter-chips retouch-person-filters">${[['all','Все',people.length],['chosen','Выбрали',selected],['none','Не выбрали',people.length-selected]].map(([key,label,n])=>`<button class="filter-chip${personFilter===key?' active':''}" data-retouch-person="${key}" aria-pressed="${personFilter===key}">${label} <small>${n}</small></button>`).join('')}</div>${tools()}`;}
  const personVisible=p=>(personFilter==='all'||(personFilter==='none'?!p.selected_photo_id:!!p.selected_photo_id))&&(!todoOnly||personFilter==='none'||chosen().some(x=>x.id===p.selected_photo_id&&!x.retouch_version));
  function redraw(){if(state.view==='persons')renderGroups();else renderWorkspace();}
  function bind(){const zone=$('[data-retouch-drop]'),input=$('[data-retouch-files]');if(!zone)return;
    input.onchange=()=>{const files=[...input.files];input.value='';upload(files);};
    zone.ondragover=e=>{e.preventDefault();e.stopPropagation();zone.classList.add('dragging');};zone.ondragleave=e=>{e.stopPropagation();zone.classList.remove('dragging');};
    zone.ondrop=e=>{e.preventDefault();e.stopPropagation();zone.classList.remove('dragging');upload([...e.dataTransfer.files]);};
  }
  async function upload(files){if(busy||!files.length)return;const order=state.order.id,shoot=scope();busy=true;const results=[];report=results;reportOrder=order;redraw();
    try{for(const file of files){let result;try{result=await api(`/orders/${order}/retouched?filename=${encodeURIComponent(file.name)}${shoot?'&shoot_id='+encodeURIComponent(shoot):''}`,{method:'POST',headers:{'Content-Type':'application/octet-stream'},body:file});}catch(error){result={status:'error',filename:file.name,message:error.message};}results.push(result);}if(state.order?.id===order){await refreshOrder();toast('Обработанные загружены — результат под списком файлов');}}
    finally{busy=false;if(state.order?.id===order)redraw();}
  }
  function openFiles(){const names=list().map(p=>p.filename.replace(/\.[^.]+$/,'')).join(' ');$('#action-content').innerHTML=`<div class="dialog-heading"><h2>Список файлов · ${list().length}</h2><button class="close" data-close="action-dialog" aria-label="Закрыть">×</button></div><p>Lightroom Classic: фильтр «Текст → Имя файла → Содержит». Имена без расширения подходят и для RAW.</p><textarea class="retouch-names" readonly aria-label="Имена файлов">${esc(names)}</textarea><div class="dialog-actions"><button class="primary" data-retouch="copy">Скопировать</button></div>`;$('#action-dialog').showModal();}
  function openArchive(){const params=new URLSearchParams({todo:String(todoOnly),names:'true'});if(scope())params.set('shoot_id',scope());const base=`/api/orders/${state.order.id}/chosen/archive?`;$('#action-content').innerHTML=`<div class="dialog-heading"><h2>Скачать оригиналы · ${list().length}</h2><button class="close" data-close="action-dialog" aria-label="Закрыть">×</button></div><p>Один архив с исходными файлами камеры.</p><label>Имена файлов<select data-retouch-archive-name><option value="true">Имя ученика — имя кадра.jpg</option><option value="false">Как в камере</option></select></label><div class="dialog-actions"><a class="primary" data-retouch-download href="${base}${params}">Скачать ZIP</a></div>`;$('#action-dialog').showModal();$('[data-retouch-archive-name]').onchange=e=>{params.set('names',e.target.value);$('[data-retouch-download]').href=base+params;};}
  function plate(o){const r=o.retouch;if(r?.mode!=='retouch'||!['forms','layout','approval'].includes(o.stage))return '';return `<div class="retouch-plate"><div><b>Обработка портретов · ${r.done} из ${r.total}</b><small>${r.done===r.total?'Все выбранные обработаны':'Обработанные фото встают на свои места в макете'}</small></div><progress value="${r.done}" max="${r.total||1}"></progress><button class="secondary" data-retouch="open">Открыть</button></div>`;}
  async function showChosen(){todoOnly=true;personFilter='all';state.selected.clear();if(state.view==='persons'){renderGroups();return;}state.shootId=state.order.shoots.find(s=>s.kind==='portrait')?.id;state.photoFilter='chosen';if(state.view==='photos')renderWorkspace();else location.hash=`order/${state.order.id}/photos?chosen=1`;}
  function publish(){const o=state.order,r=o.retouch,left=r?.mode==='retouch'?r.remaining||[]:[];
    const send=async allow=>{await api(`/orders/${o.id}/layout/publish${allow?'?allow_unretouched=true':''}`,json('POST',{}));await refreshOrder();toast('Макет отправлен классу');};
    if(!left.length){confirmStep('Отправить макет на согласование?','Класс увидит макет по своей ссылке. Ответственный согласует его вместе с количеством альбомов и получением.','Отправить',()=>send(false));return;}
    $('#action-content').innerHTML=`<div class="dialog-heading"><h2>Отправить на согласование</h2><button class="close" data-close="action-dialog" aria-label="Закрыть">×</button></div><p>Не обработано ${left.length} из ${r.total}: ${left.slice(0,8).map(p=>esc(p.name||p.filename)).join(', ')}. Класс согласует фотографии, которые пойдут в печать.</p><p class="error" role="alert"></p><div class="dialog-actions"><button class="secondary" data-retouch="wait">Дождаться обработки</button><button class="primary" data-retouch-send>Отправить эти без обработки</button></div>`;$('#action-dialog').showModal();$('[data-retouch-send]').onclick=async e=>{e.target.disabled=true;try{await send(true);$('#action-dialog').close();}catch(error){$('#action-content .error').textContent=error.message;e.target.disabled=false;}};
  }
  document.addEventListener('click',async e=>{const filter=e.target.closest('[data-retouch-person]');if(filter){personFilter=filter.dataset.retouchPerson;state.selected.clear();renderGroups();return;}const b=e.target.closest('[data-retouch]');if(!b)return;const action=b.dataset.retouch;
    if(action==='todo'){todoOnly=!todoOnly;state.selected.clear();redraw();}if(action==='hide'){report=null;redraw();}if(action==='upload')$('[data-retouch-files]')?.click();if(action==='list')openFiles();if(action==='archive')openArchive();if(action==='wait'){$('#action-dialog').close();showChosen();}if(action==='open')showChosen();if(action==='copy'){try{await navigator.clipboard.writeText($('.retouch-names').value);toast('Имена файлов скопированы');}catch{$('.retouch-names').select();toast('Выделены имена — нажмите Ctrl+C или ⌘C');}}});
  function reset(){todoOnly=false;personFilter='all';report=null;}
  return {chosen,list,url,badge,tools,personTools,personVisible,bind,plate,publish,reset};
})();
