const state={orders:[],order:null,tab:'persons',selected:new Set(),person:null,uploading:false,progress:null,query:'',period:'all',filter:'all',attention:false,view:'photos',photoFilter:'all',shootId:undefined};
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icon=name=>`<img src="/static/assets/${name}.svg" alt="">`;
const money=n=>new Intl.NumberFormat('ru-RU',{maximumFractionDigits:0}).format(n)+' ₽';
const count=(n,one,few,many)=>`${n} ${n%10===1&&n%100!==11?one:n%10>=2&&n%10<=4&&(n%100<12||n%100>14)?few:many}`;
const photoLabel=n=>count(n,'фотография','фотографии','фотографий');
const statuses={pending:'В очереди',processing:'Обработка',no_face:'Лицо не найдено',multiple_faces:'Несколько лиц',small_face:'Лицо слишком маленькое',error:'Ошибка обработки',ready:'Готово'};
const stages=[['planned','Назначить съёмку','#7712b3'],['scheduled','Съёмка назначена','#5073f2'],['upload','Загрузить фотографии','#50b7f1'],['layout','Сверстать макет','#28cec5']];
let toastTimer,pollTimer,routeVersion=0,groupsSig='';
async function api(path,options={}){const r=await fetch('/api'+path,options);let value=await r.json();if(!r.ok)throw Error(typeof value.detail==='string'?value.detail:'Проверьте заполнение полей');return value;}
function json(method,body){return {method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)};}
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),4500);}
function orderName(o){return `${o.school} / ${o.class_name}`;}
function personName(p,index){return p.name||`Персона ${String(index+1).padStart(2,'0')}`;}
function openNew(){ $('#order-form').reset();$('#form-error').textContent='';$('#order-dialog').showModal(); }
function taskButton(label,action){return `<button data-action="${action}">${icon('upload')}<span>${label}</span></button>`;}
function home(){const attention=state.orders.filter(o=>stats(o).review||(!stats(o).pending&&stats(o).total));$('#main').innerHTML=`<div class="page"><div class="eyebrow">РАБОЧЕЕ ПРОСТРАНСТВО</div><div class="page-heading"><div><h1>Главная</h1><p class="muted">Всё, что нужно для следующего шага.</p></div><button class="primary" data-action="new-order">＋ Создать заказ</button></div><div class="overview"><a href="#orders"><strong>${state.orders.length}</strong><span>Всего заказов →</span></a><a href="#photos"><strong>${state.orders.filter(o=>stats(o).pending).length}</strong><span>Обрабатываются</span></a><button data-v2="attention"><strong>${attention.length}</strong><span>Требуют внимания →</span></button></div><div class="section-head"><h2>Последние заказы</h2><a href="#orders" class="text-button">Все заказы →</a></div><div class="orders-grid">${state.orders.slice(0,6).map(orderCard).join('')||emptyOrders()}</div></div>`;}
function board(){const filtered=state.orders.filter(o=>orderName(o).toLowerCase().includes(state.query.toLowerCase()));$('#board').innerHTML=stages.map(([stage,title,color])=>{const orders=filtered.filter(o=>o.stage===stage);return `<section class="column" style="--stage:${color}"><h3>${title}<small>${orders.length}</small></h3><div class="column-body">${orders.map(o=>`<button class="order-card" data-order="${o.id}"><div class="order-card-top"><span>${esc(orderName(o))}</span>${icon('edit')}</div><small>${o.photo_count?photoLabel(o.photo_count)+' · '+count(o.person_count,'персона','персоны','персон'):count(o.copies,'альбом','альбома','альбомов')}${o.pending?' · Обработка':''}</small></button>`).join('')||`<div class="column-empty">${state.query?'Ничего не найдено':stage==='planned'?'Здесь появятся новые заказы':stage==='scheduled'?'Заказы с назначенной датой съёмки':stage==='upload'?'Заказы с загруженными фотографиями':'Подготовка макетов — следующий этап'}${stage==='planned'&&!state.query?'<button data-action="new-order">＋ Создать заказ</button>':''}</div>`}</div></section>`;}).join('');}
function chooseOrders(mode){const title=mode==='photos'?'Загрузка фотографий':mode==='client'?'Сбор данных':'Все заказы';$('#main').innerHTML=`<div class="page"><div class="eyebrow">РАБОЧЕЕ ПРОСТРАНСТВО / ЗАКАЗЫ</div><div class="page-heading"><div><h1>${title} <span class="heading-count">${state.orders.length}</span></h1><p class="muted">От первой фотографии до готового альбома.</p></div><button class="primary" data-action="new-order">＋ Создать заказ</button></div><div class="orders-toolbar"><input id="search" type="search" placeholder="Поиск по школе или классу" aria-label="Поиск заказов" value="${esc(state.query)}"><button data-v2="toggle-attention" class="filter-attention ${state.attention?'active':''}">Требуют внимания <b>${state.orders.filter(o=>stats(o).review||(!stats(o).pending&&stats(o).total)).length}</b></button></div><div class="filter-tabs" aria-label="Статус заказов">${[['all','Все'],['empty','Нужно загрузить'],['processing','Обрабатываются'],['review','Нужна проверка'],['ready','Готовы к отправке'],['client_waiting','Ожидаем клиента'],['client_filling','Заполняются'],['client_complete','Заполнены']].map(([key,label])=>`<button data-filter="${key}" class="${state.filter===key?'active':''}" aria-pressed="${state.filter===key}">${label} <small>${state.orders.filter(o=>matchesFilter(o,key)).length}</small></button>`).join('')}</div><div id="order-results" aria-live="polite"></div></div>`;drawOrders();$('#search').oninput=e=>{state.query=e.target.value;drawOrders();};}
function orderPage(){const o=state.order,s=stats(o);$('#main').innerHTML=`<div class="page"><div class="eyebrow"><a href="#orders">Все заказы</a> / ${esc(orderName(o))}</div><div class="page-heading"><div><h1>${esc(orderName(o))}</h1><p class="muted">${count(o.copies,'альбом','альбома','альбомов')}${o.shoot_date?' · Съёмка '+esc(o.shoot_date.split('-').reverse().join('.')):''}</p></div><button class="secondary" data-v2="order-menu" data-id="${o.id}" aria-label="Действия с заказом">⋯</button></div><div class="flow-track"><b>01 <span>Загрузка фотографий</span></b><span>02 Сбор данных</span><span>03 Макет</span><span>04 Печать</span><span>05 Доставка</span></div><div id="order-status" aria-live="polite"></div><div class="workspace-tabs" role="navigation" aria-label="Разделы заказа">${[['photos','Загрузка фотографий',s.total],['persons','Персоны',o.persons.length],['client','Сбор данных',''],['layout','Макет','']].map(([key,label,n])=>`<a href="#order/${o.id}/${key}" class="${state.view===key?'active':''}" ${state.view===key?'aria-current="page"':''}>${label}${n!==''?` <small>${n}</small>`:''}</a>`).join('')}</div><section id="workspace"></section><p class="model-note">Локальная версия · Заказы и фотографии общие с V1. Обработка продолжается при открытом сервере; закрытие приложения или сон компьютера её приостанавливает.</p></div>`;syncSummary(o);renderWorkspace();}
function renderGroups(){if(!$('#groups'))return;const o=state.order,unassigned=o.photos.filter(needsReview),pending=o.photos.filter(p=>['pending','processing'].includes(p.status)).length;$('#groups').innerHTML=`<div class="section-head"><h2>Персоны <span class="muted">${o.persons.length}</span></h2><div class="tabs"><button data-tab="persons" class="${state.tab==='persons'?'active':''}">По персонам</button><button data-tab="review" class="${state.tab==='review'?'active':''}">Проверить · ${unassigned.length}</button></div></div>${state.tab==='persons'?`<div class="person-grid">${o.persons.map((p,i)=>{const photos=o.photos.filter(f=>f.person_id===p.id);if(!photos.length)return '';return `<button class="person-card" data-person="${p.id}"><img src="/media/${photos[0].id}/thumb" alt="${esc(personName(p,i))}" loading="lazy" decoding="async">${photos.some(f=>f.uncertain)?'<span class="badge">Проверьте совпадение</span>':''}<div class="person-caption"><h3>${esc(personName(p,i))}</h3><p>${photoLabel(photos.length)}</p></div></button>`;}).join('')}</div>${!o.persons.length?`<div class="empty-state"><h3>${pending?'Ищем лица на фотографиях':'Персоны появятся здесь'}</h3><p>${pending?'Обработка идёт на компьютере. Можно продолжить загрузку.':unassigned.length?'Откройте «Проверить»: некоторым фотографиям нужна ваша помощь.':'Загрузите портреты — система соберёт снимки одного человека в группу.'}</p></div>`:''}`:`${unassigned.some(p=>p.status==='error')?'<div class="warning">Некоторые снимки не удалось обработать. <button class="link-button" data-action="retry">Повторить обработку</button></div>':''}${unassigned.length?`<p class="muted small confirmation-help">Сравните фото с указанной персоной и подтвердите верные совпадения. Остальные назначьте вручную или удалите.</p><div class="selection-bar"><span id="review-selected">Выбрано: ${state.selected.size}</span><button class="primary" data-v2="confirm-photos" disabled>Подтвердить совпадения</button><button class="text-button" data-v2="select-matches">Выделить совпадения</button><button class="secondary" data-action="move">Другая персона</button><button class="danger-button" data-v2="delete-photos">Удалить</button></div><div class="photo-grid">${unassigned.map(p=>photoTile(p,true)).join('')}</div>`:'<div class="empty-state"><h3>Нет фотографий для проверки</h3><p>Кадры без лица и с несколькими лицами появятся здесь.</p></div>'}`}`;groupsSig=orderSignature(o);syncConfirmation();}
function photoTile(p,review=false){return `<label class="photo-tile"><img src="/media/${p.id}/thumb" alt="${esc(p.filename)}" loading="lazy" decoding="async"><input type="checkbox" data-photo="${p.id}" aria-label="Выбрать ${esc(p.filename)}" ${state.selected.has(p.id)?'checked':''}><p title="${esc(p.filename)}">${esc(p.filename)}</p>${review?matchCaption(p):''}${review&&p.uncertain?'<small>Проверьте совпадение</small>':p.status!=='ready'?`<small>${statuses[p.status]||'Проверить'}</small>`:review?'<small class="photo-ready">Готово</small>':''}</label>`;}
function orderSignature(o){return JSON.stringify(o.shoots||[])+'|'+state.tab+'|'+o.persons.map(p=>p.id+':'+p.name).join(',')+'|'+o.photos.map(p=>[p.id,p.status,p.person_id||'',p.uncertain?1:0,p.error||'',p.filename].join(':')).join(';');}
function syncSummary(o){const el=$('#order-status');if(!el)return;const s=stats(o),info=statusInfo(o);let eta='Оцениваем оставшееся время…';if(o.processing?.eta_seconds!=null){const seconds=o.processing.eta_seconds;eta=seconds<60?'Осталось меньше минуты':`Осталось примерно ${Math.max(1,Math.floor(seconds/60*.8))}–${Math.max(2,Math.ceil(seconds/60*1.2))} мин`; }el.innerHTML=`${o.client_progress?.enabled?clientProgress(o):''}<div class="status-panel ${info.kind}"><div><span class="status-label">${info.label}</span><p>${s.pending?`Обработано ${s.total-s.pending} из ${s.total} · ${eta}`:s.review?`${s.review} снимков требуют проверки. Остальные фотографии сохранены.`:o.client_progress?.enabled?`Заполнено ${o.client_progress.completed} из ${o.client_progress.total}. ${o.client_progress.remaining?'Осталось: '+o.client_progress.remaining+'.':'Портреты и подписи сохранены.'}`:s.total?'Фотографии сохранены. Можно открыть нужную съёмку.':'Добавьте съёмку и загрузите фотографии.'}</p>${s.pending?`<progress max="${s.total}" value="${s.total-s.pending}"></progress>`:''}</div>${s.review?`<a class="secondary" href="#order/${o.id}/review">Проверить снимки →</a>`:!s.total?'<button class="primary" data-v2="add-photos">Загрузить фотографии</button>':!s.pending?`<a class="primary" href="#order/${o.id}/client">Отправить клиентам →</a>`:''}</div>`;}
function startOrderPolling(){clearInterval(pollTimer);pollTimer=setInterval(()=>{if(document.hidden)return;refreshOrder().catch(e=>{toast('Не удалось обновить обработку: '+e.message);});},5000);}
function renderProgress(){const el=$('#upload-status');if(!el)return;const p=state.progress;if(!p||p.orderId!==state.order?.id){el.innerHTML='';return;}el.innerHTML=`<progress max="${p.total}" value="${p.done}"></progress><strong>${state.uploading?'Загружаем':'Загрузка завершена'}: принято ${p.done-p.duplicates-p.errors.length} из ${p.total}</strong><p class="small muted">${p.duplicates?'Уже загружены: '+p.duplicates+' · ':''}Не загружено: ${p.errors.length}${state.uploading?' · Осталось: '+(p.total-p.done):''}</p>${p.errors.length?`<details class="upload-error"><summary>Показать ошибки (${p.errors.length})</summary>${p.errors.map(esc).join('<br>')}</details>`:''}`;}
async function uploadFiles(files){if(state.uploading){toast('Дождитесь завершения текущей загрузки');return;}if(!files.length)return;const orderId=state.order.id,shootId=state.shootId,shoot=state.order.shoots.find(s=>s.id===shootId);if(!shoot){openShootDialog(files);return;}const allowed=f=>{const type=(f.type||'').toLowerCase();const name=f.name.toLowerCase();return ['image/jpeg','image/jpg','image/pjpeg','image/png','image/x-png'].includes(type)||/\.(jpe?g|png)$/.test(name);};state.uploading=true;state.progress={orderId,total:files.length,done:0,duplicates:0,errors:[]};renderProgress();startOrderPolling();const queue=[...files];const concurrency=Math.min(6,queue.length);const worker=async()=>{while(queue.length){const file=queue.shift();try{if(!allowed(file))throw Error('Нужен файл JPG, JPEG или PNG');if(file.size>30*1024*1024)throw Error('Файл больше 30 МБ');const r=await api(`/orders/${orderId}/photos?shoot_id=${encodeURIComponent(shootId)}&filename=${encodeURIComponent(file.name)}`,{method:'POST',headers:{'Content-Type':'application/octet-stream'},body:file});if(r.duplicate)state.progress.duplicates++;}catch(e){state.progress.errors.push(file.name+': '+e.message);}state.progress.done++;renderProgress();}};await Promise.all(Array.from({length:concurrency},()=>worker()));state.uploading=false;renderProgress();toast(state.progress.errors.length?'Загрузка завершена с ошибками — проверьте список':shoot.kind==='portrait'?'Фотографии загружены. Группируем по персонам.':'Фотографии добавлены в съёмку.');if(state.order?.id===orderId){await refreshOrder();startOrderPolling();}}
function showPerson(id){const o=state.order,index=o.persons.findIndex(p=>p.id===id),person=o.persons[index];if(!person)return;state.person=id;state.selected.clear();const photos=o.photos.filter(p=>p.person_id===id);$('#person-content').innerHTML=`<div class="dialog-heading"><h2 id="person-title">${esc(personName(person,index))}</h2><button class="close" data-close="person-dialog" aria-label="Закрыть">×</button></div><form id="name-form" class="name-form"><input name="name" placeholder="Имя и фамилия" aria-label="Имя персоны" maxlength="100" value="${esc(person.name)}"><button class="secondary" type="submit">Сохранить имя</button></form><p class="muted small">${photoLabel(photos.length)}. Выберите снимки, чтобы перенести их в другую группу или выделить в новую персону.</p><div class="selection-bar"><span id="person-selected">Выбрано: 0</span><button class="text-button" data-action="select-all">Выбрать все</button><button class="secondary" data-action="move">Другая персона</button><button class="danger-button" data-v2="delete-photos">Удалить</button></div><div class="photo-grid">${photos.map(p=>photoTile(p)).join('')}</div>`;$('#name-form').onsubmit=async e=>{e.preventDefault();try{await api(`/orders/${o.id}/persons/${id}`,json('PATCH',{name:new FormData(e.target).get('name')}));await refreshOrder();const name=state.order.persons.find(p=>p.id===id)?.name;$('#person-title').textContent=name||personName(person,index);toast('Имя сохранено');}catch(e){toast(e.message);}};if(!$('#person-dialog').open)$('#person-dialog').showModal();}
function openMove(){if(!state.selected.size){toast('Сначала выберите фотографии');return;}showPersonPicker({order:state.order,selected:[...state.selected],api,esc,personName});$('#move-dialog').showModal();}
async function refreshOrder(){const id=state.order?.id;if(!id)return;const fresh=await api('/orders/'+id);if(state.order?.id!==id)return;const previous=state.order;state.order=fresh;state.selected=new Set([...state.selected].filter(id=>fresh.photos.some(p=>p.id===id)));if(orderSignature(previous)!==orderSignature(fresh)){if(state.view==='persons')renderGroups();else if(state.view==='photos')renderWorkspace();document.querySelectorAll('.workspace-tabs a').forEach(a=>{if(a.href.endsWith('/photos'))a.innerHTML=`Загрузка фотографий <small>${fresh.photos.length}</small>`;if(a.href.endsWith('/persons'))a.innerHTML=`Персоны <small>${fresh.persons.length}</small>`;});}syncSummary(fresh);syncConfirmation();if($('#client-fill-progress'))$('#client-fill-progress').innerHTML=clientProgress(fresh,true);}
async function route(){const version=++routeVersion;clearInterval(pollTimer);pollTimer=null;state.selected.clear();state.person=null;const hash=location.hash.slice(1)||'orders';try{state.orders=await api('/orders');if(version!==routeVersion)return;if(hash.startsWith('order/')){const [,id,view='photos']=hash.split('/');const order=await api('/orders/'+encodeURIComponent(id));if(version!==routeVersion)return;if(state.order?.id!==order.id)state.shootId=undefined;state.order=order;state.view=['photos','persons','client','layout','review'].includes(view)?view:'photos';state.photoFilter=view==='review'?'review':'all';if(state.view==='review'){state.view='photos';state.shootId=undefined;}orderPage();startOrderPolling();}else{state.order=null;if(hash==='home')home();else if(hash==='orders'||hash==='photos')chooseOrders(hash);else futurePage(['client','layout','ready','print','delivery','archive'].includes(hash)?hash:'client');pollTimer=setInterval(async()=>{if(document.hidden||state.order)return;try{const fresh=await api('/orders');if(version!==routeVersion)return;if(JSON.stringify(fresh)!==JSON.stringify(state.orders)){state.orders=fresh;nav();if(hash==='home')home();else if($('#order-results')){const focused=document.activeElement=== $('#search'),pos=$('#search')?.selectionStart;chooseOrders(hash);if(focused){$('#search').focus();if($('#search').type!=='search')$('#search').setSelectionRange(pos,pos);}}}}catch(error){toast('Не удалось обновить заказы: '+error.message);}},5000);}nav();}catch(e){$('#main').innerHTML=`<div class="page"><h1>Не удалось открыть страницу</h1><p class="error">${esc(e.message)}</p><a href="#orders" class="secondary">К заказам</a></div>`;}}
function needsReview(p){return p.shoot_type!=='general'&&!['pending','processing'].includes(p.status)&&(p.status!=='ready'||p.uncertain||!p.person_id);}
function stats(o){const photos=o.photos;return {total:photos?photos.length:o.photo_count||0,pending:photos?photos.filter(p=>['pending','processing'].includes(p.status)).length:o.pending||0,review:photos?photos.filter(needsReview).length:o.review_count||0};}
function phase(o){const s=stats(o);if(o.stage==='layout')return 'layout';return o.client_progress?.enabled&&!s.pending?'client':'photos';}
function statusInfo(o){const s=stats(o);if(o.stage==='layout')return {label:'Подготовка макета',kind:'neutral',action:'Открыть заказ',tab:'layout'};if(!s.total)return {label:'Нужно загрузить',kind:'neutral',action:'Загрузить портреты',tab:'photos'};if(s.pending)return {label:'Обрабатываются',kind:'working',action:'Открыть фотографии',tab:'photos'};if(o.client_progress?.enabled){const c=o.client_progress;return {label:c.label,kind:c.status==='complete'?'ready':'working',action:c.status==='complete'?'Посмотреть заполнение':'Следить за заполнением',tab:'client'};}if(s.review)return {label:'Нужна проверка',kind:'attention',action:`Проверить · ${s.review}`,tab:'review'};return {label:'Готовы к отправке',kind:'ready',action:'Отправить клиентам',tab:'client'};}
function nav(){const current=location.hash.slice(1)||'orders';const active=current.startsWith('order/')?'orders':current;const entries=[['home','home','Главная'],['orders','portraits','Все заказы'],['photos','upload','Загрузка фотографий'],['client','account','Сбор данных'],['layout','layout','Подготовка макета'],['ready','ready','Готовые макеты'],['print','print','Печать'],['delivery','delivery','Доставка'],['archive','archive','Архив']];$('#v2-nav').innerHTML=entries.map(([key,ico,label],i)=>`${i===2?'<div class="nav-caption">ПО ЭТАПАМ</div>':''}<a href="#${key}" class="${active===key?'active':''}" ${active===key?'aria-current="page"':''}>${icon(ico)}<span>${label}</span>${['home'].includes(key)?'':key==='orders'?`<small>${state.orders.length}</small>`:key==='client'?'':key==='photos'?`<small>${state.orders.filter(o=>phase(o)==='photos').length}</small>`:`<small class="soon">Скоро</small>`}</a>`).join('');$('#version-v1').href=state.order?'/#order/'+state.order.id:'/';}
function emptyOrders(){return '<div class="empty-state"><h3>Начните с первого заказа</h3><p>Создайте класс, загрузите портреты и проверьте группы персон.</p><button class="primary" data-action="new-order">Создать заказ</button></div>';}
function orderCard(o){const s=stats(o),info=statusInfo(o);return `<article class="visual-order"><a class="cover" href="#order/${o.id}/${info.tab}" aria-label="Открыть ${esc(orderName(o))}">${o.cover_id?`<img src="/media/${o.cover_id}/thumb" alt="Обложка ${esc(orderName(o))}" loading="lazy">`:`<div class="cover-placeholder"><span>ALBUM FACTORY</span><strong>${esc(o.class_name)}</strong><small>${esc(o.school)}</small></div>`}<span class="status-badge ${info.kind}">${info.label}</span></a><div class="card-body"><a href="#order/${o.id}/photos"><h2>${esc(orderName(o))}</h2></a><p class="card-meta">${count(o.copies,'альбом','альбома','альбомов')}<span>·</span>${o.shoot_date?esc(o.shoot_date.split('-').reverse().join('.')):'Дата не назначена'}</p><div class="card-progress">${o.client_progress?.enabled?clientProgress(o):''}${s.pending?`<div><span>Обработано ${s.total-s.pending} из ${s.total}</span><b>${Math.round((s.total-s.pending)/s.total*100)}%</b></div><progress max="${s.total}" value="${s.total-s.pending}"></progress>`:s.review?`<span class="attention-text">${s.review} снимков требуют проверки</span>`:s.total?`<span>${photoLabel(s.total)} · ${o.person_count??o.persons?.length??0} персон</span>`:'<span>Загрузите портреты, чтобы начать</span>'}</div><div class="card-footer"><a class="card-action" href="#order/${o.id}/${info.tab}">${info.action}<span>↗</span></a><button class="card-menu" data-v2="order-menu" data-id="${o.id}" aria-label="Действия с заказом ${esc(orderName(o))}">⋯</button></div></div></article>`;}
function matchesFilter(o,key){const s=stats(o),c=o.client_progress;return key==='all'||key==='empty'&&!s.total||key==='processing'&&s.pending>0||key==='review'&&s.review>0||key==='ready'&&s.total>0&&!s.pending&&!s.review&&!c?.enabled||key==='client_waiting'&&c?.status==='waiting'||key==='client_filling'&&c?.status==='in_progress'||key==='client_complete'&&c?.status==='complete';}
function drawOrders(){const items=state.orders.filter(o=>(!state.attention||stats(o).review||(!stats(o).pending&&stats(o).total))&&matchesFilter(o,state.filter)&&orderName(o).toLowerCase().includes(state.query.toLowerCase())&&((location.hash!=='#photos')||phase(o)==='photos')&&((location.hash!=='#client')||o.client_progress?.enabled));$('#order-results').innerHTML=`<div class="results-caption">${count(items.length,'заказ','заказа','заказов')}</div><div class="orders-grid">${items.map(orderCard).join('')||(!state.orders.length?emptyOrders():'<div class="empty-state"><h3>Заказы не найдены</h3><p>Измените запрос или сбросьте фильтры.</p><button class="secondary" data-v2="reset-filters">Сбросить фильтры</button></div>')}</div>`;}
function futurePage(key){if(key==='client'){chooseOrders('client');return;}const labels={client:'Сбор данных',layout:'Подготовка макета',ready:'Готовые макеты',print:'Печать',delivery:'Доставка',archive:'Архив'};$('#main').innerHTML=`<div class="page"><div class="eyebrow"><a href="#orders">Все заказы</a> / По этапам</div><h1>${labels[key]}</h1><div class="future-state"><span class="status-badge neutral">Следующий этап</span><h2>Здесь будут заказы на этапе «${labels[key]}»</h2><p>Раздел сохранён в рабочем процессе. ${key==='client'?'Клиентский кабинет и публикация фотографий ещё не подключены.':'Работа с этим этапом пока недоступна.'}</p><a href="#orders" class="secondary">Вернуться к заказам →</a></div></div>`;}
function renderWorkspace(){const o=state.order;if(state.view==='persons'){$('#workspace').innerHTML='<div id="groups"></div>';state.tab='persons';renderGroups();return;}if(state.view==='client'||state.view==='layout'){$('#workspace').innerHTML=state.view==='client'?`<div class="future-state"><span class="status-badge neutral">Личный кабинет</span><h2>Сбор данных</h2><div id="client-fill-progress">${clientProgress(o,true)}</div><p>Клиент увидит персоны этого заказа, выберет фотографии и заполнит имя, фамилию и цитату. Выбор сохраняется на сервере.</p><button class="primary" data-v2="open-client">Отправить клиентам →</button><p class="muted small">Локальная версия: ссылка работает на этом компьютере. Для доступа клиентов из интернета потребуется размещение сервиса.</p><a class="text-button" href="#order/${o.id}/persons">Проверить персоны →</a></div>`:'<div class="future-state"><span class="status-badge neutral">Скоро</span><h2>Подготовка макета</h2><p>Здесь появится работа с макетом после выбора фотографий клиентом.</p></div>';return;}const shoots=o.shoots||[];if(state.shootId===undefined||state.shootId&&!shoots.some(s=>s.id===state.shootId)){state.shootId=(state.photoFilter==='review'?shoots.find(s=>o.photos.some(p=>p.shoot_id===s.id&&needsReview(p))):null)?.id||shoots[0]?.id||null;}$('#workspace').innerHTML=`<div class="section-head"><h2>Съёмки <span class="muted">${shoots.length||''}</span></h2><button class="secondary" data-v2="new-shoot">＋ Добавить съёмку</button></div>${shoots.length?shoots.map(shoot=>`<section class="shoot-section ${state.shootId===shoot.id?'expanded':''}"><button class="shoot-heading" data-v2="toggle-shoot" data-id="${shoot.id}" aria-expanded="${state.shootId===shoot.id}" aria-controls="shoot-${shoot.id}"><span class="shoot-chevron" aria-hidden="true">${state.shootId===shoot.id?'⌄':'›'}</span><strong>${esc(shoot.title)}</strong><span class="muted">${shoot.kind==='portrait'?'Портретная':'Общая'} · ${photoLabel(o.photos.filter(p=>p.shoot_id===shoot.id).length)}</span>${shootStatus(shoot)}</button></section>`).join('')+shoots.map(shoot=>`<div class="shoot-content" id="shoot-${shoot.id}" ${state.shootId!==shoot.id?'hidden':''}>${state.shootId===shoot.id?shootBody(shoot):''}</div>`).join(''):'<div class="empty-state"><h3>Добавьте первую съёмку</h3><p>Портретная или общая — в заказе может быть одна съёмка или несколько.</p><button class="primary" data-v2="new-shoot">Добавить съёмку</button></div>'}`;if(!$('#choose-files'))return;$('#choose-files').onclick=()=>$('#files').click();$('#files').onchange=e=>uploadFiles([...e.target.files]);const drop=$('#dropzone');drop.ondragover=e=>{e.preventDefault();drop.classList.add('drag');};drop.ondragleave=()=>drop.classList.remove('drag');drop.ondrop=e=>{e.preventDefault();drop.classList.remove('drag');uploadFiles([...e.dataTransfer.files]);};renderProgress();renderPhotos();}
function shootBody(shoot){const o=state.order,shootPhotos=o.photos.filter(p=>p.shoot_id===shoot.id);return `<section class="panel upload-panel ${o.photos.length?'compact':''}"><div class="dropzone" id="dropzone">${icon('upload')}<div><h3>Добавить фотографии</h3><p>Перетащите файлы сюда · JPG, PNG · до 30 МБ</p><small>В заказе ${o.photos.length} из ${o.max_photos??3000} · свободно ${Math.max(0,(o.max_photos??3000)-o.photos.length)}</small></div><button class="primary" id="choose-files">Выбрать фотографии</button><input id="files" class="file-input" type="file" accept="image/jpeg,image/png,.jpg,.jpeg,.png" multiple aria-label="Выбрать фотографии"></div><div id="upload-status" class="upload-status" aria-live="polite"></div></section><div class="section-head"><h2>${esc(shoot.title)} <span class="muted">${shootPhotos.length}</span></h2><div class="filter-tabs photo-filters">${(shoot.kind==='portrait'?[['all','Все'],['pending','В обработке'],['review','Проверить'],['error','Ошибки']]:[['all','Все']]).map(([key,label])=>`<button data-photo-filter="${key}" class="${state.photoFilter===key?'active':''}" aria-pressed="${state.photoFilter===key}">${label}</button>`).join('')}</div></div><div class="selection-bar photo-actions"><span id="review-selected">Выбрано: ${state.selected.size}</span><button class="text-button" data-v2="select-visible">Выбрать все</button>${state.photoFilter==='review'?`<button class="primary" data-v2="confirm-photos" disabled>Подтвердить совпадения</button><button class="text-button" data-v2="select-matches">Выделить совпадения</button>`:''}${shoot.kind==='portrait'?'<button class="secondary" data-action="move">Другая персона</button>':''}<button class="secondary" data-v2="set-cover">На обложку</button><button class="danger-button" data-v2="delete-photos">Удалить</button></div>${state.photoFilter==='review'?'<p class="muted small confirmation-help">Сравните снимки с указанными персонами и подтвердите верные совпадения.</p>':''}${shoot.kind==='general'?'<p class="muted small">Общая съёмка · без автоматической сортировки по персонам</p>':''}<div id="photo-results"></div>`;}
function visiblePhotos(){return state.order.photos.filter(p=>p.shoot_id===state.shootId).filter(p=>state.photoFilter==='all'||state.photoFilter==='pending'&&['pending','processing'].includes(p.status)||state.photoFilter==='review'&&needsReview(p)||state.photoFilter==='error'&&p.status==='error');}
function renderPhotos(){const el=$('#photo-results');if(!el)return;const photos=visiblePhotos();el.innerHTML=`${photos.some(p=>p.status==='error')?'<div class="warning">Не удалось обработать часть снимков. <button class="link-button" data-action="retry">Повторить обработку</button></div>':''}<div class="photo-grid">${photos.map(p=>photoTile(p,state.photoFilter==='review')).join('')}</div>${!photos.length?`<div class="empty-state"><h3>${state.order.photos.length?'Здесь нет фотографий':'Фотографии появятся здесь'}</h3><p>${state.order.photos.length?'Выберите другой фильтр.':'Добавьте фотографии с помощью кнопки или перетащите их в область загрузки.'}</p></div>`:''}`;}
function showOrderMenu(id){const o=state.orders.find(o=>o.id===id)||state.order;state.menuOrder=o;$('#action-content').innerHTML=`<div class="dialog-heading"><h2>${esc(orderName(o))}</h2><button class="close" data-close="action-dialog" aria-label="Закрыть">×</button></div><div class="menu-options"><a class="secondary" href="#order/${id}/photos" data-v2="close-actions">Открыть фотографии →</a><a class="secondary" href="#order/${id}/persons" data-v2="close-actions">Открыть персоны →</a><button class="danger-button" data-v2="delete-order">Удалить заказ</button></div>`;$('#action-dialog').showModal();}
function confirmRemoval(kind){const o=kind==='order'?state.menuOrder:state.order;const ids=[...state.selected];if(kind==='photos'&&!ids.length){toast('Сначала выберите фотографии');return;}state.removal={kind,orderId:o.id,ids};$('#action-content').innerHTML=`<div class="dialog-heading"><h2>${kind==='order'?'Удалить заказ?':'Удалить фотографии?'}</h2><button class="close" data-close="action-dialog" aria-label="Закрыть">×</button></div><p class="muted">${kind==='order'?`Заказ «${esc(orderName(o))}», все его фотографии и персоны будут удалены.`:`Будут удалены выбранные фотографии (${ids.length}), оригиналы и превью.`} Это действие нельзя отменить. Изменения будут видны и в V1.</p>${kind==='order'?`<label>Введите название заказа для подтверждения<input id="delete-name" autocomplete="off" placeholder="${esc(orderName(o))}"></label>`:''}<p id="delete-error" class="error" role="alert"></p><div class="dialog-actions"><button class="secondary" data-close="action-dialog">Отмена</button><button class="danger-solid" data-v2="confirm-delete">Удалить ${kind==='order'?'заказ':'фотографии'}</button></div>`;if(!$('#action-dialog').open)$('#action-dialog').showModal();}
document.addEventListener('click',async e=>{const target=e.target.closest('[data-action],[data-order],[data-close],[data-tab],[data-person]');if(!target)return;if(target.dataset.order){location.hash='order/'+target.dataset.order;return;}if(target.dataset.close){$('#'+target.dataset.close).close();return;}if(target.dataset.tab){state.tab=target.dataset.tab;state.selected.clear();renderGroups();return;}if(target.dataset.person){showPerson(target.dataset.person);return;}switch(target.dataset.action){case'new-order':openNew();break;case'choose-upload':location.hash='upload';break;case'choose-persons':location.hash='persons';break;case'move':openMove();break;case'select-all':document.querySelectorAll('#person-dialog [data-photo]').forEach(input=>{input.checked=true;state.selected.add(input.dataset.photo);});$('#person-selected').textContent='Выбрано: '+state.selected.size;break;case'retry':try{await api(`/orders/${state.order.id}/retry${state.view==='photos'&&state.shootId?'?shoot_id='+encodeURIComponent(state.shootId):''}`,json('POST',{}));toast('Обработка запущена повторно');startOrderPolling();await refreshOrder();}catch(e){toast(e.message);}break;}});
document.addEventListener('change',e=>{if(e.target.dataset.photo){if(e.target.checked)state.selected.add(e.target.dataset.photo);else state.selected.delete(e.target.dataset.photo);for(const id of ['#person-selected','#review-selected'])if($(id))$(id).textContent='Выбрано: '+state.selected.size;}});
$('#order-form').onsubmit=async e=>{e.preventDefault();const button=e.target.querySelector('[type=submit]');button.disabled=true;$('#form-error').textContent='';const values=Object.fromEntries(new FormData(e.target));values.copies=Number(values.copies);values.price=Number(values.price);try{const result=await api('/orders',json('POST',values));$('#order-dialog').close();location.hash='order/'+result.id;toast('Заказ создан. Добавьте первую съёмку.');}catch(error){$('#form-error').textContent=error.message;}finally{button.disabled=false;}};
$('#move-form').onsubmit=async e=>{e.preventDefault();const button=e.target.querySelector('[type=submit]');button.disabled=true;try{await api(`/orders/${state.order.id}/move`,json('POST',{photo_ids:[...state.selected],person_id:new FormData(e.target).get('target')||null}));$('#move-dialog').close();$('#person-dialog').close();state.selected.clear();await refreshOrder();toast('Фотографии перенесены');}catch(error){toast(error.message);}finally{button.disabled=false;}};
window.addEventListener('hashchange',()=>{document.querySelectorAll('dialog[open]').forEach(d=>d.close());route();});window.addEventListener('beforeunload',e=>{if(state.uploading){e.preventDefault();e.returnValue='';}});route();
document.addEventListener('click',async e=>{
  const t=e.target.closest('[data-v2],[data-filter],[data-photo-filter]');if(!t)return;
  if(t.dataset.filter){state.filter=t.dataset.filter;chooseOrders(location.hash.slice(1));return;}
  if(t.dataset.photoFilter){state.photoFilter=t.dataset.photoFilter;state.selected.clear();renderWorkspace();return;}
  const action=t.dataset.v2;
  try{
    if(action==='open-client'){const link=await api(`/orders/${state.order.id}/client-link`,json('POST',{}));location.href=link.url;}
    if(action==='toggle-attention'){state.attention=!state.attention;chooseOrders(location.hash.slice(1));}
    if(action==='attention'){state.attention=true;location.hash='orders';}
    if(action==='reset-filters'){state.query='';state.filter='all';state.attention=false;chooseOrders(location.hash.slice(1));}
    if(action==='order-menu')showOrderMenu(t.dataset.id);
    if(action==='close-actions')$('#action-dialog').close();
    if(action==='delete-order')confirmRemoval('order');
    if(action==='delete-photos')confirmRemoval('photos');
    if(action==='add-photos')openShootDialog();
    if(action==='new-shoot')openShootDialog(null,true);
    if(action==='toggle-shoot'){state.shootId=state.shootId===t.dataset.id?null:t.dataset.id;state.photoFilter='all';state.selected.clear();renderWorkspace();}
    if(action==='select-visible'){const photos=visiblePhotos();const all=photos.every(p=>state.selected.has(p.id));photos.forEach(p=>all?state.selected.delete(p.id):state.selected.add(p.id));renderWorkspace();}
    if(action==='set-cover'){if(state.selected.size!==1){toast('Выберите одну фотографию для обложки');return;}await api(`/orders/${state.order.id}/cover`,json('PUT',{photo_ids:[...state.selected]}));toast('Обложка заказа обновлена');}
    if(action==='confirm-photos'){const photos=state.order.photos.filter(p=>state.selected.has(p.id)&&canConfirmMatch(p));if(!photos.length){toast('Выберите совпадения с указанной персоной');return;}t.disabled=true;try{await api(`/orders/${state.order.id}/confirm-photos`,json('POST',{photo_ids:photos.map(p=>p.id),expected_persons:Object.fromEntries(photos.map(p=>[p.id,p.person_id]))}));photos.forEach(p=>state.selected.delete(p.id));await refreshOrder();if($('#person-dialog').open)showPerson(state.person);else if(state.view==='photos')renderWorkspace();else renderGroups();toast(`Подтверждено: ${photos.length}. Остальные снимки можно распределить вручную.`);}finally{syncConfirmation();}}
    if(action==='confirm-delete'){
      const r=state.removal;if(r.kind==='order'&&$('#delete-name').value!==orderName(state.menuOrder)){$('#delete-error').textContent='Название должно совпадать с названием заказа.';return;}
      t.disabled=true;
      try{await api(`/orders/${r.orderId}`+(r.kind==='photos'?'/delete-photos':''),r.kind==='photos'?json('POST',{photo_ids:r.ids}):{method:'DELETE'});$('#action-dialog').close();$('#person-dialog').close();state.selected.clear();if(r.kind==='order'){if(location.hash==='\u0023orders')await route();else location.hash='orders';toast('Заказ удалён');}else{await refreshOrder();if(state.view==='photos')renderWorkspace();toast('Фотографии удалены');}}catch(error){$('#delete-error').textContent=error.message;}finally{t.disabled=false;}
    }
  }catch(error){toast(error.message);}
});

function clientProgress(o,details=false){const c=o.client_progress;if(!c)return '';if(!c.enabled)return details?'<p class="muted">Клиентский кабинет ещё не открыт.</p>':'';return `<div class="client-fill ${c.status==='complete'?'complete':''}"><div><strong>${esc(c.label)}</strong><span>Заполнено ${c.completed} из ${c.total}</span></div><progress max="${c.total||1}" value="${c.completed}" aria-label="Заполнено участников: ${c.completed} из ${c.total}"></progress>${details?`<p class="muted small">${c.total?`Осталось заполнить: ${c.remaining}.`:'Ожидаем появления участников.'} Учитываются сохранённые портрет, имя и фамилия. Цитата необязательна.</p>`:''}</div>`;}

function matchReference(p){return state.order.photos.find(f=>f.person_id===p.person_id&&f.id!==p.id&&f.status==='ready'&&!f.uncertain)||state.order.photos.find(f=>f.person_id===p.person_id&&f.id!==p.id&&f.status==='ready');}
function canConfirmMatch(p){return p.status==='ready'&&!!p.person_id&&!!matchReference(p);}
function matchCaption(p){if(!p.person_id)return '<div class="match-target unmatched">Персона не определена — назначьте вручную</div>';const index=state.order.persons.findIndex(x=>x.id===p.person_id);if(index<0)return '';const person=state.order.persons[index],reference=matchReference(p);return `<div class="match-target">${reference?`<img src="/media/${reference.id}/thumb" alt="Сравнить с ${esc(personName(person,index))}" loading="lazy">`:''}<span><small>${p.uncertain?'Предположительно':'Назначено'}</small><strong>${esc(personName(person,index))}</strong>${!reference?'<small>Нет другого снимка для сравнения</small>':reference.uncertain?'<small>Образец тоже требует проверки</small>':''}</span></div>`;}
function syncConfirmation(){if(!state.order)return;const photos=state.order.photos.filter(p=>state.selected.has(p.id)&&canConfirmMatch(p));const people=[...new Set(photos.map(p=>p.person_id))];const label=people.length===1?personName(state.order.persons.find(p=>p.id===people[0]),state.order.persons.findIndex(p=>p.id===people[0])):null;document.querySelectorAll('[data-v2="confirm-photos"]').forEach(b=>{b.disabled=!photos.length;b.textContent=photos.length?`Подтвердить ${label?label+' · ':''}${photos.length} фото`:'Подтвердить совпадения';});document.querySelectorAll('.confirmation-help').forEach(el=>{el.textContent=photos.length?`Подтверждаются показанные на карточках персоны. ${state.selected.size-photos.length?`Остальные ${state.selected.size-photos.length} снимков останутся для ручного распределения.`:''}`:'Сравните снимки с фото персоны на карточке, отметьте верные совпадения и подтвердите. Остальные можно назначить вручную или удалить.';});}
document.addEventListener('change',e=>{if(e.target.dataset.photo)syncConfirmation();});
document.addEventListener('click',e=>{const b=e.target.closest('[data-v2="select-matches"]');if(b){const available=$('#person-dialog').open?state.order.photos.filter(p=>p.person_id===state.person):state.view==='photos'?visiblePhotos():state.order.photos.filter(needsReview);available.filter(p=>p.uncertain&&canConfirmMatch(p)).forEach(p=>state.selected.add(p.id));document.querySelectorAll('[data-photo]').forEach(i=>{i.checked=state.selected.has(i.dataset.photo);});document.querySelectorAll('#review-selected,#person-selected').forEach(el=>{el.textContent='Выбрано: '+state.selected.size;});}queueMicrotask(syncConfirmation);});

function shootStatus(shoot){const photos=state.order.photos.filter(p=>p.shoot_id===shoot.id),pending=photos.filter(p=>['pending','processing'].includes(p.status)).length,review=photos.filter(needsReview).length;return pending?`<small class="shoot-status">Обработка · ${pending}</small>`:review?`<small class="shoot-status">Проверить · ${review}</small>`:'';}
function openShootDialog(files=null,createOnly=false){
  if(state.uploading){toast('Дождитесь завершения текущей загрузки');return;}
  const orderId=state.order.id,shoots=state.order.shoots||[],active=shoots.find(s=>s.id===state.shootId);
  $('#action-content').innerHTML=`<form id="shoot-form"><div class="dialog-heading"><h2>${createOnly?'Добавить съёмку':'Загрузить фотографии'}</h2><button type="button" class="close" data-close="action-dialog" aria-label="Закрыть">×</button></div>${!createOnly&&shoots.length?`<label>Куда загрузить<select name="destination">${shoots.map(s=>`<option value="${s.id}" ${s.id===active?.id?'selected':''}>${esc(s.title)} · ${s.kind==='portrait'?'Портретная':'Общая'}</option>`).join('')}<option value="new">＋ Новая съёмка</option></select></label>`:''}<div id="new-shoot-fields"><label>Тип съёмки<select name="kind"><option value="portrait">Портретная</option><option value="general">Общая</option></select></label><label>Название<input name="title" maxlength="100" placeholder="Например, Портреты или Прогулка" value="Портреты" required></label><p class="muted small">Портреты группируются по персонам. Общие фотографии пока сохраняются без автоматической сортировки.</p></div>${!createOnly&&!files?'<label>Фотографии<input name="photos" type="file" accept="image/jpeg,image/png,.jpg,.jpeg,.png" multiple required></label>':''}${files?`<p class="muted">Выбрано файлов: ${files.length}</p>`:''}<p id="shoot-error" class="error" role="alert"></p><div class="dialog-actions"><button type="button" class="secondary" data-close="action-dialog">Отмена</button><button type="submit" class="primary">${createOnly?'Добавить съёмку':'Загрузить'}</button></div></form>`;
  const form=$('#shoot-form'),destination=form.elements.destination,fields=$('#new-shoot-fields');
  const update=()=>{const isNew=!destination||destination.value==='new';fields.hidden=!isNew;form.elements.title.required=isNew;};
  if(destination)destination.onchange=update;update();
  form.elements.kind.onchange=()=>{if(['Портреты','Общая съёмка'].includes(form.elements.title.value))form.elements.title.value=form.elements.kind.value==='portrait'?'Портреты':'Общая съёмка';};
  form.onsubmit=async e=>{e.preventDefault();const submit=form.querySelector('[type=submit]');submit.disabled=true;try{let id=destination?.value;if(!id||id==='new'){const result=await api(`/orders/${orderId}/shoots`,json('POST',{kind:form.elements.kind.value,title:form.elements.title.value.trim()}));id=result.id;}await refreshOrder();state.shootId=id;state.selected.clear();state.photoFilter='all';const selected=files||[...(form.elements.photos?.files||[])];$('#action-dialog').close();if(state.view!=='photos'){location.hash=`order/${orderId}/photos`;}else renderWorkspace();if(!createOnly)await uploadFiles(selected);}catch(error){$('#shoot-error').textContent=error.message;}finally{submit.disabled=false;}};
  $('#action-dialog').showModal();
}
